objects/Account.object
<CustomObject>
    <fields>
        <fullName>crm_pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>contains Bradycardia, Tachycardia, Diagnostic</description>
        <label>CRM Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>CRM_Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>manufacturer__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Manufacturer from this picklist.</description>
        <label>Manufacturer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BIOTRONIK</fullName>
                    <default>true</default>
                    <label>BIOTRONIK</label>
                </value>
                <value>
                    <fullName>5500_APC</fullName>
                    <label>AMERICAN PACEMAKER CORP.</label>
                </value>
                <value>
                    <fullName>5500_ACO</fullName>
                    <label>ANGEION CORP.</label>
                </value>
                <value>
                    <fullName>5500_BME</fullName>
                    <label>BIOMEC</label>
                </value>
                <value>
                    <fullName>5500_BSX</fullName>
                    <label>BOSTON SCIENTIFIC</label>
                </value>
                <value>
                    <fullName>5500_CAC</fullName>
                    <label>CARDIAC CONTROL</label>
                </value>
                <value>
                    <fullName>5500_CAI</fullName>
                    <label>CARDIAC IMPULSE</label>
                </value>
                <value>
                    <fullName>5500_CAP</fullName>
                    <label>CARDIAC PACEMAKER</label>
                </value>
                <value>
                    <fullName>5500_CPR</fullName>
                    <label>CARDIAC PRODUCTS</label>
                </value>
                <value>
                    <fullName>5500_CPM</fullName>
                    <label>CARDIO-PACE MEDICAL</label>
                </value>
                <value>
                    <fullName>5500_CHR</fullName>
                    <label>CHRONIC</label>
                </value>
                <value>
                    <fullName>5500_COK</fullName>
                    <label>COOK</label>
                </value>
                <value>
                    <fullName>5500_COI</fullName>
                    <label>CORATOMIC INC.</label>
                </value>
                <value>
                    <fullName>5500_COR</fullName>
                    <label>CORDIS</label>
                </value>
                <value>
                    <fullName>5500_DAI</fullName>
                    <label>DAIG CORP.</label>
                </value>
                <value>
                    <fullName>5500_ES</fullName>
                    <label>EA</label>
                </value>
                <value>
                    <fullName>5500_ELM</fullName>
                    <label>ELA MEDICAL</label>
                </value>
                <value>
                    <fullName>5500_ELS</fullName>
                    <label>ELS</label>
                </value>
                <value>
                    <fullName>5500_ENP</fullName>
                    <label>ENPATH MEDICAL INC.</label>
                </value>
                <value>
                    <fullName>5500_GRE</fullName>
                    <label>GREATBATCH</label>
                </value>
                <value>
                    <fullName>5500_GDT</fullName>
                    <label>GUIDANT</label>
                </value>
                <value>
                    <fullName>5500_IMP</fullName>
                    <label>IMPLANTRONIK</label>
                </value>
                <value>
                    <fullName>5500_INA</fullName>
                    <label>INHO A</label>
                </value>
                <value>
                    <fullName>5500_INH</fullName>
                    <label>INHOUEE</label>
                </value>
                <value>
                    <fullName>5500_INN</fullName>
                    <label>INHOUSEN</label>
                </value>
                <value>
                    <fullName>5500_INO</fullName>
                    <label>INNOMEDICA LTD.</label>
                </value>
                <value>
                    <fullName>5500_INT</fullName>
                    <label>INTERMEDICS INC.</label>
                </value>
                <value>
                    <fullName>5500_MDO</fullName>
                    <label>MEDICO</label>
                </value>
                <value>
                    <fullName>5500_MDT</fullName>
                    <label>MEDTRONIC, INC</label>
                </value>
                <value>
                    <fullName>5500_MYO</fullName>
                    <label>MYOPORE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                    <isActive>false</isActive>
                    <label>Change</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                    <isActive>false</isActive>
                    <label>Retirement</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>declined_to_provide_address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_dob__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide DOB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_ssn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide SSN</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>us_patient</fullName>
        <active>true</active>
        <label>Patient</label>
    </recordTypes>
    <recordTypes>
        <fullName>us_physician</fullName>
        <active>true</active>
        <label>Physician</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that BIOTRONIK representative was not present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Implanted</fullName>
                </value>
                <value>
                    <fullName>Explanted</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Partially Capped</fullName>
                </value>
                <value>
                    <fullName>Patient Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Implantable Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/System_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>System Rule</label>
    <nameField>
        <displayFormat>SysRule-{0000}</displayFormat>
        <label>System Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/SystemPricing_Test.cls
@isTest
public class SystemPricing_Test {

    public static final Boolean DO_PRINTLINE_DEBUGGING = false;
    
    public static final String ORDER_NAME = 'MyTestOrder';
    public static final Integer NUMBER_OF_RULES_IN_TEST = 5;
    public static final String RT_CONTACT_PATIENT   = 'us_patient';
    public static final String RT_CONTACT_PHYSICIAN = 'us_physician';

    public static final String ASS_MANUFACTURER = 'BIOTRONIK';

    static String namePrefix = '';
    
    @testSetup
    public static void setupSystemPricingEnvironment () {
        // We need
        // - An Account
        // - An Order
        // - -Assets
        // - + OrderItem
        // - Products
        // - System Rules
        
        System.debug('Syspri: Generate UUID');
        
        Blob b = Crypto.GenerateAESKey(128);
        namePrefix = EncodingUtil.ConvertTohex(b).left(8);
        
        Id stdPbId = Test.getStandardPricebookId();
        if(DO_PRINTLINE_DEBUGGING) { System.debug('Syspri: StandardPriceBookId = ' + stdPbId); }
        Pricebook2 pb = new Pricebook2(Name = namePrefix + ' Testing Pricebook', CurrencyIsoCode = 'USD');
        insert pb; 
        if(DO_PRINTLINE_DEBUGGING) { System.debug('Syspri: PriceBookId = ' + pb.Id); }

        System.debug('Syspri: Generate Account');
        Account acc = new Account (Name = namePrefix + 'Account', status__c = 'Active', crm_pricebook__c = pb.Id);
        insert acc;
        Id AccountId = acc.Id;

        
        Id rtIdPatient = Utility.getRecordTypeId(Contact.SObjectType, Constants.RECORD_TYPE_NAME_CONTACT_US_PATIENT);

        
        Contact c = new Contact (FirstName = 'Capital_letter', LastName = 'ConName',
                                     declined_to_provide_address__c = True, declined_to_provide_dob__c = True, 
                                     //declined_to_provide_fname__c  = True, SAFBIO 1365
                                     declined_to_provide_phone__c = True, 
                                     declined_to_provide_ssn__c  = True,
                                    RecordTypeId = rtIdPatient,
                                    MailingCountry = null, status__c = 'Active');
        
        insert c;
        
        System.debug('Syspri: Generate Order');
        Order o = new Order (Name = ORDER_NAME, AccountId = acc.Id, EffectiveDate = Date.today().addDays(-5),
                             Status = 'Draft', Pricebook2Id = pb.Id
                             , no_rep_present_at_implant__c = true, patient__c = c.id
                            );
        insert o;
        System.debug('Syspri: Generate products');
        // -------------- products ------------------
        List<Product2> products = new List<Product2>();
        Product2 prodPM = new Product2 (Name = namePrefix + 'TestProduct_PM', product_type__c = 'Pacemaker', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodPM);
        
        Product2 prodLead1 = new Product2 (Name = namePrefix + 'TestProduct_Lead1', product_type__c = 'Lead', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodLead1);
        
        Product2 prodLead2 = new Product2 (Name = namePrefix + 'TestProduct_Lead2', product_type__c = 'Lead', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodLead2);

        Product2 prodLead3 = new Product2 (Name = namePrefix + 'TestProduct_Lead3', product_type__c = 'Lead', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodLead3);
        
        Product2 prodSystem1 = new Product2 (Name = namePrefix + 'TestSystemProduct_1', product_type__c = 'System', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodSystem1);
        
        Product2 prodSystem2 = new Product2 (Name = namePrefix + 'TestSystemProduct_2', product_type__c = 'System', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodSystem2);
        
        Product2 prodSystem3 = new Product2 (Name = namePrefix + 'TestSystemProduct_3', product_type__c = 'System', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodSystem3);
        
        Product2 prodSystem4 = new Product2 (Name = namePrefix + 'TestSystemProduct_4', product_type__c = 'System', IsActive = true, manufacturer__c = ASS_MANUFACTURER);
        products.add(prodSystem4);
        
        System.debug('Syspri: Insert products');
        insert products;

        System.assert(prodPM.Id != null, 'Pacemaker Product has no ID');
        
        List<PricebookEntry> pbes = new List<PricebookEntry>();
        
        if(DO_PRINTLINE_DEBUGGING) { 
            System.debug('Syspri: PricebookEntry - system1 = ' + prodSystem1.Id);
            System.debug('Syspri: PricebookEntry - system2 = ' + prodSystem2.Id);
            System.debug('Syspri: PricebookEntry - system3 = ' + prodSystem3.Id);
            System.debug('Syspri: PricebookEntry - system4 = ' + prodSystem4.Id);
        }
        
        System.debug('Syspri: Creating PricebookEntries');
        // StandardPricebooks
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem1.Id, Pricebook2Id = stdPbId, UnitPrice = 10000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem2.Id, Pricebook2Id = stdPbId, UnitPrice = 12000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem3.Id, Pricebook2Id = stdPbId, UnitPrice = 14000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem4.Id, Pricebook2Id = stdPbId, UnitPrice = 16000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodPM.Id, Pricebook2Id = stdPbId, UnitPrice = 10000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodLead1.Id, Pricebook2Id = stdPbId, UnitPrice = 10000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodLead2.Id, Pricebook2Id = stdPbId, UnitPrice = 5000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodLead3.Id, Pricebook2Id = stdPbId, UnitPrice = 6000, CurrencyIsoCode = 'USD'));
        
        // Custom Pricebooks
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem1.Id, Pricebook2Id = pb.Id, UnitPrice = 10000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem2.Id, Pricebook2Id = pb.Id, UnitPrice = 12000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem3.Id, Pricebook2Id = pb.Id, UnitPrice = 14000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodSystem4.Id, Pricebook2Id = pb.Id, UnitPrice = 16000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodPM.Id, Pricebook2Id = pb.Id, UnitPrice = 40000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodLead1.Id, Pricebook2Id = pb.Id, UnitPrice = 100, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodLead2.Id, Pricebook2Id = pb.Id, UnitPrice = 5000, CurrencyIsoCode = 'USD'));
        pbes.add(new PricebookEntry(IsActive = true, Product2Id = prodLead3.Id, Pricebook2Id = pb.Id, UnitPrice = 6000, CurrencyIsoCode = 'USD'));
        
        System.debug('Syspri: inserting Pricebook2Entry');
        insert pbes;

        List<PricebookEntry> ourPbEs = [SELECT Id, Product2Id, UnitPrice FROM PricebookEntry WHERE Pricebook2Id = :pb.Id];
        Map<Id, PricebookEntry> pbMap = new Map<Id, PricebookEntry> ();
        for(PricebookEntry pbE : ourPbEs) {
            pbMap.put(pbE.Product2Id, pbE);
        }
        
        System.debug('Syspri: Generate OrderItems ');
        // -------------- assets ------------------
        List<OrderItem> orderItems = new List<OrderItem>();
        
        PricebookEntry currEntry = pbMap.get(prodPM.Id);
        // TODO: Create associated Assets!
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodPM.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        currEntry = pbMap.get(prodLead1.Id);
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodLead1.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodLead1.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodLead1.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodLead1.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        currEntry = pbMap.get(prodLead2.Id);
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodLead2.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodLead2.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        orderItems.add(new OrderItem (OrderId = o.id, Product2Id = prodLead3.Id, Quantity = 1, PricebookEntryId = currEntry.Id, UnitPrice = currEntry.UnitPrice));
        System.debug('Syspri: Insert OrderItems (');
        insert orderItems;
        
        List<Asset> assets = new List<Asset>();
        Integer assIdx = 0;
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodPM.Id, product_type__c = prodPM.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodPM.Name, AccountId = o.AccountId, Status = 'Implanted'));
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodLead1.Id, product_type__c = prodLead1.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodLead1.Name, AccountId = o.AccountId, Status = 'Implanted'));
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodLead1.Id, product_type__c = prodLead1.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodLead1.Name, AccountId = o.AccountId, Status = 'Implanted'));
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodLead1.Id, product_type__c = prodLead1.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodLead1.Name, AccountId = o.AccountId, Status = 'Implanted'));
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodLead1.Id, product_type__c = prodLead1.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodLead1.Name, AccountId = o.AccountId, Status = 'Implanted'));
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodLead2.Id, product_type__c = prodLead2.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodLead2.Name, AccountId = o.AccountId, Status = 'Implanted'));
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodLead2.Id, product_type__c = prodLead2.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodLead2.Name, AccountId = o.AccountId, Status = 'Implanted'));
        assets.add(new Asset(order_product__c = orderItems.get(assIdx++).Id, Product2Id = prodLead3.Id, product_type__c = prodLead3.product_type__c,
                            manufacturer__c = ASS_MANUFACTURER, SerialNumber = '123456',
                                           Name = prodLead2.Name, AccountId = o.AccountId, Status = 'Discarded',
                            event_reason__c = 'Upgrade')); // OOS_Reason__c necessary because of Flow restrictions introduced later in the game.
        insert assets;
        
        // -------------- system rules ------------------
        
        
        // Allow 2 of "Name contains Lead1"
        system_rule__c sr_1 = new system_rule__c(system_product__c = prodSystem1.Id, product__c = prodPM.Id, max_quantity__c = 5,
                                                 rule_field__c = 'Name', rule_value__c = 'Lead1',
                                                 name__c = namePrefix + '_sr_1');
        insert sr_1;
        
        // Allow 3 of either "Name contains Lead1" or "Name contains Lead2"
        system_rule__c sr_2 = new system_rule__c(system_product__c = prodSystem2.Id, product__c = prodPM.Id, max_quantity__c = 3,
                                                 name__c = namePrefix + '_sr_2');
        insert sr_2;
        system_rule__c sr_2_1 = new system_rule__c(parent_rule__c = sr_2.Id, rule_field__c = 'Name', rule_value__c = 'Lead1');
        insert sr_2_1;
        system_rule__c sr_2_2 = new system_rule__c(parent_rule__c = sr_2.Id, rule_field__c = 'Name', rule_value__c = 'Lead2');
        insert sr_2_2;
        
        // Allow 2 of either "Name contains Lead1" or "Name contains Lead2"
        system_rule__c sr_3 = new system_rule__c(system_product__c = prodSystem3.Id, product__c = prodPM.Id, max_quantity__c = 2,
                                                 name__c = namePrefix + '_sr_3');
        insert sr_3;
        system_rule__c sr_3_1 = new system_rule__c(parent_rule__c = sr_3.Id, rule_field__c = 'Name', rule_value__c = 'Lead1');
        insert sr_3_1;
        system_rule__c sr_3_2 = new system_rule__c(parent_rule__c = sr_3.Id, rule_field__c = 'Name', rule_value__c = 'Lead2');
        insert sr_3_2;
        
        // Allow any number of "Name contains Lead3"
        system_rule__c sr_4 = new system_rule__c(system_product__c = prodSystem4.Id, product__c = prodPM.Id, max_quantity__c = 2,
                                                 rule_field__c = 'Name', rule_value__c = 'Lead3',
                                                 name__c = namePrefix + '_sr_4');
        insert sr_4;
        
        // Complicated rule for deep excess test
        system_rule__c sr_5 = new system_rule__c(system_product__c = prodSystem3.Id, product__c = prodPM.Id, max_quantity__c = 1,
                                                 name__c = namePrefix + '_sr_5');
        insert sr_5;
        
        system_rule__c sr_5_1 = new system_rule__c(parent_rule__c = sr_5.Id, rule_field__c = 'Name', rule_value__c = 'Lead');
        insert sr_5_1;
        
        system_rule__c sr_5_1_1 = new system_rule__c(parent_rule__c = sr_5_1.Id);
        insert sr_5_1_1;
        
        system_rule__c sr_5_1_1_1 = new system_rule__c(parent_rule__c = sr_5_1_1.Id);
        insert sr_5_1_1_1;
        
        system_rule__c sr_5_1_1_1_1 = new system_rule__c(parent_rule__c = sr_5_1_1_1.Id, rule_field__c = 'Name', rule_value__c = 'Lead1',
                                                         max_quantity__c = 1);
        insert sr_5_1_1_1_1;
        
    }
    

    public static void testSystemPricing() {
        List<SystemPricing_SystemRuleBucket> mainBuckets = new List<SystemPricing_SystemRuleBucket>();  
        Set<Id> relatedProducts = new Set<Id>();
        
        // Find our Order...
        List<Order> orders = [SELECT Id FROM Order WHERE Name = :ORDER_NAME];
        System.assertEquals(1, orders.size(), 'Cannot reliably find my test Order');
        
        Test.startTest();
        
        // Read all products which are related to the order
        List<SystemPricing_ProductHolder> allLinkedProducts = SystemPricingController_Helper.readAllProducts(orders[0].Id, relatedProducts);
        System.assertEquals(7, allLinkedProducts.size());
        System.assertEquals(3, relatedProducts.size());
        
        // Read all applicable rules and fill the mainBuckets list.
        System.debug('Syspri: StandardPriceBookId = ' + Test.getStandardPricebookId());

        if(DO_PRINTLINE_DEBUGGING) { 
            List<PricebookEntry> pbes = [SELECT Id, Product2Id, Pricebook2Id FROM PricebookEntry WHERE Pricebook2Id = :Test.getStandardPricebookId()];
            for(PricebookEntry pbe : pbes) {
                System.debug('Syspri: PricebookEntry ProdId = ' + pbe.Product2Id + ' PB-Id: ' + pbe.Pricebook2Id);
            }
        }

        SystemPricingController_Helper.populateRuleBuckets(mainBuckets, relatedProducts, Test.getStandardPricebookId(), 'USD');
        
        System.assertEquals(NUMBER_OF_RULES_IN_TEST, mainBuckets.size(), 
                            'We created ' + NUMBER_OF_RULES_IN_TEST + ' rules, but got ' + mainBuckets.size() + ' buckets back.');
        
        // Now try and match the products
        // There can be more than one possible system
        for (SystemPricing_SystemRuleBucket currBucket : mainBuckets) {
            for(SystemPricing_ProductHolder curr : allLinkedProducts) {
                System.debug ('checkAndAddProduct(' + curr + ')');
                currBucket.checkAndAddProduct(curr);                
            }
            
            System.debug('Syspri: current bucket (' + currBucket.getRuleName() + ') holds ' + currBucket.getNumberOfMatchedProducts() + ' before removal.');
            If(currBucket.areThereExcessiveNumbersOfProducts()) { System.debug('Syspri: current bucket has excess.');  }
            // The SystemRuleBucket should have been filled now (if applicable)
            // So we clean out the excessive amounts. 
            
            currBucket.removeExcess();

            System.debug('Syspri: current bucket (' + currBucket.getRuleName() + ') holds ' + currBucket.getNumberOfMatchedProducts() + ' after removal.');
            If(currBucket.areThereExcessiveNumbersOfProducts()) { System.debug('Syspri: current bucket STILL has excess.');  }
            // Printline debugging...
            // currBucket.debugHierarchy(0);
            
            // Now check if the results are what we expected
            // For each rule - hopefully there are no rules for our special device other than those we created - we check
            // for overall count as well as the specific type matches.
            if(currBucket.getRule().name__c.containsIgnoreCase('_sr_1')) {
                System.assertEquals(4,currBucket.getNumberOfMatchedProducts(),'Expected all the 4 Lead1 products.');
                Integer prodCount = 0;
                for(SystemPricing_ProductHolder ph : currBucket.getMatchedProducts()) {
                    System.assert(((String)ph.getProdProp('Name')).containsIgnoreCase('Lead1'), 'There should only be Lead1 Products');
                    prodCount++;
                }
                System.assertEquals(4,prodCount, 'Recount does not match.');
            }
            else if(currBucket.getRule().name__c.containsIgnoreCase('_sr_2')) {
                System.assertEquals(3,currBucket.getNumberOfMatchedProducts(),'Expected 3 products.');
                Integer lead1Count = 0, lead2Count = 0;
                for(SystemPricing_ProductHolder ph : currBucket.getMatchedProducts()) {
                    String prodName = (String)ph.getProdProp('Name');
                    if(prodName.containsIgnoreCase('Lead1')) {
                        lead1Count++;
                    }
                    if(prodName.containsIgnoreCase('Lead2')) {
                        lead2Count++;
                    }
                }
                System.assertEquals(2, lead2Count);
                System.assertEquals(1, lead1Count);
                
            }
            else if(currBucket.getRule().name__c.containsIgnoreCase('_sr_3')) {
                System.assertEquals(2,currBucket.getNumberOfMatchedProducts(),'Expected 2 products.');
                Integer lead1Count = 0, lead2Count = 0;
                for(SystemPricing_ProductHolder ph : currBucket.getMatchedProducts()) {
                    String prodName = (String)ph.getProdProp('Name');
                    if(prodName.containsIgnoreCase('Lead1')) {
                        lead1Count++;
                    }
                    if(prodName.containsIgnoreCase('Lead2')) {
                        lead2Count++;
                    }
                }
                System.assertEquals(2, lead2Count);
                System.assertEquals(0, lead1Count);
                
            }
            else if(currBucket.getRule().name__c.containsIgnoreCase('_sr_4')) {
                // Even though rulke 4 matches 'Lead3' and we have inserted an entry, the asssociated Asset is set to 'discarded' - this should not be 
                // matching!
                System.assertEquals(0,currBucket.getNumberOfMatchedProducts(),'Expected no products.');
            }
            else if(currBucket.getRule().name__c.containsIgnoreCase('_sr_5')) {
                System.assertEquals(1,currBucket.getNumberOfMatchedProducts(),'Expected 1 product.');
                System.assert(((String)currBucket.getMatchedProducts()[0].getProdProp('Name')).containsIgnoreCase('Lead1'), 'There should only be Lead1 Products');
                
            }
            
            
        }
        
        
        // Up to here we have tested that the logic itself seems to work as designed.
        // Now for testing the page in combination with its controller.
        // This is mostly smoke testing, but it makes sure that the page gets all necessary information
        // from the controller.
        
        PageReference pref = Page.SystemPricing;
        
        pref.getParameters().put('id',orders[0].id);
        
        Test.setCurrentPage(pref);
        
        System.debug('Syspri: testing controller');
        ApexPages.StandardController con = new ApexPages.StandardController(orders[0]);
        SystemPricingPreController preExt = new SystemPricingPreController(con);
        SystemPricingController ext = new SystemPricingController(con);

        ext.getCurrency();
        List<SystemPricing_SystemRuleBucket> buckets = ext.getMatchedSystems();
        if(buckets.size() > 0) {
            System.currentPageReference().getParameters().put('sysid', buckets[0].getRule().Id);
        }
        ext.selectSystem();
        preExt.initInfo();
        ext.cancelSystem();

        // And now for pure percentage raising, aka SmokeTest
        Product2 tprod = [SELECT Id, Name FROM Product2 WHERE Name LIKE '%TestProduct%' LIMIT 1];
        SystemPricing_ProductHolder ph = new SystemPricing_ProductHolder(tprod);
        system_rule__c sr = new system_rule__c(parent_rule__c = orders[0].Id);
        SystemPricing_SystemRuleBucket srb;
        try {
            srb = new SystemPricing_SystemRuleBucket(sr, 200, 'Syspri Test System', null);
            System.assert(false);
        }
        catch(Exception e) {
            System.assert(true);
        }
        sr.parent_rule__c = null;
        srb = new SystemPricing_SystemRuleBucket(sr, 200, 'Syspri Test System', null);
        srb.parBucket = srb;
        try {
            srb = new SystemPricing_SystemRuleBucket(sr, srb);
            System.assert(false);
        }
        catch(Exception e) {
            System.assert(true);
        }
        
        

    }

    @isTest
    public static void testAsSales() {
        List<Profile> profs = [Select Name, id FROM profile WHERE Name = 'Sales'];
        System.assertEquals(1, profs.size());
        Id salesProfileId = profs[0].Id;

        System.assertNotEquals(null, salesProfileId);

        List<Order> orders = [SELECT Id, OwnerId FROM Order WHERE Name = :ORDER_NAME];
        System.assertEquals(1, orders.size(), 'Cannot reliably find my test Order');

        User salesUser = TestDataFactory.createUser(salesProfileId, 'myS');
        insert salesUser;

        orders[0].OwnerId = salesUser.Id;
        update orders;

        System.runAs(salesUser) {
            testSystemPricing();
        }
    }

    @isTest
    public static void testAsInsidesales() {
        List<Profile> profs = [Select Name, id FROM profile WHERE Name = 'Inside Sales'];
        System.assertEquals(1, profs.size());
        Id insidesalesProfileId = profs[0].Id;

        System.assertNotEquals(null, insidesalesProfileId);

        List<Order> orders = [SELECT Id, OwnerId FROM Order WHERE Name = :ORDER_NAME];
        System.assertEquals(1, orders.size(), 'Cannot reliably find my test Order');

        User insidesalesUser = TestDataFactory.createUser(insidesalesProfileId, 'myIS');
        insert insidesalesUser;

        orders[0].OwnerId = insidesalesUser.Id;
        update orders;

        System.runAs(insidesalesUser) {
            testSystemPricing();
        }

    }

    /* Tests accessibility for all necessary fields.
     *
     */
/*    @isTest
    public static void testAccessControl() {
        List<Profile> profs = [Select Name, id FROM profile WHERE Name like '%Sales%'];
        Id salesProfileId, insidesalesProfileId;
        for(Profile p : profs) {
            if(p.Name == 'Sales') {
                salesProfileId = p.Id;
            }
            else if (p.name == 'Inside Sales') {
                insidesalesProfileId = p.Id;
            }
        }

        System.assertNotEquals(null, salesProfileId);
        System.assertNotEquals(null, insidesalesProfileId);

        User salesUser = TestDataFactory.createUser(salesProfileId);
        User insidesalesUser = TestDataFactory.createUser(insidesalesProfileId);


        List<String> objCreate = new List<String> { 'OrderItem', 'Asset' };

            List<String> objDelete = new List<String> {
                        'OrderItem', 'Asset'
                    };

                        List<String> objUpdate = new List<String> {
                            'OrderItem', 'Asset'
                                };

                    List<String> objRead = new List<String> {
                        'Order', 'OrderItem', 'Asset'
        };

            System.runAs(salesUser) {


            }


        List<String> fieldsRW = new List<String> {

        };


    }
*/
}