objects/Account.object
<CustomObject>
    <fields>
        <fullName>crm_pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>contains Bradycardia, Tachycardia, Diagnostic</description>
        <label>CRM Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>CRM_Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>batch_no__c</fullName>
        <description>Unique alphanumeric identifier of a lot of products</description>
        <label>Batch No.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>expired_ubd_acknowledged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The user has to acknowledge that he knows, that the UBD is in the past the moment he edits/created the record</description>
        <label>Expired UBD acknowledged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linkage to the  Order record</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ubd_expired__c</fullName>
        <description>Shows that the asset is expired. It is not recommended to use the product if this field shows &quot;true&quot;.</description>
        <formula>expiration_date_ubd__c  &lt; TODAY ()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBD expired</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>implant_date__c</fullName>
        <description>Defines the date of the implant procedure.</description>
        <inlineHelpText>Date of the Implant Procedure</inlineHelpText>
        <label>Implant date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>barcode__c</fullName>
        <label>Barcode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_no__c</fullName>
        <description>Unique alphanumeric identifier of a lot of products</description>
        <label>Batch No.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>expired_ubd_acknowledged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The user has to acknowledge that he knows, that the UBD is in the past the moment he edits/created the record</description>
        <label>Expired UBD acknowledged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>implant_date__c</fullName>
        <label>Implant date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Implanted</fullName>
                </value>
                <value>
                    <fullName>Explanted</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Partially Capped</fullName>
                </value>
                <value>
                    <fullName>Patient Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Implantable Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ubd_expired__c</fullName>
        <description>Shows that the asset is expired. It is not recommended to use the product if this field shows &quot;true&quot;.</description>
        <formula>expiration_date_ubd__c &lt; TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBD expired</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>EAN__c</fullName>
        <label>EAN</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductConsumed.object
<CustomObject>
    <fields>
        <fullName>expired_ubd_acknowledged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The user has to acknowledge that he knows, that the UBD is in the past the moment he edits/created the record</description>
        <label>Expired UBD acknowledged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>implant_date__c</fullName>
        <label>Implant Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the patient record</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Products Consumed (Patient)</relationshipLabel>
        <relationshipName>Products_Consumed1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>Product type defined by the picklist located in the related Product Item record.</description>
        <formula>TEXT(ProductItem.product_type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>The status of the device.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implanted</fullName>
                </value>
                <value>
                    <fullName>Explanted</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Partially Capped</fullName>
                </value>
                <value>
                    <fullName>Patient Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Implantable Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ubd_expired__c</fullName>
        <description>Shows that the asset is expired. It is not recommended to consume the device if this field shows &quot;true&quot;.</description>
        <formula>expiration_date_ubd__c &lt; TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBD expired</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductItem.object
<CustomObject>
    <fields>
        <fullName>barcode__c</fullName>
        <label>Barcode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_no__c</fullName>
        <description>Unique alphanumeric identifier of a lot of products</description>
        <label>Batch No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ubd_expired__c</fullName>
        <formula>(expiration_date_ubd__c &lt; TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBD Expired</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implant Procedures</relationshipLabel>
        <relationshipName>Implants_Procedures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/AddProdManually.cls
/* Created by Florian Heer <f.heer@conciscon.de>
 * 
 * Runs without sharing, hoping to solve SAFBIO-2348 with that.
 */

public without sharing class AddProdManually {
    
    /** Performs a substring search on ProductItems
     * 
     * @param searchText the text to search for. This is treated as a substring.
     * @param orderId the Id of the order. Necessary to filter for available products according to the pricebook.
     * @return a List of all available Product Items, filtered by Pricebook-availability and search text
     */    
    @AuraEnabled
    public static List<ProductItem> searchForProductItems(String searchText, String orderID) {
        System.debug('AddProdManually: receive parameters searchText: ' + searchText + ' orderID: ' + orderID);
        Id relatedPricebook = [SELECT Account.crm_pricebook__c FROM Order WHERE Id = :orderId LIMIT 1].Account.crm_pricebook__c;
        List<PricebookEntry> pbes = [SELECT Product2Id FROM PricebookEntry WHERE Pricebook2Id = :relatedPricebook];
        List<Id> prodIds = new List<Id>();
        for(PricebookEntry pbe : pbes) prodIds.add(pbe.Product2Id);
        searchText = '%' + searchText + '%';
        System.debug('searchText: "' + searchText + '"');
        List<ProductItem> pis = [SELECT Id, Product2.Name, QuantityOnHand, SerialNumber, batch_no__c, Location.Name, 
                                 ubd_expired__c FROM ProductItem 
                                 WHERE 
                                 (
// Bill requested (SAFBIO-2040) to remove the search by name
//                                     Product2.Name LIKE :searchText OR
                                  Product2.EAN__c LIKE :searchText 
                                  OR barcode__c LIKE :searchText
                                  OR SerialNumber LIKE :searchText
                                 )
                                 AND QuantityOnHand > 0 AND Product2Id IN :prodIds LIMIT 50];
        return pis;
    }

    /** Performs the steps necessary to consume a product item and convert it to OrderItem and Asset
     * 
     * @param piId Id of a ProductItem to consume
     * @param amount how many to consume (should always be one in the current setup)
     * @param orderId the Order to attach the created OrderItem and Asset to. Patient is taken from the related WorkOrder.
     */    
    @AuraEnabled
    public static Asset consumeProduct (String piId, String amount, String orderId, String implantStatus) {
        return consumeProduct (piId, amount, orderId, false, implantStatus);
    }
    
    @AuraEnabled
    public static Asset consumeProduct (String piId, String amount, String orderId) {
        return consumeProduct (piId, amount, orderId, false, Constants.PICKLIST_STATUS_ORDER_ITEM_NOT_IMPLANTABLE_PRODUCT);
    }
    
    public static Asset consumeProduct (String piId, String amount, String orderId, Boolean replenish) {
        return consumeProduct (piId, amount, orderId, replenish, Constants.PICKLIST_STATUS_ORDER_ITEM_NOT_IMPLANTABLE_PRODUCT);
    }
    
    

    public static Asset consumeProduct(String piId, String amount, String orderId, Boolean replenish, String implantStatus) {
        System.debug('AAA apm AddProdManually.consumeProduct("' + piId + '","' + amount + '","' + orderId + '")');
        Integer quantity;
        String error = '';
        try {
            quantity = Integer.valueOf(amount.trim());
        }
        catch (TypeException ex) {
            error = String.format(Label.APM_quantity_not_number, new String [] {amount});
        }
        
        If(Schema.sObjectType.ProductConsumed.isCreateable() && error.length() == 0) {
            Id woliId, workOrderId, patientId;
        	List<WorkOrderLineItem> wolis = [SELECT Id, WorkOrderId, WorkOrder.patient__c FROM WorkOrderLineItem WHERE OrderId = :orderId];
            if(wolis.size() > 0) {
                woliId = wolis[0].Id;
                workOrderId = wolis[0].WorkOrderId;
                patientId = wolis[0].WorkOrder.patient__c;
            }
            else {
                List<WorkOrder> wos =  [SELECT Id, patient__c FROM WorkOrder WHERE order__c = :orderId];
                if(wos.size() > 0) {
                    workOrderId = wos[0].Id;
                    patientId = wos[0].patient__c;
                }
            }
			
            
            Date implantDate;
            for(ServiceAppointment sApp : [SELECT Id, SchedEndTime, ActualEndTime FROM ServiceAppointment WHERE ParentRecordId = :workOrderId]) {
                if(sApp.ActualEndTime != null) {
                    implantDate = sApp.ActualEndTime.dateGMT();
                    break;
                }
                else {
                    implantDate = sApp.SchedEndTime.dateGMT();
                }
            }
            if(implantDate == null) {
                implantDate = Date.today();
            }

            
            ProductItem pi = [SELECT Id, ubd_expired__c, product_type__c FROM ProductItem WHERE Id = :piId LIMIT 1];
            
            
			ProductConsumed pc = new ProductConsumed (ProductItemId = piId, QuantityConsumed = Decimal.valueOf(amount),
                                                     WorkOrderId = workOrderId, WorkOrderLineItemId = woliId, status__c = implantStatus,
                                                     expired_ubd_acknowledged__c = pi.ubd_expired__c,
                                                     patient__c = patientId, implant_date__c = implantDate
                                                     );
            if (pi.product_type__c == Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD){
              	pc.Lead_Tip_Location__c = Constants.PICKLIST_VALUE_LEAD_TIP_LOCATION_UNKNOWN;  
            }
            insert pc;
            Asset ass = WorkOrderConversion.convertProduct(orderId, pc.Id, replenish);
        	return ass;        
        }
        else {
            error += Label.APM_ProductConsumed_not_creatable;
        }

        if(error.length() == 0) {
            // This holds true, as we employ an early return (return ass;)
        	error = Label.APM_generic_error;
        }
        AuraHandledException ex = new AuraHandledException(error);
        ex.setMessage(error);
        throw ex;
    }
    @AuraEnabled
    public static Boolean checkUserPermission(){
        Boolean allowed = false;
        
        List <String> PROFILES_ALLOWED_FOR_ADD_PRODUCT = new List<String>{Constants.PROFILE_NAME_SALES, Constants.PROFILE_NAME_SYSTEM_ADMIN, Constants.PROFILE_Name_System_MMS_FUNC};
        List <String> ROLES_ALLOWED_FOR_ADD_PRODUCT = new List<String>{Constants.User_ROLE_NAME_SO};
        String profileName = Utility.getProfileNameById(UserInfo.getProfileId());
        String userRole = Utility.getUserRoleNameById(UserInfo.getUserRoleId());
        
        if ((PROFILES_ALLOWED_FOR_ADD_PRODUCT.contains(profileName))|| ROLES_ALLOWED_FOR_ADD_PRODUCT.contains(userRole)){
          	allowed = true;  
        }
        return allowed;
    }
}