objects/Account.object
<CustomObject>
    <fields>
        <fullName>crm_pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>contains Bradycardia, Tachycardia, Diagnostic</description>
        <label>CRM Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>CRM_Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_no__c</fullName>
        <description>SAP SHIP-TO account number</description>
        <externalId>true</externalId>
        <label>SAP No</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                    <isActive>false</isActive>
                    <label>Change</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                    <isActive>false</isActive>
                    <label>Retirement</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Referring Physician)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Implanted</fullName>
                </value>
                <value>
                    <fullName>Explanted</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Partially Capped</fullName>
                </value>
                <value>
                    <fullName>Patient Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Implantable Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductConsumed.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the patient record</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Products Consumed (Patient)</relationshipLabel>
        <relationshipName>Products_Consumed1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>Product type defined by the picklist located in the related Product Item record.</description>
        <formula>TEXT(ProductItem.product_type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>The status of the device.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implanted</fullName>
                </value>
                <value>
                    <fullName>Explanted</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Partially Capped</fullName>
                </value>
                <value>
                    <fullName>Patient Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Implantable Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_no__c</fullName>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <inlineHelpText>Physician who referred the patient</inlineHelpText>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Referring Physician)</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <inlineHelpText>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</inlineHelpText>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrderCancellationTest.cls
@isTest
public class OrderCancellationTest {
    static Account objAccount;  
    static Order objOrder;
    static User salesUser;
    static OrderItem ordIt;
    static Asset objAsset;
    
	@isTest
    private static void init() {
		String profileSalesId = Utility.getProfileId(Constants.PROFILE_NAME_SALES);
        salesUser = TestDataFactory.createUser(profileSalesId, 'SalesTes');
        insert salesUser;
        
        Product2 prod = TestDataFactory.createProduct(Constants.RECORD_TYPE_NAME_PRODUCT);
        prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ACCESSORY;
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, UnitPrice = 10000, IsActive = true, Product2Id= prod.Id, CurrencyIsoCode = 'USD');
        insert standardPrice;
        
        objAccount= new Account(Name = 'Test Account', sap_company_code__c = '5500', sap_no__c = '35627', status__c = 'Active', crm_pricebook__c = pricebookId);
        insert objAccount;
        
		Contact physician =  TestDataFactory.createPhysician(false);
    	Contact patient = TestDataFactory.createPatient(true, objAccount.id);
        
         WorkOrder objWorkOrder = new WorkOrder(Status = Constants.PICKLIST_STATUS_VALUE_WORK_ORDER_TRANSMITTED, StartDate = Date.today(), EndDate = Date.today()+20, 
                                                Pricebook2Id = pricebookId, rep_at_implant__c = UserInfo.getUserId(),
                                                patient__c =patient.Id, referring_physician__c= physician.Id, following_physician__c=physician.Id, AccountId = objAccount.Id);
        insert objWorkOrder;
		//WorkOrderToOrderConverter.convertToOrder(objWorkOrder);
		//
		Id orderRtId =  Utility.getRecordTypeId(Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
        objOrder = new Order (AccountId = objAccount.Id, Status = Constants.PICKLIST_VALUE_ORDER_STATUS_NOT_SUBMITTED, EffectiveDate = System.today(), Pricebook2Id = pricebookId,
                              referring_physician__c = physician.Id, patient__c = patient.Id, RecordTypeId = orderRtId, 
                              no_rep_present_at_implant__c  = true, rep_for_credit__c= UserInfo.getUserId());
        objOrder.OwnerId = salesUser.Id;
        insert objOrder;
		objWorkOrder.order__c = objOrder.Id;
        update objWorkOrder;
       
        OrderItem orderItems = TestDataFactory.createOrderItem(objOrder.Id, prod.Id, 'USD', pricebookId);
        objAsset  = TestDataFactory.createAsset(objAccount.Id, prod.Id);
        
        insert objAsset;
        orderItems.asset__c =objAsset.Id;
        ProductConsumed pc = new ProductConsumed(WorkOrderId = objWorkOrder.Id, PricebookEntryId = standardPrice.Id, QuantityConsumed = 2);
        insert pc; 
        OrderItems.product_consumed__c = pc.Id;
        insert orderItems;
    }   
    
    @isTest 
    static void testCancelProcess(){
        init();
        Id patientId = objOrder.patient__c;
      
        System.runAs(salesUser){
         	objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_CANCELED;
         	update objOrder;   
        }
         	
        
        
        List<OrderItem> orderItem = [SELECT Id, asset__c, product_consumed__c FROM OrderItem WHERE OrderId =:objOrder.Id];
        for (OrderItem ot:orderItem){
            System.assertEquals(null, ot.asset__c);
            System.assertEquals(null, ot.product_consumed__c);
        }
        
        
        Order orders = [SELECT Id, patient__c From Order where Id =: objOrder.Id];
        System.assertEquals(null, orders.patient__c);
        
        Contact contacts = [SELECT Id, Status__c from Contact where Id =: patientId];
        System.assertEquals(Constants.PICKLIST_VALUE_CONTACT_STATUS_INACTIVE, contacts.Status__c);
        
        WorkOrder wo = [SELECT Id, order__c, patient__c, Status from WorkOrder where order__c=:objOrder.Id];
        System.assertEquals(Constants.PICKLIST_STATUS_VALUE_WORK_ORDER_CANCELED, wo.Status);
        System.assertEquals(null, wo.patient__c);

    }
    
    @isTest
    static void testCancelNotPermitted(){
        String profileSalesId = Utility.getProfileId(Constants.PROFILE_NAME_SALES);
        salesUser = TestDataFactory.createUser(profileSalesId, 'SalesTes');
        insert salesUser;
        
        objAccount = TestDataFactory.createAccount();
        insert objAccount;
        objOrder = TestDataFactory.createOrder(objAccount.Id);
        objOrder.OwnerId = salesUser.Id;
        
        Contact patient = TestDataFactory.createPatient(true);
        objOrder.patient__c = patient.Id;
        
        Insert objOrder;
        
        OrderItem ordersItems = TestDataFactory.createOrderItem(objOrder.Id);
        
        objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_PROCESSED_SAP;
        update objOrder;
        
        try{
            System.runAs(salesUser){
                objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_CANCELED;
                update objOrder;
            }   
        }catch(Exception e ){
            System.assertEquals(true, e.getMessage().contains(System.Label.ERROR_TO_CANCEL_ORDER));
        } 
    }    
}