objects/Account.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                    <isActive>false</isActive>
                    <label>Change</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                    <isActive>false</isActive>
                    <label>Retirement</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>implanting physician CONTACT record assigned by SFDC
removed Implanting Physician: Account: Account ID = Work Order: Account ID filter criteria</description>
        <inlineHelpText>implanting physician CONTACT record assigned by SFDC</inlineHelpText>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that no BIOTRONIK representative was present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <inlineHelpText>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</inlineHelpText>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_for_credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for sales rep who will receive credit for the sale.</description>
        <inlineHelpText>Identifier for sales rep who will receive credit for the sale.</inlineHelpText>
        <label>Rep for Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WorkOrderUpdatorTest.cls
@isTest 
private class WorkOrderUpdatorTest {
        
    static testMethod void updateWorkOrderredordsTest() {
        workorder wodr = createWorkorder();
        
        //Verifying the rep at Implant and rep at credit are null.
        System.assertEquals(wodr.rep_at_implant__c, null);
        System.assertEquals(wodr.rep_for_credit__c, null);
        
        User u1 =  createUser('test@Testsdsssdsdsds.com');
        User u2 =  createUser('test@Tppppppyyy.com');
        workorder wo = new workorder();
        wo.rep_at_implant__c = u1.id;
        wo.rep_for_credit__c   = u2.id;
        wo.no_rep_present_at_implant__c = false;
        //Updating rep at Implant and rep at credit for a wororder record
        WorkOrderUpdator.updateWorkOrderredords(wo, wodr.id);
        //Verifying the rep at Implant and rep at credit are updated
        workorder wr = [SELECT id,rep_at_implant__c, rep_for_credit__c FROM workorder where id =: wodr.id];
        System.assertEquals(wr.rep_at_implant__c, u1.id);
        System.assertEquals(wr.rep_for_credit__c, u2.id);
        try{
            //Will throw exception 
            wo.no_rep_present_at_implant__c = true;
            WorkOrderUpdator.updateWorkOrderredords(wo, wodr.id);
        } catch(Exception e) {
            System.assertNotEquals(e.getMessage(), null);
        }
        
    }
    
    private static User createUser(String userName) {
        User u = TestDataFactory.createUser(Utility.getProfileId(Constants.PROFILE_NAME_SALES));
        u.Username =  userName;
        insert u;
        return u;
    }
    
    private static WorkOrder createWorkorder() {

        Account acc = new Account();
        acc.Name = 'Testing Acc';
        acc.status__c = 'active';
        insert acc;

        Contact con = TestDataFactory.createPhysician(acc.Id);
        con.FirstName = 'Test';
        con.LastName = 'Cont';
        insert con;

        WorkOrder wo = TestDataFactory.createWorkOrder();
        wo.implanting_physician__c = con.Id;
        insert wo;
        return wo;
    }
}