objects/Account.object
<CustomObject>
    <fields>
        <fullName>sap_no__c</fullName>
        <description>SAP SHIP-TO account number</description>
        <externalId>true</externalId>
        <label>SAP No</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Explant_Date__c</fullName>
        <description>Date the Asset was explanted. In case the Asset goes through a change out process, the field is auto-updated with the implant date value of the replacing Asset.</description>
        <label>Explant Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>explanting_facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the explant</description>
        <label>Explanting Facility</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>x5500_us_account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Other_Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>oos_date__c</fullName>
        <description>Gives the date of the explanation. date can only be inserted if asset has the status &quot;explanted&quot;.
Date device was taken out of service (explanted, capped, or discarded)</description>
        <label>OOS Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linkage to the  Order record</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>order_product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>declined_to_provide_address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_ssn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide SSN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>implanted_product_changed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Invisible for the users. The checkbox is used to determine when a Patient record should be auto-assigned for a Permanent Patient ID card creation.</description>
        <label>Implanted product changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>implanted_product_new_patient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Invisible for the users. The checkbox is used to determine when a Patient record should be auto-assigned for a Permanent Patient ID card creation.</description>
        <label>Implanted product for new patient</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>implant_date__c</fullName>
        <description>Defines the date of the implant procedure.</description>
        <inlineHelpText>Date of the Implant Procedure</inlineHelpText>
        <label>Implant date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>mdrf_reimport_timestamp__c</fullName>
        <description>This field will be used to re import the MDRF.</description>
        <label>MDRF Reimport Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>submit_to_sap__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checkbox which triggers the status change to &apos;Submitted&apos; and Submission process to SAP</description>
        <label>Submit to SAP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>implant_date__c</fullName>
        <label>Implant date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>sap_no__c</fullName>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/user_id__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>stores the user id</description>
    <fields>
        <fullName>binc_default_initial_reporter_s_user_id__c</fullName>
        <label>BINC Default Initial Reporter&apos;s User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>User ID</label>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/AssetHandlerTest.cls
/**
 *
 * Test class for Asset Trigger
 * 
 * @author          snpa 
 * @modifiedBy      Gokul Palagiri
 * @created         2018-04-10
 * @modified        2018-10-25
 * @systemLayer     Test 
 *  
*/
@isTest
private class AssetHandlerTest {
    public static final String SALES_PROFILE = 'Sales';
    
    static Account objAccount;
    static Contact objPatient;  
    static Order objOrder;
    static OrderItem objOrderItem;
    static user testUser;
    
    private static void init() {
        Profile p = [SELECT Id, Name FROM Profile WHERE Name = :SALES_PROFILE];
        Id idUSAccountRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name = 'US Account'].Id; 
        testUser = TestDataFactory.createUser(p.id);
        insert testUser;
        
        System.runAs(testUser) {
            objAccount = TestDataFactory.createAccount();
            objAccount.RecordTypeId=idUSAccountRecordType;
            insert objAccount;

        Id idPateintRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name = 'Patient'].Id;
        objPatient = new Contact(firstname='TEST', lastname= 'CONTACT',
                Birthdate = System.today().addYears(-29),
                declined_to_provide_address__c = true,
                declined_to_provide_phone__c = true,
                declined_to_provide_ssn__c = true,
                accountid = objAccount.Id,
                recordTypeId = idPateintRecordType);
        insert objPatient;            
        
            Id orderRtId =  Utility.getRecordTypeId (Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
            objOrder = TestDataFactory.createOrder(objAccount.Id);
            objOrder.status = Constants.PICKLIST_VALUE_STATUS_NOT_SUBMITTED;
            objOrder.recordTypeId = orderRtId;
            objOrder.submit_to_sap__c = true;
            objOrder.PoNumber = '1234';
            objOrder.OwnerId = testUser.Id;
            objOrder.AccountId = objAccount.Id;
            objOrder.rep_at_implant__c = testUser.Id;
            objOrder.EffectiveDate = System.Today();
            objOrder.implant_date__c = System.Today();
            objOrder.patient__c = objPatient.Id;
            insert objOrder;

            objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            Insert objOrderItem;
        }
    }
    
    /**
     * Method checks if after a asset is linked to a patient
     * a field updates are done
     */
    @isTest
    static void testPatientUpdateForNewAsset() {
        init();
        Id idPateintRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name = 'Patient'].Id;
        
        contact patient = new Contact(firstname='TEST', lastname= 'CONTACT',
                                        Birthdate = System.today().addYears(-29),
                                        declined_to_provide_address__c = true,
                                        declined_to_provide_phone__c = true,
                                        declined_to_provide_ssn__c = true,
                                        accountid = objAccount.Id,
                                        recordTypeId = idPateintRecordType);
        insert patient;
        
        Product2 prod = new Product2(Name = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD);
        prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        insert prod;
        
        System.runAs(testUser) {
            Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objAsset.order__c = objOrder.Id;
            objAsset.order_product__c = objOrderItem.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.patient__c = patient.Id;
            objAsset.Product2Id = prod.Id;

            Test.startTest();        
               insert objAsset;
            Test.stopTest();
            
            patient = [SELECT Id, implanted_product_new_patient__c, implanted_product_changed__c FROM Contact WHERE Id = :patient.Id];
            System.assertEquals(true, patient.implanted_product_changed__c);
            System.assertEquals(true, patient.implanted_product_new_patient__c);
        }
    }
    
    /**
     * Method checks if on the status change of a linked asset
     * a field update on the patient is done
     */
    @isTest
    static void testPatientUpdateForAssetStatusChange() {
        init();
        Id idPateintRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name = 'Patient'].Id;
        
        contact patient = new Contact(firstname='TEST', lastname= 'CONTACT',
                                        Birthdate = System.today().addYears(-29),
                                        declined_to_provide_address__c = true,
                                        declined_to_provide_phone__c = true,
                                        declined_to_provide_ssn__c = true,
                                        accountid = objAccount.Id,
                                        recordTypeId = idPateintRecordType);
        insert patient;
        
        Product2 prod = new Product2(Name = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD);
        prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        insert prod;

        System.runAs(testUser) {
            Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objAsset.order__c = objOrder.Id;
            objAsset.order_product__c = objOrderItem.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.patient__c = patient.Id;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            Test.startTest();
                objAsset.Status = 'Explanted';
                objAsset.Explant_Date__c = Date.today();
                objAsset.oos_date__c = Date.today();
                //objAsset.event_reason_c = 'Infection';
                update objAsset;
            Test.stopTest();

            patient = [SELECT Id, implanted_product_new_patient__c, implanted_product_changed__c FROM Contact WHERE Id = :patient.Id];
            System.assertEquals(true, patient.implanted_product_changed__c);
        }
    } 

    @isTest
    static void testdeleteAsset() {
        init();
        Id idPateintRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name = 'Patient'].Id;
        
        contact patient = new Contact(firstname='TEST', lastname= 'CONTACT',
                                        Birthdate = System.today().addYears(-29),
                                        declined_to_provide_address__c = true,
                                        declined_to_provide_phone__c = true,
                                        declined_to_provide_ssn__c = true,
                                        accountid = objAccount.Id,
                                        recordTypeId = idPateintRecordType);
        insert patient;
        
        Product2 prod = new Product2(Name = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD);
        prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        insert prod;
        
        
        System.runAs(testUser) {
            Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objAsset.order__c = objOrder.Id;
            objAsset.order_product__c = objOrderItem.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.patient__c = patient.Id;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            Test.startTest();        
                delete objAsset;
            Test.stopTest();
            
            patient = [SELECT Id, implanted_product_new_patient__c, implanted_product_changed__c FROM Contact WHERE Id = :patient.Id];
            System.assertEquals(true, patient.implanted_product_changed__c);
        }
    }
    
    @isTest
    static void updateMDRFReimportTimestampTest() {
        init();
        Id idPateintRecordType = Utility.getRecordTypeId(Contact.SObjectType, Constants.RECORD_TYPE_NAME_CONTACT_US_PATIENT);
        
        contact patient = new Contact(firstname='TEST', lastname= 'CONTACT',
                                        Birthdate = System.today().addYears(-29),
                                        declined_to_provide_address__c = true,
                                        declined_to_provide_phone__c = true,
                                        declined_to_provide_ssn__c = true,
                                        accountid = objAccount.Id,
                                        recordTypeId = idPateintRecordType);
        insert patient;

        Product2 prod = new Product2(Name = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD);
        prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        insert prod;
        
        System.runAs(testUser) {
            OrderItem oi = TestDataFactory.createOrderItem(objOrder.id);
            oi.OrderId =  objOrder.Id;
            insert oi;

            Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objAsset.order__c = objOrder.Id;
            objAsset.order_product__c = objOrderItem.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.patient__c = patient.Id;
            objAsset.Product2Id = prod.Id;
            objAsset.order_product__c = oi.id;
            objAsset.InstallDate = Date.Today();
            insert objAsset;
            
            //Inserting custom settings
            user_id__c defaultusr = new user_id__c(binc_default_initial_reporter_s_user_id__c = testUser.id);
            insert defaultusr;
            
            Test.startTest();  
                objAsset.InstallDate = Date.Today().addDays(2);
                update objAsset;
                Asset asst = [Select order_product__r.Order.mdrf_reimport_timestamp__c FROM Asset where Id =: objAsset.id];
                System.Assert(asst.order_product__r <> null);  
           Test.stopTest();
 
        }
    }

    /* Checks if we set the correct contact and account id on insert and update.
     * 
     * 2018-06-13 Florian Heer <f.heer@conciscon.de>
     */
    static testMethod void testContactAndAccountFieldSynchs() {
        Id assetRTId = Utility.getRecordTypeId(Asset.SObjectType, Constants.RECORD_TYPE_NAME_ASSET_US_BIOTRONIK);
        Id orderRtId = Utility.getRecordTypeId(Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);

        init();
        Id idPateintRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name = 'Patient'].Id;
    Test.StartTest();
        Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
        objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        objAsset.order__c = objOrder.Id;
        objAsset.order_product__c = objOrderItem.Id;
        objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
        objAsset.patient__c = objPatient.Id;
        objAsset.InstallDate = Date.Today();
        objAsset.AccountId = objAccount.Id;
        insert objAsset;

        Asset ass = [SELECT Id, ContactId, AccountId FROM Asset WHERE Id = :objAsset.Id LIMIT 1];
        System.assert(ass.AccountId != null, 'Invalid Account Id');
        System.assert(ass.ContactId != null, 'Invalid Contact Id');

        Update objAsset;
        ass = [SELECT Id, ContactId, patient__c, AccountId, explanting_facility__c FROM Asset WHERE Id = :objAsset.Id LIMIT 1];
        System.assert(ass.AccountId != null, 'Invalid Account Id');
        System.assert(ass.ContactId != null, 'Invalid Contact Id');

        Account newAccount = objAccount.Clone();
        newAccount.Name = 'Different Name';
        newAccount.sap_no__c = '2342134';
        insert newAccount;
        objAsset.explanting_facility__c = newAccount.Id;
        objAsset.patient__c = objPatient.Id;
        Update objAsset;
    Test.StopTest();
        ass = [SELECT Id, AccountId, ContactId FROM Asset WHERE Id = :ass.Id LIMIT 1];
        System.assert(ass.AccountId != null, 'Invalid Account Id');
        System.assert(ass.ContactId != null, 'Invalid Contact Id');

    }
    
}