objects/Account.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                    <isActive>false</isActive>
                    <label>Change</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                    <isActive>false</isActive>
                    <label>Retirement</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>declined_to_provide_address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_dob__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide DOB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_ssn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide SSN</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <inlineHelpText>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</inlineHelpText>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WorkOrderLineItemHandlerTest.cls
@isTest
public class WorkOrderLineItemHandlerTest {
	public static final String PREFIX_TEST_NAMES = 'wolit_';

    /* SAFBIO-1332
     * Florian Heer <f.heer@conciscon.de>
     * 2018-06-25
     */ 
    @testSetup
    public static void setupEnvironment() {
        List<RecordType> rts = [SELECT Id FROM RecordType WHERE DeveloperName LIKE '%us_account%' AND SObjectType = 'Account'];
        
        Account acc = New Account(Name = PREFIX_TEST_NAMES + 'Account', RecordTypeId = rts[0].Id, Status__c = 'Active');
        insert acc;
        
        Id rtIdPatient, rtIdPhysician;
        List<RecordTypeInfo> conRTs = Schema.SObjectType.Contact.getRecordTypeInfos();
        for(RecordTypeInfo rti : conRTs) {
            if(rti.getDeveloperName() == Constants.RECORD_TYPE_NAME_CONTACT_US_PATIENT) rtIdPatient = rti.getRecordTypeId();
            else if(rti.getDeveloperName() == Constants.RECORD_TYPE_NAME_CONTACT_US_PHYSICIAN) rtIdPhysician = rti.getRecordTypeId();
        }
        
        
        Contact c = new Contact (FirstName = 'Capital_letter', LastName = 'ConName',
                                 declined_to_provide_address__c = True, declined_to_provide_dob__c = True, 
                                 //declined_to_provide_fname__c  = True, SAFBIO 1365
                                 declined_to_provide_phone__c = True, 
                                 declined_to_provide_ssn__c  = True,
                                 RecordTypeId = rtIdPatient,
                                 MailingCountry = null, status__c = 'Active');
        
        insert c;

        
        WorkOrder wo = new WorkOrder(Subject = PREFIX_TEST_NAMES + 'wo', StartDate = Date.today(),
                                     EndDate = Date.today().addDays(1), rep_at_implant__c = UserInfo.getUserId()
                                    , AccountId = acc.Id
                                    , patient__c = c.id);
        insert wo;
        
        WorkOrderLineItem woli = new WorkOrderLineItem(Subject = PREFIX_TEST_NAMES + 'woli', WorkOrderId = wo.Id,
                                                       StartDate = Date.today());
        insert woli;
    }
	
    @isTest
    static void workOrderLineItemDeletionNonCas(){
        WorkOrder objWorkOrder = new WorkOrder();
        objWorkOrder.StartDate = Date.today();
        objWorkOrder.EndDate = Date.today();
        objWorkORder.rep_at_implant__c = UserInfo.getUserId();
        insert objWorkOrder;
        
        WorkOrderLineItem item = new WorkOrderLineItem();
        item.WorkOrderId = objWorkOrder.Id;
        item.StartDate = Date.today();
        insert item;
        
        
        Boolean bException = false;
        Integer intCountItemsBefore = [SELECT count() FROM WorkOrderLineItem];
        Test.startTest();        
        try{
            delete item;
        }catch(Exception e){
            bException = true;
        }                
        Test.stopTest();
        
        Integer intCountItemsAfter = [SELECT count() FROM WorkOrderLineItem];
        System.assertEquals(true, bException);
        System.assertEquals(intCountItemsBefore,intCountItemsAfter); 
    }
    
    /* SAFBIO-1332
     * Florian Heer <f.heer@conciscon.de>
     * 2018-06-25
     * Tests if the trigger changes the status of the related WorkOrder if the WorkOrderLineItem's
     * status is set to Transmitted.
     */ 
    @isTest
    public static void testTransmittedStatusOnWorkOrderLineItem() {
        String search = PREFIX_TEST_NAMES + '%';
        
        List<WorkOrder> wos = [SELECT Id, Subject, Status FROM WorkOrder WHERE subject LIKE :search];
        System.assertEquals(1, wos.size(), 'We should have one WorkOrder for the subject search string "' + search + '"');
        System.assertNotEquals('Transmitted', wos[0].Status);
        
        List<WorkOrderLineItem> wolis = [SELECT Id, Status FROM WorkOrderLineItem WHERE WorkOrderId = :wos[0].Id];
        System.assertEquals(1, wolis.size(), 'We should have one WorkOrderLineItem for our WorkOrder.');
        
        wolis[0].Status = 'Transmitted';
        
        Test.startTest();
        update wolis;
        Test.stopTest();
        
        wos = [SELECT Id, Subject, Status FROM WorkOrder WHERE subject LIKE :search];
        System.assertEquals('Transmitted', wos[0].Status, 'The trigger should have updated the Status of the WorkOrder');
        
    }
}