objects/Account.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>event_reason__c</fullName>
        <label>Event Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>event_reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>explanting_facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the explant</description>
        <label>Explanting Facility</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>x5500_us_account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Other_Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>explanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Explanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Explanted_Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>oos_date__c</fullName>
        <description>Gives the date of the explanation. date can only be inserted if asset has the status &quot;explanted&quot;.
Date device was taken out of service (explanted, capped, or discarded)</description>
        <label>OOS Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Patient)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/complaint__c.object
<CustomObject>
    <description>Medical Device Complaint used for reporting issues with patients that have a Biotronik device implanted.</description>
    <fields>
        <fullName>asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>linkage from complaint to asset</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to parent case, used for routing through queues and overall usage of service cloud
Complaint object is used for detailed information about the complaint.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>date_of_death__c</fullName>
        <description>3500a Question B2.  Patient&apos;s date of death.</description>
        <label>Date of Death</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>death_device_related__c</fullName>
        <description>VI Complaint form, Y/N</description>
        <label>Death was Device-related</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Device related</fullName>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>Non-Device related</fullName>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>doctors_letter_required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator that  the physician of record on the event has requested an analysis of the event from the manufacturer</description>
        <label>Doctors Letter Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Complaint_Relationships__c.object
<CustomObject>
    <fields>
        <fullName>complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>complaint__c</referenceTo>
        <relationshipLabel>Complaint Relationships</relationshipLabel>
        <relationshipName>Complaint_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please choose a Physician or Other Contact.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician, Other Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Complaint Relationships</relationshipLabel>
        <relationshipName>Complaint_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>type_of_contact__c</fullName>
        <label>Type of contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Biotronik Contact Person</fullName>
                </value>
                <value>
                    <fullName>Dr Letter Recipient</fullName>
                </value>
                <value>
                    <fullName>Event Physician</fullName>
                </value>
                <value>
                    <fullName>Explanting Physician</fullName>
                </value>
                <value>
                    <fullName>Following Physician</fullName>
                </value>
                <value>
                    <fullName>Implanting Physician</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Returned Product Sender</fullName>
                </value>
                <value>
                    <fullName>Revising Physician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint Relationships</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Complaint Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                    <isActive>false</isActive>
                    <label>Change</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                    <isActive>false</isActive>
                    <label>Retirement</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>date_of_death__c</fullName>
        <description>Person date of death</description>
        <label>Date of Death</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ssn__c</fullName>
        <description>Social Security Number (US)</description>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/event_reason.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Both</fullName>
    </customValue>
    <customValue>
        <fullName>Dislodgement</fullName>
    </customValue>
    <customValue>
        <fullName>ERI</fullName>
    </customValue>
    <customValue>
        <fullName>Erosion</fullName>
    </customValue>
    <customValue>
        <fullName>Error Message</fullName>
    </customValue>
    <customValue>
        <fullName>High shock impedance/High impedance</fullName>
    </customValue>
    <customValue>
        <fullName>High threshold</fullName>
    </customValue>
    <customValue>
        <fullName>Infection</fullName>
    </customValue>
    <customValue>
        <fullName>Landline Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Reposition</fullName>
    </customValue>
    <customValue>
        <fullName>Loss of Capture</fullName>
    </customValue>
    <customValue>
        <fullName>Low impedance</fullName>
    </customValue>
    <customValue>
        <fullName>Noise</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Oversensing</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Anatomy</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Death</fullName>
    </customValue>
    <customValue>
        <fullName>Pocket Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Power Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Safe mode/Back up Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Freeze</fullName>
    </customValue>
    <customValue>
        <fullName>Start Up</fullName>
    </customValue>
    <customValue>
        <fullName>Storm Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Telephone Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Transmit</fullName>
    </customValue>
    <customValue>
        <fullName>Undersensing</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Exposed to bodily fluids</fullName>
        <isActive>false</isActive>
        <label>Exposed to bodily fluids</label>
    </customValue>
    <customValue>
        <fullName>Diaphragmatic Stimulation</fullName>
        <isActive>false</isActive>
        <label>Diaphragmatic Stimulation</label>
    </customValue>
    <masterLabel>Event Reason</masterLabel>
</GlobalValueSet>

classes/BINCAssetDataControllerExt.cls
public class BINCAssetDataControllerExt {
    private Asset ourAsset;
    private Asset fullerAsset;
    private complaint__c newestComplaint;
    private String oosReason;
    private complaint_relationships__c drLetterRecipient;
    private complaint_relationships__c eventPhysician;
    private Case newestCase;
    
    
    
    public BINCAssetDataControllerExt (ApexPages.StandardController stdController) {
        // Can only be an Asset
        ourAsset = (Asset)stdController.getRecord();
        
        readRelatedData ();
    }
    
    private void readRelatedData () {
        List<Asset> assets = [SELECT Id
                              , patient__r.FirstName, patient__r.MiddleName, patient__r.LastName
                              , patient__r.ssn__c, patient__r.BirthDate
                              , patient__r.Status__c, patient__r.date_of_death__c
                              // , patient__r.cause_of_death__c
                              , explanting_physician__r.FirstName, explanting_physician__r.MiddleName, explanting_physician__r.LastName
                              , explanting_physician__r.MailingStreet, explanting_physician__r.MailingCity
                              , explanting_physician__r.MailingStateCode, explanting_physician__r.MailingPostalCode
                              , explanting_physician__r.Phone
                              , explanting_facility__r.Name, explanting_facility__r.Phone
                              , explanting_facility__r.ShippingStreet, explanting_facility__r.ShippingCity
                              , explanting_facility__r.ShippingStateCode, explanting_facility__r.ShippingPostalCode
                              , event_reason__c, Name, SerialNumber, InstallDate, oos_date__c
                              , Status
                             
                              FROM Asset WHERE Id = :ourAsset.Id
                             ];
        if (assets.size () > 0) {
            fullerAsset = assets[0];
        }
        
        List<complaint__c> complaints = [SELECT Id, doctors_letter_required__c
                                         , death_device_related__c, case__c 
                                         FROM complaint__c WHERE asset__c = :ourAsset.Id ORDER BY CreatedDate DESC LIMIT 1];
        if (complaints.size() > 0) {
            newestComplaint = complaints[0];
        }
        
        List<Case> cases = [SELECT Id, Contact.Name, Contact.Phone FROM Case WHERE Id = :newestComplaint.case__c];
        if (cases.size() > 0) {
            newestCase = cases[0];
        }
        
        List<complaint_relationships__c> furtherContacts =  [SELECT contact__r.FirstName, contact__r.MiddleName, contact__r.LastName
                                                             , contact__r.MailingStreet, contact__r.MailingCity, contact__r.MailingStateCode
                                                             , contact__r.Phone, contact__r.MailingPostalCode
                                                             , type_of_contact__c
                                                                FROM complaint_relationships__c 
                                                                WHERE complaint__c = :newestComplaint.Id 
                                                                AND type_of_contact__c IN ('Dr Letter Recipient')
                                            ];
        if (furtherContacts.size () > 0) {
            for (complaint_relationships__c cr : furtherContacts) {
                if (cr.type_of_contact__c == 'Dr Letter Recipient') {
                    drLetterRecipient = cr;
                }
            }
        }
        
        
        
    }
    
    public Asset getCurrentAsset () {
        return fullerAsset;
    }
    
    public String getOOSReason () {
        return fullerAsset.event_reason__c == null ? '' : fullerAsset.event_reason__c;
    }
    
    public complaint__c getNewestComplaint () {
        return newestComplaint;
    }
 
    public complaint_relationships__c getDLRecipient () {
        return drLetterRecipient;
    }
    public complaint_relationships__c getEventPhysician () {
        return eventPhysician;
    }
    public String getCurrUserName () {
        return UserInfo.getName();
    }

    public Case getNewestCase () {
        return newestCase;
    }

}