objects/Account.object
<CustomObject>
    <fields>
        <fullName>sap_no__c</fullName>
        <description>SAP SHIP-TO account number</description>
        <externalId>true</externalId>
        <label>SAP No</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>x5500_us_account</fullName>
        <active>true</active>
        <label>US Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>is_locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether an order is locked by order submission job</description>
        <label>IsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that BIOTRONIK representative was not present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_error_message__c</fullName>
        <description>Text of error message returned from SAP</description>
        <label>SAP Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>submission_attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Technical Field. Number of attempts to submit the order to SAP.</description>
        <label>Submission Attempts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>submit_to_sap__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checkbox which triggers the status change to &apos;Submitted&apos; and Submission process to SAP</description>
        <label>Submit to SAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>submitted_date__c</fullName>
        <description>Timestamp of when the user submitted the order</description>
        <label>Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>expiration_date_ubd__c</fullName>
        <description>Date after which product expires and must not be used</description>
        <label>Expiration date (UBD)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>model_no__c</fullName>
        <label>Model No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>model_no__c</fullName>
        <description>Formula-field referencing the product</description>
        <formula>Product2.sap_model_no__c</formula>
        <label>Model No</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>sap_no__c</fullName>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrderSubmissionServiceTest.cls
@IsTest
global class OrderSubmissionServiceTest {
    global Static Boolean testOrderSubmissionSchedulableRunning = false;
    @IsTest
    static void testOrderSubmissionSchedulable() {

        testOrderSubmissionSchedulableRunning = true;

        User testuser = [SELECT Id, Profile.Name FROM User WHERE Alias = 'testfunc'].get(0);
        System.assertEquals('MMS FUNC', testuser.Profile.Name);
        System.runAs(testuser) {

            Test.startTest();

            OrderSubmissionSchedulable sched = new OrderSubmissionSchedulable();
            String cronExp = '0 0 2 * * ?';
            system.schedule(OrderSubmissionSchedulable.JOB_NAME, cronExp, sched);

            // there should be one job that we just created
            List<CronTrigger> cjd = [SELECT Id FROM CronTrigger  WHERE CronJobDetail.Name = :OrderSubmissionSchedulable.JOB_NAME];
            System.assertEquals(1, cjd.size());


            Test.stopTest();

            // now as the job was running, it should have re.scheduked itself, so the ID should be different
            List<CronTrigger> cjd2 = [SELECT Id FROM CronTrigger  WHERE CronJobDetail.Name = :OrderSubmissionSchedulable.JOB_NAME];
            System.assertEquals(1, cjd2.size());
            System.assertNotEquals(cjd.get(0).Id, cjd2.get(0).Id);
        }
    }


    @IsTest
    static void testOrderSubmission() {

        User testuser = [SELECT Id, Profile.Name FROM User WHERE Alias = 'testfunc'].get(0);
        System.assertEquals('MMS FUNC', testuser.Profile.Name);
        System.runAs(testuser) {
            Order orderTest;

            Product2 product = new Product2();
            product.Name = 'Testproduct';
            insert product;

            PricebookEntry pbe = new PricebookEntry();
            pbe.Product2Id = product.Id;
            pbe.UnitPrice = 42;
            pbe.Pricebook2Id = Test.getStandardPricebookId();
            insert pbe;

            Account account = TestDataFactory.createAccount();
            account.Name = 'Testaccount';
            account.sap_no__c = '0000464464';
            account.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'x5500_us_account' LIMIT 1].Id;
            insert account;

            Contact patientContact = TestDataFactory.createPatient(false, account.Id);
            insert patientContact;

            Order order = new Order();
            order.AccountId = account.id;
            order.EffectiveDate = System.today();
            order.Status = 'Pending SAP Submission';
            order.Pricebook2Id = Test.getStandardPricebookId();
            order.no_rep_present_at_implant__c = true;
            order.patient__c = patientContact.Id;
            insert order;


            OrderItem oi = new OrderItem();
            oi.OrderId = order.Id;
            oi.Product2Id = product.Id;
            oi.PricebookEntryId = pbe.Id;
            oi.Quantity = 1;
            oi.UnitPrice = 42;
            oi.expiration_date_ubd__c = System.Today();
            oi.model_no__c = '123';
            oi.product_type__c = '123';
            oi.product_code__c = '123';
            oi.product_type__c = 'Pacemaker';
            insert oi;

            order.submit_to_sap__c = true;
            order.submission_attempts__c = 1;
            order.is_locked__c = true;
            update order;

            orderTest = [SELECT submission_attempts__c, submitted_date__c, sap_error_message__c, is_locked__c FROM Order WHERE Id = :order.Id];
            System.assertEquals(1, orderTest.submission_attempts__c);
            System.assertEquals(NULL, orderTest.sap_error_message__c);
            System.assertEquals(NULL, orderTest.submitted_date__c);
            System.assertEquals(true, orderTest.is_locked__c);


            Test.startTest();

            Test.setMock(WebServiceMock.class, new API_OrderIntegration_Mock());

            OrderSubmissionService.submitOrder(order.Id);


            Test.stopTest();


            orderTest = [SELECT submission_attempts__c, submitted_date__c, sap_error_message__c, is_locked__c FROM Order WHERE Id = :order.Id];
            System.assertEquals(1, orderTest.submission_attempts__c);
            System.assertEquals(false, orderTest.is_locked__c);
            System.assertEquals(NULL, orderTest.sap_error_message__c);
            System.assertNotEquals(NULL, orderTest.submitted_date__c);
        }
    }


    @IsTest
    static void testOrderSubmissionError() {

        User testuser = [SELECT Id, Profile.Name FROM User WHERE Alias = 'testfunc'].get(0);
        System.assertEquals('MMS FUNC', testuser.Profile.Name);
        System.runAs(testuser) {
            Order orderTest;

            Product2 product = new Product2();
            product.Name = 'Testproduct';
            insert product;

            PricebookEntry pbe = new PricebookEntry();
            pbe.Product2Id = product.Id;
            pbe.UnitPrice = 42;
            pbe.Pricebook2Id = Test.getStandardPricebookId();
            insert pbe;

            Account account = TestDataFactory.createAccount();
            account.Name = 'Testaccount';
            account.sap_no__c = '0000464464';
            account.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'x5500_us_account' LIMIT 1].Id;
            insert account;

            Contact patientContact = TestDataFactory.createPatient(false, account.Id);
            insert patientContact;

            Order order = new Order();
            order.AccountId = account.id;
            order.EffectiveDate = System.today();
            order.Status = 'Pending SAP Submission';
            order.Pricebook2Id = Test.getStandardPricebookId();
            order.no_rep_present_at_implant__c = true;
            order.patient__c = patientContact.Id;
            insert order;


            OrderItem oi = new OrderItem();
            oi.OrderId = order.Id;
            oi.Product2Id = product.Id;
            oi.PricebookEntryId = pbe.Id;
            oi.Quantity = 1;
            oi.UnitPrice = 42;
            oi.expiration_date_ubd__c = System.Today();
            oi.model_no__c = '123';
            oi.product_type__c = '123';
            oi.product_code__c = '123';
            oi.product_type__c = 'Pacemaker';
            insert oi;

            order.submit_to_sap__c = true;
            order.submission_attempts__c = 1;
            order.is_locked__c = true;
            update order;

            orderTest = [SELECT submission_attempts__c, submitted_date__c, sap_error_message__c, is_locked__c FROM Order WHERE Id = :order.Id];
            System.assertEquals(1, orderTest.submission_attempts__c);
            System.assertEquals(NULL, orderTest.sap_error_message__c);
            System.assertEquals(NULL, orderTest.submitted_date__c);
            System.assertEquals(true, orderTest.is_locked__c);


            Test.startTest();

            Test.setMock(WebServiceMock.class, new API_OrderIntegrationNegative_Mock());

            OrderSubmissionService.submitOrder(order.Id);


            Test.stopTest();


            orderTest = [SELECT submission_attempts__c, submitted_date__c, sap_error_message__c, is_locked__c FROM Order WHERE Id = :order.Id];
            System.assertEquals(1, orderTest.submission_attempts__c);
            System.assertEquals(false, orderTest.is_locked__c);
            System.assertEquals('Mock_Error', orderTest.sap_error_message__c);
            System.assertEquals(NULL, orderTest.submitted_date__c);
        }
    }

    @testSetup
    public static void setupOrderSubmissionUser () {
        User u = TestDataFactory.createUser(Utility.getProfileId(Constants.PROFILE_Name_System_MMS_FUNC));
        u.FirstName = 'Test';
        u.LastName = 'Test';
        u.Username = 'test_mms_func@example.com';
        u.Email = 'test_mms_func@example.com';
        u.Alias = 'testfunc';
        u.CommunityNickname = 'test_mms_func@example.com';
        u.TimeZoneSidKey = 'Europe/Berlin';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey ='en_US';
        u.Country = 'United States';
        insert u;
    }
}