objects/Account.object
<CustomObject>
    <fields>
        <fullName>crm_pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>contains Bradycardia, Tachycardia, Diagnostic</description>
        <label>CRM Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>CRM_Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cvi_pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CVI Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Accounts (CVI Pricebook)</relationshipLabel>
        <relationshipName>CVI_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pvi_pricebook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PVI Pricebook</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Accounts (PVI Pricebook)</relationshipLabel>
        <relationshipName>PVI_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_no__c</fullName>
        <description>SAP SHIP-TO account number</description>
        <externalId>true</externalId>
        <label>SAP No</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>external_id__c</fullName>
        <description>Company Code_Account_Division</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>last_update__c</fullName>
        <label>Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>dummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dummy Pricebook Entry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>external_id__c</fullName>
        <description>Account_Division_Materialnummer</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>external_id__c</fullName>
        <description>SAP Materialnummer</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>manufacturer__c</fullName>
        <label>Manufacturer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BIOTRONIK</fullName>
                    <default>true</default>
                    <label>BIOTRONIK</label>
                </value>
                <value>
                    <fullName>5500_APC</fullName>
                    <label>AMERICAN PACEMAKER CORP.</label>
                </value>
                <value>
                    <fullName>5500_ACO</fullName>
                    <label>ANGEION CORP.</label>
                </value>
                <value>
                    <fullName>5500_BME</fullName>
                    <label>BIOMEC</label>
                </value>
                <value>
                    <fullName>5500_BSX</fullName>
                    <label>BOSTON SCIENTIFIC</label>
                </value>
                <value>
                    <fullName>5500_CAC</fullName>
                    <label>CARDIAC CONTROL</label>
                </value>
                <value>
                    <fullName>5500_CAI</fullName>
                    <label>CARDIAC IMPULSE</label>
                </value>
                <value>
                    <fullName>5500_CAP</fullName>
                    <label>CARDIAC PACEMAKER</label>
                </value>
                <value>
                    <fullName>5500_CPR</fullName>
                    <label>CARDIAC PRODUCTS</label>
                </value>
                <value>
                    <fullName>5500_CPM</fullName>
                    <label>CARDIO-PACE MEDICAL</label>
                </value>
                <value>
                    <fullName>5500_CHR</fullName>
                    <label>CHRONIC</label>
                </value>
                <value>
                    <fullName>5500_COK</fullName>
                    <label>COOK</label>
                </value>
                <value>
                    <fullName>5500_COI</fullName>
                    <label>CORATOMIC INC.</label>
                </value>
                <value>
                    <fullName>5500_COR</fullName>
                    <label>CORDIS</label>
                </value>
                <value>
                    <fullName>5500_DAI</fullName>
                    <label>DAIG CORP.</label>
                </value>
                <value>
                    <fullName>5500_ES</fullName>
                    <label>EA</label>
                </value>
                <value>
                    <fullName>5500_ELM</fullName>
                    <label>ELA MEDICAL</label>
                </value>
                <value>
                    <fullName>5500_ELS</fullName>
                    <label>ELS</label>
                </value>
                <value>
                    <fullName>5500_ENP</fullName>
                    <label>ENPATH MEDICAL INC.</label>
                </value>
                <value>
                    <fullName>5500_GRE</fullName>
                    <label>GREATBATCH</label>
                </value>
                <value>
                    <fullName>5500_GDT</fullName>
                    <label>GUIDANT</label>
                </value>
                <value>
                    <fullName>5500_IMP</fullName>
                    <label>IMPLANTRONIK</label>
                </value>
                <value>
                    <fullName>5500_INA</fullName>
                    <label>INHO A</label>
                </value>
                <value>
                    <fullName>5500_INH</fullName>
                    <label>INHOUEE</label>
                </value>
                <value>
                    <fullName>5500_INN</fullName>
                    <label>INHOUSEN</label>
                </value>
                <value>
                    <fullName>5500_INO</fullName>
                    <label>INNOMEDICA LTD.</label>
                </value>
                <value>
                    <fullName>5500_INT</fullName>
                    <label>INTERMEDICS INC.</label>
                </value>
                <value>
                    <fullName>5500_MDO</fullName>
                    <label>MEDICO</label>
                </value>
                <value>
                    <fullName>5500_MDT</fullName>
                    <label>MEDTRONIC, INC</label>
                </value>
                <value>
                    <fullName>5500_MYO</fullName>
                    <label>MYOPORE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_model_no__c</fullName>
        <externalId>true</externalId>
        <label>SAP Model No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/Batch_PricebookEntryDummies_Test.cls
@isTest
public class Batch_PricebookEntryDummies_Test {
    public static final Integer NUM_PRODUCTS = 50;
    public static final Integer NUM_CRM_ENTRIES = 30;
    public static final Integer OFFSET_CRM = 0;
    public static final Integer NUM_CVI_ENTRIES = 30;
    public static final Integer OFFSET_CVI = 10;
    public static final Integer NUM_PVI_ENTRIES = 30;
    public static final Integer OFFSET_PVI = 20;
    // Maximum Batch size is 60 anyways
    public static final Integer NUM_ACCOUNTS = 150;


    /**
     * Creating test data
     * 
     * Need (many!):
     * - Product2
     * - Account
     * - (SAP-Standard) Pricebook2
     * - Pricebook2
     * - PricebookEntry
     * 
     */
    @TestSetup
    public static void setupEnvironment() {
        List<Product2> prod2Insert = new List<Product2>();
        Product2 templateProduct = TestDataFactory.createProduct(Constants.RECORD_TYPE_NAME_PRODUCT);
        templateProduct.manufacturer__c = 'BIOTRONIK';
        templateProduct.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_CRT_D;
        templateProduct.IsActive = true;
        Product2 cloneProd;
        for (Integer i = 0; i < NUM_PRODUCTS; i++) {
            cloneProd = templateProduct.clone();
            cloneProd.Name = 'TestProduct_' + i;
            cloneProd.sap_model_no__c = '' + i;
            prod2Insert.add(cloneProd);
        }
        insert prod2Insert;

        List<PricebookEntry> pbes2Insert = new List<PricebookEntry>();
        Id pbId = Test.getStandardPricebookId();
        for (Product2 currProd : prod2Insert) {
            pbes2Insert.add (
                    new PricebookEntry (
                            Product2Id = currProd.Id,
                            Pricebook2Id = pbId,
                            isActive = True,
                            CurrencyIsoCode = 'USD',
                            UnitPrice = 0,
                            external_id__c = '5500__Test_' + currProd.Id
                    )
            );
        }

        insert pbes2Insert;
        pbes2Insert = new List<PricebookEntry>();

        List<Pricebook2> pbs = new List<Pricebook2>();

        Pricebook2 crmPB = new Pricebook2(
                isActive = true,
                currency__c = 'USD',
                Name = '5500' + Constants.STANDARD_PRICEBOOKS_NAMING_SUBSTRING + 'CRM',
                last_update__c = DateTime.now()
        );
        pbs.add(crmPB);

        Pricebook2 cviPB = new Pricebook2(
                isActive = true,
                currency__c = 'USD',
                Name = '5500' + Constants.STANDARD_PRICEBOOKS_NAMING_SUBSTRING + 'CVI',
                last_update__c = DateTime.now()
        );
        pbs.add(cviPB);

        Pricebook2 pviPB = new Pricebook2(
                isActive = true,
                currency__c = 'USD',
                Name = '5500' + Constants.STANDARD_PRICEBOOKS_NAMING_SUBSTRING + 'PVI',
                last_update__c = DateTime.now()
        );
        pbs.add(pviPB);

        insert pbs;

        pbId = crmPB.Id;
        Integer counter = 0;
        for (Product2 currProd : prod2Insert) {
            if (counter >= OFFSET_CRM) {
                pbes2Insert.add (
                        new PricebookEntry (
                                Product2Id = currProd.Id,
                                Pricebook2Id = pbId,
                                isActive = True,
                                sap_company_code__c = '5500',
                                CurrencyIsoCode = 'USD',
                                UnitPrice = 0,
                                UseStandardPrice = true
                        )
                );
            }
            counter++;
            if (counter >= (OFFSET_CRM + NUM_CRM_ENTRIES)) break;
        }

        pbId = cviPB.Id;
        counter = 0;
        for (Product2 currProd : prod2Insert) {
            if (counter >= OFFSET_CVI) {
                pbes2Insert.add (
                        new PricebookEntry (
                                Product2Id = currProd.Id,
                                Pricebook2Id = pbId,
                                isActive = True,
                                sap_company_code__c = '5500',
                                CurrencyIsoCode = 'USD',
                                UnitPrice = 0,
                                UseStandardPrice = true
                        )
                );
            }
            counter++;
            if (counter >= (OFFSET_CVI + NUM_CVI_ENTRIES)) break;
        }

        pbId = pviPB.Id;
        counter = 0;
        for (Product2 currProd : prod2Insert) {
            if (counter >= OFFSET_PVI) {
                pbes2Insert.add (
                        new PricebookEntry (
                                Product2Id = currProd.Id,
                                Pricebook2Id = pbId,
                                isActive = True,
                                sap_company_code__c = '5500',
                                CurrencyIsoCode = 'USD',
                                UnitPrice = 0,
                                UseStandardPrice = true
                        )
                );
            }
            counter++;
            if (counter >= (OFFSET_PVI + NUM_PVI_ENTRIES)) break;
        }

        insert pbes2Insert;

        List<Pricebook2> pricebook2s = new List<Pricebook2>();

        Pricebook2 crm = new Pricebook2(
                isActive = true,
                currency__c = 'USD',
                Name = '5500_CRM'
        );
        pricebook2s.add(crm);

        Pricebook2 cvi = new Pricebook2(
                isActive = true,
                currency__c = 'USD',
                Name = '5500_CVI'
        );
        pricebook2s.add(cvi);

        Pricebook2 pvi = new Pricebook2(
                IsActive = true,
                currency__c = 'USD',
                Name = '5500_PVI'
        );
        pricebook2s.add(pvi);

        insert pricebook2s;

        List<Account> accs2Insert = new List<Account>();
        Account templateAccount = TestDataFactory.createAccount();
        templateAccount.crm_pricebook__c = crm.Id;
        templateAccount.cvi_pricebook__c = cvi.Id;
        templateAccount.pvi_pricebook__c = pvi.Id;

        for (Integer i = 0; i < NUM_ACCOUNTS; i++) {
            Account aClone = templateAccount.clone();
            aClone.Name = 'TestAccount_' + i;
            aClone.sap_no__c = 'sap_no_' + i;
            accs2Insert.add(aClone);

            if (accs2Insert.size () > 9000) {
                insert accs2Insert;
                accs2Insert = new List<Account>();
            }

        }

        insert accs2Insert;

    }

    /**
     * Testing the synching for products
     */
    @IsTest
    public static void testProductTypeSyncing() {
        Test.startTest();
        Batch_PricebookEntryDummies pbeDummies = new Batch_PricebookEntryDummies();
        Database.executeBatch(pbeDummies);
        Test.stopTest();

        String accName = 'TestAccount_15';
        Account acc = [SELECT Id, crm_pricebook__c, cvi_pricebook__c, pvi_pricebook__c FROM Account WHERE Name = :accName];
        Integer entryCountCRM = [SELECT COUNT() FROM PricebookEntry WHERE Pricebook2Id = :acc.crm_pricebook__c AND dummy__c = TRUE];
        System.assertEquals(NUM_CRM_ENTRIES, entryCountCRM);

        accName = 'TestAccount_35';
        acc = [SELECT Id, crm_pricebook__c, cvi_pricebook__c, pvi_pricebook__c FROM Account WHERE Name = :accName];
        Integer entryCountCVI = [SELECT COUNT() FROM PricebookEntry WHERE Pricebook2Id = :acc.cvi_pricebook__c AND dummy__c = TRUE];
        System.assertEquals(NUM_CVI_ENTRIES, entryCountCVI);

        accName = 'TestAccount_45';
        acc = [SELECT Id, crm_pricebook__c, cvi_pricebook__c, pvi_pricebook__c FROM Account WHERE Name = :accName];
        Integer entryCountPVI = [SELECT COUNT() FROM PricebookEntry WHERE Pricebook2Id = :acc.pvi_pricebook__c AND dummy__c = TRUE];
        System.assertEquals(NUM_PVI_ENTRIES, entryCountPVI);

    }

    /**
     * Testing the error mail on syncing fail
     */
    @IsTest
    public static void testProductTypeSyncingCheckSchedulable() {

        Batch_PricebookEntryDummies pbeDummies = new Batch_PricebookEntryDummies();
        Id pbeDummiesBatchJob;

        Test.startTest();
        pbeDummiesBatchJob = Database.executeBatch(pbeDummies);

        Test.stopTest();

        //Cron trigger is allrady removed
        List<CronTrigger> cronTriggers = [SELECT Id, CronJobDetail.Id, CronJobDetail.Name, CronJobDetail.JobType FROM CronTrigger WHERE CronJobDetail.Name LIKE '%Check Job%'];
        System.assertEquals(0,cronTriggers.size());

        //but run flag should have been set
        System.assertEquals(PriceBookDummiesCheckBatchSchedule.state, 'run');

    }

}