objects/Account.object
<CustomObject>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_no__c</fullName>
        <description>SAP SHIP-TO account number</description>
        <externalId>true</externalId>
        <label>SAP No</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                    <isActive>false</isActive>
                    <label>Change</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                    <isActive>false</isActive>
                    <label>Retirement</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>following_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the physician contact</description>
        <label>Following Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Patients Following</relationshipLabel>
        <relationshipName>ContactFollowingPhysician</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that BIOTRONIK representative was not present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Referring Physician)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_for_credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep for Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>study_product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox field. If checked, a check sign indicates a product as a study product in the list view</description>
        <label>Study Product</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductConsumed.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the patient record</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Products Consumed (Patient)</relationshipLabel>
        <relationshipName>Products_Consumed1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>The status of the device.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implanted</fullName>
                </value>
                <value>
                    <fullName>Explanted</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Partially Capped</fullName>
                </value>
                <value>
                    <fullName>Patient Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Implantable Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>following_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>following physician CONTACT record assigned by SFDC</description>
        <label>Following Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Following Physician)</relationshipLabel>
        <relationshipName>Implants_Procedures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that no BIOTRONIK representative was present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <inlineHelpText>Physician who referred the patient</inlineHelpText>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Referring Physician)</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <inlineHelpText>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</inlineHelpText>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_for_credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for sales rep who will receive credit for the sale.</description>
        <inlineHelpText>Identifier for sales rep who will receive credit for the sale.</inlineHelpText>
        <label>Rep for Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WorkOrderHandlerTest.cls
//TestClass for workOrder Handler
//Created by emma
//created date 25.07.2018
@isTest
private class WorkOrderHandlerTest {

    @isTest
    static void testCheckAndPerformWorkOrderCancellation(){
        List<ProductConsumed> lstPc = new List<ProductConsumed>();
        List<WorkOrderLineItem> lstwoli = new List<WorkOrderLineItem>();
        
        Account objAccount = new Account(Name = 'Test Account',
                                         sap_company_code__c = '5500',
                                         sap_no__c = '35627', 
                                         status__c = 'Active');
        insert objAccount;
		Contact physician =  TestDataFactory.createPhysician(false);
    	Contact patient = TestDataFactory.createPatient(true, objAccount.id);
        Product2 prod = new Product2(IsActive = true,
                                     Name = 'ABC product',
                                     study_product__c = true
                                     );
        insert prod;
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, 
            											  UnitPrice = 10000, 
                                                          IsActive = true,
                                                          Product2Id= prod.Id);
        insert standardPrice;        
		Id orderRtId =  Utility.getRecordTypeId(Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
        Order objOrd = new Order (AccountId = objAccount.Id,
                                   Status = Constants.PICKLIST_VALUE_ORDER_STATUS_NOT_SUBMITTED,
                                   EffectiveDate = System.today(),
                                   Pricebook2Id = pricebookId,
                                   referring_physician__c = physician.Id,
                                   patient__c = patient.Id,
                                   RecordTypeId = orderRtId,
                                   no_rep_present_at_implant__c  = true,
                                   rep_for_credit__c= UserInfo.getUserId());
        insert objOrd;

         WorkOrder objWorkOrder = new WorkOrder(Status = Constants.PICKLIST_VALUE_ORDER_STATUS_NOT_SUBMITTED,
             								   StartDate = Date.today(),
                                               EndDate = Date.today() + 20,
                                               Pricebook2Id = pricebookId,
                                               rep_at_implant__c = UserInfo.getUserId(),
                                               patient__c =patient.Id,
                                               referring_physician__c= physician.Id,
                                               following_physician__c=physician.Id,
                                               AccountId = objAccount.Id
                                               );
        insert objWorkOrder;
        
        System.debug('objWorkOöllr'+objWorkOrder);
        
        ProductConsumed item = new ProductConsumed(WorkOrderId = objWorkOrder.Id,
                                                   PricebookEntryId = standardPrice.Id,
                                                   QuantityConsumed = 2);
        
        ProductConsumed item_2 = new ProductConsumed(WorkOrderId = objWorkOrder.Id,
                                                   PricebookEntryId = standardPrice.Id,
                                                   QuantityConsumed = 2);
        lstPc.add(item);
        lstPc.add(item_2);
        insert lstPc; 

        WorkOrderLineItem objWoli = new WorkOrderLineItem(status = Constants.PICKLIST_STATUS_VALUE_WORK_ORDER_LINE_ITEM_NOT_SUBMITTED,
                                                          WorkOrderId = objWorkOrder.Id,
                                                          OrderId = objOrd.Id);
        
        WorkOrderLineItem objWoli_2 = new WorkOrderLineItem(status = Constants.PICKLIST_STATUS_VALUE_WORK_ORDER_LINE_ITEM_NOT_SUBMITTED,
                                                          WorkOrderId = objWorkOrder.Id,
                                                          OrderId = objOrd.Id);
        lstwoli.add(objWoli);
        lstwoli.add(objWoli_2);
        insert lstwoli;
        
        Test.startTest();
            System.debug('objWorkOrder'+objWorkOrder);
        	objWorkOrder.Status = WorkOrderHandler.CANCELED;
            update objWorkOrder;
        Test.stopTest();
        
            WorkOrder wolst = [select Id,referring_physician__c, patient__c, implanting_physician__c, following_physician__c
                               		FROM  WorkOrder
                                   	WHERE Id =:objWorkOrder.Id];
        
           System.assertEquals(NULL, wolst.referring_physician__c);
           System.assertEquals(NULL, wolst.patient__c);
        
        
           WorkOrderLineItem woli =[Select Id, Status, WorkOrderId FROM WorkOrderLineItem where WorkOrderId = :objWorkOrder.Id LIMIT 1 ];
          
           System.assertEquals(Constants.PICKLIST_STATUS_VALUE_WORK_ORDER_LINE_ITEM_CANCELED, woli.Status);
           
           List<ProductConsumed> pc = [SELECT Id, WorkOrderId From ProductConsumed WHERE WorkOrderId =: objWorkOrder.Id ];
           System.assertEquals(0, pc.size());
           System.debug('pc.size()' + pc.size());
        
    } 
}