objects/Account.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <description>Indicator of whether account is active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>UDI__c</fullName>
        <description>Unique Device Identification made up of serial/batch number, UBD, and EAN. Required by FDA</description>
        <label>UDI</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>date_asset_status_changed__c</fullName>
        <description>Used in OOS validation rules.  Updated via process builder when Asset &apos;Status&apos;  is changed.</description>
        <label>Date Asset Status Changed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>expiration_date_ubd__c</fullName>
        <description>use by date. If the MDRF user selects (by scanning or manual entry) Asset that is past its Use by Date (UBD), the system will send a warning to the screen which the user must acknowledge.  It does not prevent the MDRF entry process from continuing with UBD asset (the product may already have been implanted at the time the MDRF is being completed).</description>
        <label>Expiration date (UBD)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets (Implanting Physician)</relationshipLabel>
        <relationshipName>Assets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>imported_as_oos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imported as OOS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>oos_date__c</fullName>
        <description>Gives the date of the explanation. date can only be inserted if asset has the status &quot;explanted&quot;.
Date device was taken out of service (explanted, capped, or discarded)</description>
        <label>OOS Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linkage to the  Order record</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>part_of_donation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When MDRF is marked as donation the related Assets are flagged as a part of donation</description>
        <label>Part of Donation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                    <isActive>false</isActive>
                    <label>Change</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                    <isActive>false</isActive>
                    <label>Retirement</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>donation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Donation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>validation_reason__c</fullName>
        <description>Auto-filled comment field to create task description lines for CAS</description>
        <label>Validation Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Price Discrepancy Reason = Bulk swap</fullName>
                </value>
                <value>
                    <fullName>Implanting facility in Puerto Rico**</fullName>
                </value>
                <value>
                    <fullName>Alphanumeric PO Number**</fullName>
                </value>
                <value>
                    <fullName>Donation**</fullName>
                </value>
                <value>
                    <fullName>Bulk Product with Price &gt; $0</fullName>
                </value>
                <value>
                    <fullName>Part of System &amp; Price &gt; $0</fullName>
                </value>
                <value>
                    <fullName>$0 Product outside System</fullName>
                </value>
                <value>
                    <fullName>Unverified physician</fullName>
                </value>
                <value>
                    <fullName>Device with no leads</fullName>
                </value>
                <value>
                    <fullName>Patient Shipping Address is P.O. Box</fullName>
                </value>
                <value>
                    <fullName>Unverified Patient Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Lead with no Device</fullName>
                </value>
                <value>
                    <fullName>Device with only one Lead</fullName>
                </value>
                <value>
                    <fullName>More than 1 Device on MDRF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>expiration_date_ubd__c</fullName>
        <description>Date after which product expires and must not be used</description>
        <label>Expiration date (UBD)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>part_of_donation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When MDRF is marked as donation the related Assets are flagged as a part of donation</description>
        <label>Part of Donation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>serial_number__c</fullName>
        <description>Unique numeric identifier of the specific device</description>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Implanted</fullName>
                </value>
                <value>
                    <fullName>Explanted</fullName>
                </value>
                <value>
                    <fullName>Discarded</fullName>
                </value>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Partially Capped</fullName>
                </value>
                <value>
                    <fullName>Patient Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Implantable Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>udi__c</fullName>
        <description>Unique Device Identification made up of serial/batch number, UBD, and EAN. Required by FDA</description>
        <label>UDI</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implant Procedures</relationshipLabel>
        <relationshipName>Implants_Procedures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrderHandlerTest.cls
/**
*
* Test class for Order Trigger and the OrderHandler
*
* @author			snpa
* @modifiedBy		ilu_pkas
* @created			2018-04-10
* @modified		2018-08-30
* @systemLayer		Test
*
*/
@isTest
private class OrderHandlerTest {
    static Account objAccount;
    static Order objOrder;
    static User testUser;

    private static void init() {
        testUser = TestDataFactory.createUser(UserInfo.getProfileId());
        testUser.UserRoleId = [SELECT Id FROM UserRole WHERE DeveloperName = : Constants.USER_ROLE_NAME_SO LIMIT 1].Id;
        System.runAs(testUser){
            objAccount = TestDataFactory.createAccount();
            insert objAccount;

            Id orderRtId =  Utility.getRecordTypeId (Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
            objOrder = TestDataFactory.createOrder(objAccount.Id);
            objOrder.Status = Constants.PICKLIST_VALUE_STATUS_NOT_SUBMITTED;
            objOrder.RecordTypeId = orderRtId;
            objOrder.PoNumber = '1234';
            objOrder.validation_reason__c = Constants.PICKLIST_VALIDATION_REASON_NONE;
            insert objOrder;
        }
    }

    /**
    * Method checks if donations, without any additional error, are processed
    * 	to the right queue and have the correct validation reason
    */
    @isTest
    static void testForDonation() {
        init();
        
        System.runAs(testUser){
            List<OrderItem> lstItems = new List<OrderItem>();
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderItem.part_of_system_price__c = false;
            objOrderItem.UnitPrice = 0;
            lstItems.add(objOrderItem);

            OrderItem objLead = TestDataFactory.createOrderItem(objOrder.Id);
            objLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead.UnitPrice = 1;
            lstItems.add(objLead);

            OrderItem objLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead2.UnitPrice = 1;
            lstItems.add(objLead2);

            insert lstItems;
            
            Test.startTest();
            objOrder.donation__c = true;
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        objOrder = [SELECT Id, OwnerId, validation_reason__c FROM Order WHERE Id = :objOrder.Id LIMIT 1];
        System.assert(objOrder.validation_reason__c.contains('Donation**'), 'Order validation reason: '+objOrder.validation_reason__c);
    }

    /**
    * Method checks that if a order gets flagged as a donation following steps are done:
    * 	-	marking the order items as donation
    *  -	setting the order items unit price to 0
    */
    @isTest
    static void changedToDonation() {
        init();

        System.runAs(testUser){
            List<OrderItem> lstItems = new List<OrderItem>();
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderItem.part_of_system_price__c = false;
            objOrderItem.UnitPrice = 0;
            lstItems.add(objOrderItem);

            OrderItem objLead = TestDataFactory.createOrderItem(objOrder.Id);
            objLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead.UnitPrice = 1;
            lstItems.add(objLead);

            OrderItem objLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead2.UnitPrice = 1;
            lstItems.add(objLead2);

            insert lstItems;

            Test.startTest();
            objOrder.donation__c = true;
            update objOrder;
            Test.stopTest();
        }

        List<OrderItem> lstDonationItems = [SELECT Id, UnitPrice, ListPrice, part_of_donation__c FROM OrderItem WHERE OrderId = :objOrder.Id];
        System.assertNotEquals(0, lstDonationItems.size());
        for(OrderItem item :lstDonationItems){
            System.assertEquals(0, item.UnitPrice, 'Unit Price for the Donation was not set to zero');
            System.assertEquals(true, item.part_of_donation__c, 'The part of donation flag should be set');
        }
    }

    /**
     * Method checks that if a order gets the donation flag removed following steps are done:
     * 	-	removing the donation flag from the order items
     *  -	setting the order items unit price to the products list price
     */
    @isTest
    static void changedFromDonation() {
        init();

        System.runAs(testUser){
            objOrder.donation__c = true;
            update objOrder;

            List<OrderItem> lstItems = new List<OrderItem>();
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_PACEMAKER;
            objOrderItem.part_of_system_price__c = false;
            objOrderItem.UnitPrice = 0;
            lstItems.add(objOrderItem);

            OrderItem objLead = TestDataFactory.createOrderItem(objOrder.Id);
            objLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead.UnitPrice = 2;
            lstItems.add(objLead);

            OrderItem objLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead2.UnitPrice = 2;
            lstItems.add(objLead2);

            insert lstItems;

            Test.startTest();
            objOrder.donation__c = false;
            update objOrder;
            Test.stopTest();
        }

        List<OrderItem> lstDonationItems = [SELECT Id, UnitPrice, part_of_donation__c, ListPrice FROM OrderItem WHERE OrderId = :objOrder.Id];
        for(OrderItem item :lstDonationItems){
            System.assertEquals(item.ListPrice, item.UnitPrice, 'Unit Price for the Donation was not set to the list price');
            System.assertEquals(false, item.part_of_donation__c, 'The part of donation flag should be false');
        }
    }

    //test check required value of a an orderItem when changing when submitting the order
    @isTest
    static void testCheckProductRequiredValue(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            Product2 prod = new Product2(Name = 'Lead');
            insert prod;
            Id pricebookId = Test.getStandardPricebookId();
            PricebookEntry standardPrice = new PricebookEntry(
                    Pricebook2Id = pricebookId, Product2Id = prod.Id,
                    UnitPrice = 10000, IsActive = true);
            insert standardPrice;

            OrderItem objOrderItem = new OrderItem(
                    OrderId = objOrder.Id,
                    Quantity = 1,
                    PricebookEntryId = standardPrice.Id,
                    status__c = 'Implanted',
                    expiration_date_ubd__c = Date.today().addDays(20),
                    udi__c='6254879552412397745',
                    serial_number__c = NULL
            );
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderItem.UnitPrice = 2;

            Test.startTest();
            lstOrderItems.add(objOrderItem);
            insert lstOrderItems;

            try{
                objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
                update objOrder;
            }catch(Exception e){
                System.assertEquals(e.getMessage().contains(System.Label.ADD_PRODUCT_REQUIRED_VALUES), True);
                System.assertEquals(true, e.getMessage().contains(System.Label.ADD_PRODUCT_REQUIRED_VALUES), 'Expected Error1');
            }
        }
    }

    @isTest
    static void testCheckProductRequiredValuesWhenSystemDevice(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            Product2 prod = new Product2(Name = 'System Device');
            insert prod;
            Id pricebookId = Test.getStandardPricebookId();
            PricebookEntry standardPrice = new PricebookEntry(
                    Pricebook2Id = pricebookId, Product2Id = prod.Id,
                    UnitPrice = 10000, IsActive = true);
            insert standardPrice;

            OrderItem objOrderItem = new OrderItem(
                    OrderId = objOrder.Id,
                    Quantity = 1,
                    PricebookEntryId = standardPrice.Id,
                    status__c = 'Implanted',
                    expiration_date_ubd__c = Date.today().addDays(20),
                    udi__c='6254879552412397745',
                    serial_number__c = NULL
            );
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderItem.UnitPrice = 2;

            Test.startTest();
            lstOrderItems.add(objOrderItem);
            insert lstOrderItems;

            try {
                objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
                update objOrder;
            } catch(Exception e) {
                System.assertEquals(true, e.getMessage().contains(System.Label.ADD_PRODUCT_REQUIRED_VALUES), 'Expected Error3');
            }
            Test.stopTest();
        }
    }

    @isTest
    static void validateOosAssets(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderDevice.part_of_system_price__c = false;
            objOrderDevice.UnitPrice = 2;
            lstOrderItems.add(objOrderDevice);

            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            insert lstOrderItems;

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            insert prod;

            WorkOrder workorder = TestDataFactory.createWorkOrder();
            workorder.order__c = objOrder.Id;
            workorder.patient__c = objOrder.patient__c;
            insert workorder;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId, prod.Id);
            objAsset.patient__c = objOrder.patient__c;
            objAsset.Status = Constants.IMPLANT_STATUS_EXPLANTED;
            objAsset.oos_date__c = null;
            objAsset.imported_as_oos__c = false;
            objAsset.date_asset_status_changed__c = Date.today();
            objAsset.RecordTypeId = Utility.getRecordTypeId(Asset.SObjectType, Constants.RECORD_TYPE_NAME_ASSET_US_BIOTRONIK);
            insert objAsset;

            boolean bException = false;
            try{
                Test.startTest();
                objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
                update objOrder;
                Test.stopTest();
            }catch(System.DmlException ex){
                System.debug('### msg '+ex.getMessage());
                if(ex.getMessage().contains(System.Label.ERR_OOS_VALIDATION))
                    bException = true;
            }

            Order objOrder = [SELECT Id, OwnerId, validation_reason__c, Status FROM Order WHERE Id = :objOrder.Id];
            System.assertEquals(true, bException, 'Expected Exception');
            System.assertEquals(Constants.PICKLIST_VALUE_STATUS_NOT_SUBMITTED, objOrder.Status);
        }
    }

    @isTest
    static void testCheckImplantingPhysicianInfoIfNoPhone(){
        init();

        System.runAs(testUser){
            Contact physician =  TestDataFactory.createPhysician(false);
            physician.phone = '';
            physician.AccountId = objAccount.Id;
            insert physician;

            Contact objCnt = TestDataFactory.createPatient(true);

            objOrder.implanting_physician__c = physician.Id;
            update objOrder;

            Test.startTest();
            try{
                objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
                update objOrder;
            }catch(Exception e){
                System.debug('### '+e.getMessage());
                System.assertEquals(true, e.getMessage().contains(System.Label.ADD_IMPLANTING_PHYSICIAN_PHONE_NUMBER), 'Expected Error2');
            }
            Test.stopTest();
        }
    }

    @isTest
    static void testCheckFollowingPhysicianInfoInfoPhone(){
        init();

        System.runAs(testUser){
            Contact physician =  TestDataFactory.createPhysician(false);
            physician.AccountId = objAccount.Id;
            insert physician;

            Contact followingphysician =  TestDataFactory.createPhysician(false);
            followingphysician.AccountId = objAccount.Id;
            followingphysician.Phone = '';
            followingphysician.LastName = followingphysician.LastName + 'TestName';
            insert followingphysician;

            Contact objCnt = TestDataFactory.createPatient(false);
            objCnt.following_physician__c = followingphysician.Id;
            insert objCnt;

            objOrder.implanting_physician__c = physician.Id;
            objOrder.patient__c = objCnt.Id;
            update objOrder;
            Test.startTest();
            try{

                objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
                update objOrder;
            }catch(Exception e){
                System.assertEquals(true, e.getMessage().contains(System.Label.ADD_FOLLOWING_PHYSICIAN_PHONE));
            }
            Test.stopTest();
        }
    }
}