objects/Analysis_Report__c.object
<CustomObject>
    <description>CAN Analysis Result
The manufacturer will send the analysis results about complaints back to the MDR team. A record of this object is created automatically everytime, when feedback is pulled out of CAN.
FDA Analysis Result
Everytime the eMDR tool sends back feedback from the FDA a new record is created.</description>
    <fields>
        <fullName>complaint__c</fullName>
        <description>Linkage to initial complaint</description>
        <label>Complaint</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>complaint__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CardioMessenger Report, Out Of Service Report, Programmer Report, Revision Report, OUS/OEM Report, Returned Product Report, CardioMessenger Report, General Report, Out Of Service Report, Programmer Report, Revision Report</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>complaint__c</referenceTo>
        <relationshipLabel>Analysis Reports</relationshipLabel>
        <relationshipName>Analysis_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>date_sent_to_fda__c</fullName>
        <description>Date report sent to FDA.</description>
        <label>Date sent to FDA</label>
        <type>DateTime</type>
    </fields>
    <label>Analysis Result</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Analysis Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analysis Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/complaint__c.object
<CustomObject>
    <description>Medical Device Complaint used for reporting issues with patients that have a Biotronik device implanted.</description>
    <fields>
        <fullName>asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>linkage from complaint to asset</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FDA3500FormExtensionTest.cls
/**
 * Test class for FDA3500FormExtension
 * 
 * @author            SNPA
 * @created           2018-10-26
 * @systemLayer       Test Class 
 *  
 */
@isTest
private class FDA3500FormExtensionTest {

    private static Complaint__c objComplaint;
    
    private static void init() {
        account objAccount = TestDataFactory.createAccount();
        insert objAccount;
        
        Asset objectAsset = TestDataFactory.createAsset(objAccount.id);
        insert objectAsset;
        
        Case objCase = TestDataFactory.createCase();
        insert objCase;
        
        objComplaint = TestDataFactory.createComplaint(objCase.id);
        objComplaint.asset__c = objectAsset.id;
        insert objComplaint;
        
        Analysis_Report__c analysisReport = TestDataFactory.createAnalysisReport(objComplaint.id);
        insert analysisReport;
        
        Analysis_Report__c analysisReportLatest = TestDataFactory.createAnalysisReport(objComplaint.id);
        analysisReportLatest.date_sent_to_fda__c = system.today().addDays(-1);
        insert analysisReportLatest;        
    }
    
    /**
     * Test method for FDA form creation
     *
     * @return     void    
     * @author     SNPA 
     */    
    private static testMethod void testFDAFormCreation() {
        init();
        
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(objComplaint);
        FDA3500FormExtension formExtension = new FDA3500FormExtension(sc);
        
        PageReference pageRef = Page.FDA3500Form;
        pageRef.getParameters().put('id',objComplaint.id );
        Test.setCurrentPage(pageRef);
        
        FDA3500FormExtension.attachAsPdf(objComplaint.Id);
        test.stopTest();
        
        ContentDocumentLink conDoc = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId =:objComplaint.Id];
        system.assert(conDoc != null);
        system.assert(formExtension.complaint != null);
        system.assert(formExtension.analysisResult != null && formExtension.analysisResult.date_sent_to_fda__c == system.today().addDays(-1));       
        
    }
}