objects/Analysis_Report__c.object
<CustomObject>
    <description>CAN Analysis Result
The manufacturer will send the analysis results about complaints back to the MDR team. A record of this object is created automatically everytime, when feedback is pulled out of CAN.
FDA Analysis Result
Everytime the eMDR tool sends back feedback from the FDA a new record is created.</description>
    <fields>
        <fullName>complaint__c</fullName>
        <description>Linkage to initial complaint</description>
        <label>Complaint</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>complaint__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CardioMessenger Report, Out Of Service Report, Programmer Report, Revision Report, OUS/OEM Report, Returned Product Report, CardioMessenger Report, General Report, Out Of Service Report, Programmer Report, Revision Report</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>complaint__c</referenceTo>
        <relationshipLabel>Analysis Reports</relationshipLabel>
        <relationshipName>Analysis_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>conclusion_code__c</fullName>
        <description>pulled from CAN into SFDC</description>
        <label>Conclusion Code</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                    <label>10: Conclusion not yet available-evaluation in progress</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>11: Conclusion Not Yet Available</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>12: Cause Traced to Device Design</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13: Device difficult to operate</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14: Device incorrectly prepared for use or modified</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15: Device not manufactured by reporting firm</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <label>16: Device received unused in original package</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <label>18: Failure To Follow Instructions</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <label>19: Cause Traced to User</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>20: Inconclusive-investigation in progress</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <label>21: Cause Traced to Infrastructure</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <label>22: Known Inherent Risk of Device</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <label>23: Manufacturing Deficiency</label>
                </value>
                <value>
                    <fullName>24</fullName>
                    <label>24: Cause Traced to Intentional Off-Label, Unapproved, or Contraindicated Use</label>
                </value>
                <value>
                    <fullName>25</fullName>
                    <label>25: Cause Traced to Manufacturing</label>
                </value>
                <value>
                    <fullName>26</fullName>
                    <label>26: Reuse of Single Use Device</label>
                </value>
                <value>
                    <fullName>27</fullName>
                    <label>27: Cause Traced to Training</label>
                </value>
                <value>
                    <fullName>31</fullName>
                    <label>31: DO NOT USE</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>44: DO NOT USE</label>
                </value>
                <value>
                    <fullName>50</fullName>
                    <label>50: Adverse Event Related to Patient Condition</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>51: Cause Traced to Maintenance</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>54: DO NOT USE</label>
                </value>
                <value>
                    <fullName>57</fullName>
                    <label>57: Cause Traced to Labeling</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>61: Unintended Use Error Caused or Contributed to Event</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>63: Device repaired and returned</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>64: DO NOT USE</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>65: DO NOT USE</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>67: No Problem Detected</label>
                </value>
                <value>
                    <fullName>68</fullName>
                    <label>68: DO NOT USE</label>
                </value>
                <value>
                    <fullName>70</fullName>
                    <label>70: Device discarded - unable to follow-up</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Analysis Result</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Analysis Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analysis Results</pluralLabel>
    <recordTypes>
        <fullName>CAN_Analysis_Report</fullName>
        <active>true</active>
        <description>Feedback from CAN</description>
        <label>CAN Analysis Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/complaint__c.object
<CustomObject>
    <description>Medical Device Complaint used for reporting issues with patients that have a Biotronik device implanted.</description>
    <label>Complaint</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <recordTypes>
        <fullName>cardiomessenger_report</fullName>
        <active>true</active>
        <label>CardioMessenger Report</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AnalysisReportTriggerTest.cls
@isTest
public with sharing class AnalysisReportTriggerTest {


    public static testMethod void testDuplicate() {

        Case c = TestDataFactory.createCase();
        insert c;

        complaint__c complaint = TestDataFactory.createComplaint(c.Id);
        complaint.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'complaint__c' AND DeveloperName = 'cardiomessenger_report' LIMIT 1].Id;
        insert complaint;

        Analysis_Report__c ar1 = new Analysis_Report__c();
        ar1.complaint__c = complaint.Id;
        ar1.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Analysis_Report__c' AND DeveloperName = 'CAN_Analysis_Report' LIMIT 1].Id;
        ar1.conclusion_code__c = '110';

        insert ar1;

        // reset id and re-insert should result in an error
        String msg;
        ar1.Id = null;
        Test.startTest();
        try {
            insert ar1;
        }
        catch (DmlException e){
            msg = e.getDmlMessage(0);
        }
        Test.stopTest();

        System.assertEquals(AnalysisReportHandler.DUPLICATE_ANALYSIS_REPORT_ERROR, msg);
        System.assertEquals(1, [SELECT Id FROM Analysis_Report__c WHERE complaint__c =: complaint.Id].size());
    }

    public static testMethod void testNoDuplicate() {

        Case c = TestDataFactory.createCase();
        insert c;

        complaint__c complaint = TestDataFactory.createComplaint(c.Id);
        complaint.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'complaint__c' AND DeveloperName = 'cardiomessenger_report' LIMIT 1].Id;
        insert complaint;

        Analysis_Report__c ar1 = new Analysis_Report__c();
        ar1.complaint__c = complaint.Id;
        ar1.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Analysis_Report__c' AND DeveloperName = 'CAN_Analysis_Report' LIMIT 1].Id;
        ar1.conclusion_code__c = '110';
        insert ar1;


        Analysis_Report__c ar2 = new Analysis_Report__c();
        ar2.complaint__c = complaint.Id;
        ar2.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Analysis_Report__c' AND DeveloperName = 'CAN_Analysis_Report' LIMIT 1].Id;
        ar2.conclusion_code__c = '111';

        Test.startTest();
        insert ar2;
        Test.stopTest();

        System.assertEquals(2, [SELECT Id FROM Analysis_Report__c WHERE complaint__c =: complaint.Id].size());

    }

    public static testMethod void testDuplicateBulk() {

        Case c = TestDataFactory.createCase();
        insert c;

        complaint__c complaint = TestDataFactory.createComplaint(c.Id);
        complaint.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'complaint__c' AND DeveloperName = 'cardiomessenger_report' LIMIT 1].Id;
        insert complaint;

        Analysis_Report__c ar1 = new Analysis_Report__c();
        ar1.complaint__c = complaint.Id;
        ar1.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Analysis_Report__c' AND DeveloperName = 'CAN_Analysis_Report' LIMIT 1].Id;
        ar1.conclusion_code__c = '110';

        Analysis_Report__c ar2 = new Analysis_Report__c();
        ar2.complaint__c = complaint.Id;
        ar2.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Analysis_Report__c' AND DeveloperName = 'CAN_Analysis_Report' LIMIT 1].Id;
        ar2.conclusion_code__c = '111';

        insert new List<Analysis_Report__c>{ar1, ar2};

        // reset ids and re-insert should result in errors
        String msg;
        ar1.Id = null;
        ar2.Id = null;

        Test.startTest();
        List<Database.SaveResult> results =  database.insert(new List<Analysis_Report__c>{ar1, ar2}, false);
        Test.stopTest();

        System.assertEquals(2, [SELECT Id FROM Analysis_Report__c WHERE complaint__c =: complaint.Id].size());

        for(Database.SaveResult result : results){
            System.assertEquals(false, result.isSuccess());
            for(Database.Error err : result.getErrors()){
                System.assertEquals(AnalysisReportHandler.DUPLICATE_ANALYSIS_REPORT_ERROR, err.getMessage());
            }
        }

    }
}