objects/Analysis_Report__c.object
<CustomObject>
    <description>CAN Analysis Result
The manufacturer will send the analysis results about complaints back to the MDR team. A record of this object is created automatically everytime, when feedback is pulled out of CAN.
FDA Analysis Result
Everytime the eMDR tool sends back feedback from the FDA a new record is created.</description>
    <fields>
        <fullName>analysis_results__c</fullName>
        <description>3500a Question H10.  Brief Results of Analysis from MFG - Additional Manufacturer Narrative in 3500a</description>
        <label>Analysis Results</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>complaint__c</fullName>
        <description>Linkage to initial complaint</description>
        <label>Complaint</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>complaint__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CardioMessenger Report, Out Of Service Report, Programmer Report, Revision Report, OUS/OEM Report, Returned Product Report, CardioMessenger Report, General Report, Out Of Service Report, Programmer Report, Revision Report</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>complaint__c</referenceTo>
        <relationshipLabel>Analysis Reports</relationshipLabel>
        <relationshipName>Analysis_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Analysis Result</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Analysis Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analysis Results</pluralLabel>
    <recordTypes>
        <fullName>CAN_Analysis_Report</fullName>
        <active>true</active>
        <description>Feedback from CAN</description>
        <label>CAN Analysis Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/complaint__c.object
<CustomObject>
    <description>Medical Device Complaint used for reporting issues with patients that have a Biotronik device implanted.</description>
    <label>Complaint</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Complaint_Relationships__c.object
<CustomObject>
    <fields>
        <fullName>complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>complaint__c</referenceTo>
        <relationshipLabel>Complaint Relationships</relationshipLabel>
        <relationshipName>Complaint_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please choose a Physician or Other Contact.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician, Other Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Complaint Relationships</relationshipLabel>
        <relationshipName>Complaint_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>type_of_contact__c</fullName>
        <label>Type of contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Biotronik Contact Person</fullName>
                </value>
                <value>
                    <fullName>Dr Letter Recipient</fullName>
                </value>
                <value>
                    <fullName>Event Physician</fullName>
                </value>
                <value>
                    <fullName>Explanting Physician</fullName>
                </value>
                <value>
                    <fullName>Following Physician</fullName>
                </value>
                <value>
                    <fullName>Implanting Physician</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Returned Product Sender</fullName>
                </value>
                <value>
                    <fullName>Revising Physician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint Relationships</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Complaint Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DoctorLetterControllerExt.cls
/**
 * Controller to generate Doctors Letter file
 *
 * @author         emma
 * @created        2018-04-23
 * @systemLayer    Controller | Extension
 *
 **/
public with sharing class DoctorLetterControllerExt {

    public static final String DOCTOR_RECIPIENT = 'Dr Letter Recipient';
    public complaint__c complaints{get;set;}
    
    public boolean renderPanel{get;set;}
    public Date currentDate{get; set;}
    public String contentType{get; set;}
    
    public List<String> analysis {get;set;}
    public list<Contact> physicianDetails {get;set;}
    public Integer nbr{get; set;}
    
    //Labels for the template, so we can translate them.
    public String doctorLetterContent{get;set;}
    public String doctorLetterWarrantyContent{get;set;}
    public String doctorLetterWarrantyContentpart2{get;set;}
    public String patientName{get;set;} 
    public String explantDate{get;set;}
    public String implantDate{get;set;}
    public String deviceDescription{get;set;}
    public String reasonForAnalysis{get;set;}
    public String dear{get;set;}
    public String introduction{get;set;}
    public String sincerely {get;set;}
    public String salesRepresentative {get;set;}
    public String areaSalesDirector {get;set;}
    public String areaSalesVicePresident {get;set;}
    public String content {get;set;}
	public String msgLabel {get;set;}
	public String titleLabel {get;set;}
    /* 
	 * Standard controller / Constructor
	 */
    public DoctorLetterControllerExt(ApexPages.StandardController controller) {
		complaints = (complaint__c)controller.getRecord();
        Id idcom = complaints.Id;
       
        renderPanel = false;
        currentDate = sysdate();
        
        doctorLetterContent = System.Label.DOCTOR_LETTER_CONTENT;
        doctorLetterWarrantyContent = System.Label.DOCTOR_LETTER_WARRANTY_CONTENT;
        doctorLetterWarrantyContentpart2= System.Label.DOCTOR_LETTER_WARRANTY_CONTENT_2;
        patientName = System.Label.Patient_Name;
        explantDate = System.Label.Explant_Date;
        implantDate = System.Label.IMPLANT_DATE;
        deviceDescription = System.Label.Device_Description;
        reasonForAnalysis = System.Label.Reason_for_Analysis;
        dear = System.Label.dear_contact;
        introduction = System.Label.intoduction_to_device_description;
        sincerely = System.Label.sincerely;
        salesRepresentative = System.Label.Sales_Representative;
        areaSalesDirector = System.Label.Area_Sales_Director;
        areaSalesVicePresident = System.Label.Area_Sales_Vice_President;
        content = System.Label.content;
        msgLabel = System.Label.DOCTOR_LETTER_CREATED;
        titleLabel = System.Label.DOCTOR_LETTER_CREATION_PROCCES;
        
        
		//display analysis results
        map <Id,List<Analysis_Report__c>> analysisMap = new map <Id,List<Analysis_Report__c>>();
        analysisMap = getAnalysisFromComplaints(idcom);
        if (analysisMap.size() > 0){
            analysis = getListOfAnalysis(analysisMap.containsKey(idcom)?analysisMap.get(idcom) : null);
        }else{
            String msg = 'No Analysis available';
            list<String> noAnalysis = new list<String>{msg};
            analysis= noAnalysis;
        }
        
        //display the physician info (name and address)
        Set<Id> RecipientIdSet = new Set<Id>();
        try {
        	RecipientIdSet = getDoctorRecipients(idcom);
            physicianDetails = getPhysiciansDetails(RecipientIdSet);    
			nbr = physicianDetails.size();
        }catch(Exception e) {
           System.debug('Error'); 
        }  
    }

    //Current date  
    private Date sysdate(){
        Date today = Date.today();
        return today;
    }
    
    /**
     * Method to get all Ids physician with contact type DOCTOR_RECIPIENT 
     * from Complaint_Relationships__c
     * 
     * @param     complaint Id
     * @return    Set<Id>(contact)
     * @author    emma
     *
     **/
    @TestVisible
     private static Set<Id> getDoctorRecipients (Id complaintId){
    	Set <Id> physicianIdSet = new Set<Id>();
        for (Complaint_Relationships__c complaintsRelationship: [SELECT Id, 
                                                                 type_of_contact__c,
                                                                 complaint__c,
                                                                 contact__c
                                                                 FROM Complaint_Relationships__c
                                                                 WHERE
                                                                 complaint__c =:complaintId
                                                                 AND 
                                                                 type_of_contact__c =: DOCTOR_RECIPIENT]){   
                                                                     
                                physicianIdSet.add(complaintsRelationship.contact__c);
       } 
        return physicianIdSet;
    }
    
    
    /**
     * Method to get contact details needed for the template mapping
     * @param     Set<Id> (Contact)
     * @return    list<contact>
     * @author    emma
     *
     **/
    
    private list<Contact> getPhysiciansDetails (Set<Id> physicianIdSet){
        list <Contact> contactList = new list<Contact>();
        for (Contact contacts : [SELECT Id, 
                                 Name,
                                 Salutation,
                                 MailingStreet, 
                                 MailingPostalCode, 
                                 MailingCity, 
                                 MailingState, 
                                 MailingCountry
                                 FROM
                                 Contact
                                 WHERE
                                 Id IN : physicianIdSet]){
                                     contactList.add(contacts);  
                                 }
        return contactList;
    }
    
    /**
     * Helper Method,This map is to get all analysis report from the complaint
     * @param     complaint Id
     * @return    Map
     * @author    emma
     *
     **/
    private map <Id,List<Analysis_Report__c>> getAnalysisFromComplaints (Id complaintId){
        map <Id,List<Analysis_Report__c>> analysisReportMap = new map <Id,List<Analysis_Report__c>>();
        for (Analysis_Report__c analysisReportList : [SELECT Id, 
                                                      analysis_results__c,
                                                      complaint__c
                                                      FROM
                                                      Analysis_Report__c
                                                      WHERE
                                                      complaint__c =:complaintId
                                                      AND recordTypeId =:Utility.getRecordTypeId('Analysis_Report__c', 'CAN_Analysis_Report')
                                                      ORDER BY Id DESC
                                                      LIMIT 1]){
                                                          if (analysisReportMap.isEmpty()|| !analysisReportMap.containsKey(analysisReportList.complaint__c)){
                                                              analysisReportMap.put(analysisReportList.complaint__c, new list<Analysis_Report__c>{analysisReportList});
                                                          }else {
                                                              analysisReportMap.get(analysisReportList.complaint__c).add(analysisReportList); 
                                                          }
                                                                                                           
                                                      }
        return analysisReportMap;
    }
    
    /**
     * Method to get the list of analysis_ results related to the complaint 
     * that need to be displayed on the doctorLetter
     * 
     * @param     list of analysis report
     * @return    List of string
     * @author    emma
     *
     **/
    // get the list of analysis_ results related to the complaint that need to be displayed on the doctorLetter
    private List<String> getListOfAnalysis(List<Analysis_Report__c> analysisReportList){ 
        List<String> analysisList = new List<String>();
        if (analysisReportList !=null){
            for(Analysis_Report__c ans :analysisReportList){
                if (ans.analysis_results__c !=null){
                    analysisList.add(ans.analysis_results__c);
                }
            }    
        }
        return analysisList;
    }
    
    /**
     * @AuraEnabled Method Called from the component  Doctor letter selection
     * it check if there is doctors related to the complaint or not to generate the letter for them
     * 
     * @param     complaint Id
     * @return    string
     * @author    emma
     *
     **/
    
    @AuraEnabled
    public static String getErrorMsg(Id complaintId){
        
        Set<Id> RecipientIdSet = new Set<Id>();
        RecipientIdSet = getDoctorRecipients(complaintId);
        
        Integer recipientNbr = RecipientIdSet.size();
        String msg='';
            
        if (recipientNbr == 0){
            msg=System.Label.NO_DOCTOR_RECIPIENT_IS_FOUND;
        }else{
            msg = System.Label.DOCTOR_LETTER_CREATED;
        }
        return msg;
    }
    
}