objects/Analysis_Report__c.object
<CustomObject>
    <description>CAN Analysis Result
The manufacturer will send the analysis results about complaints back to the MDR team. A record of this object is created automatically everytime, when feedback is pulled out of CAN.
FDA Analysis Result
Everytime the eMDR tool sends back feedback from the FDA a new record is created.</description>
    <fields>
        <fullName>analysis_results__c</fullName>
        <description>3500a Question H10.  Brief Results of Analysis from MFG - Additional Manufacturer Narrative in 3500a</description>
        <label>Analysis Results</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>complaint__c</fullName>
        <description>Linkage to initial complaint</description>
        <label>Complaint</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>complaint__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CardioMessenger Report, Out Of Service Report, Programmer Report, Revision Report, OUS/OEM Report, Returned Product Report, CardioMessenger Report, General Report, Out Of Service Report, Programmer Report, Revision Report</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>complaint__c</referenceTo>
        <relationshipLabel>Analysis Reports</relationshipLabel>
        <relationshipName>Analysis_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>conclusion_code__c</fullName>
        <description>pulled from CAN into SFDC</description>
        <label>Conclusion Code</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                    <label>10: Conclusion not yet available-evaluation in progress</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>11: Conclusion Not Yet Available</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>12: Cause Traced to Device Design</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13: Device difficult to operate</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14: Device incorrectly prepared for use or modified</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15: Device not manufactured by reporting firm</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <label>16: Device received unused in original package</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <label>18: Failure To Follow Instructions</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <label>19: Cause Traced to User</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>20: Inconclusive-investigation in progress</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <label>21: Cause Traced to Infrastructure</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <label>22: Known Inherent Risk of Device</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <label>23: Manufacturing Deficiency</label>
                </value>
                <value>
                    <fullName>24</fullName>
                    <label>24: Cause Traced to Intentional Off-Label, Unapproved, or Contraindicated Use</label>
                </value>
                <value>
                    <fullName>25</fullName>
                    <label>25: Cause Traced to Manufacturing</label>
                </value>
                <value>
                    <fullName>26</fullName>
                    <label>26: Reuse of Single Use Device</label>
                </value>
                <value>
                    <fullName>27</fullName>
                    <label>27: Cause Traced to Training</label>
                </value>
                <value>
                    <fullName>31</fullName>
                    <label>31: DO NOT USE</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>44: DO NOT USE</label>
                </value>
                <value>
                    <fullName>50</fullName>
                    <label>50: Adverse Event Related to Patient Condition</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>51: Cause Traced to Maintenance</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>54: DO NOT USE</label>
                </value>
                <value>
                    <fullName>57</fullName>
                    <label>57: Cause Traced to Labeling</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>61: Unintended Use Error Caused or Contributed to Event</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>63: Device repaired and returned</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>64: DO NOT USE</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>65: DO NOT USE</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>67: No Problem Detected</label>
                </value>
                <value>
                    <fullName>68</fullName>
                    <label>68: DO NOT USE</label>
                </value>
                <value>
                    <fullName>70</fullName>
                    <label>70: Device discarded - unable to follow-up</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Analysis Result</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Analysis Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analysis Results</pluralLabel>
    <recordTypes>
        <fullName>CAN_Analysis_Report</fullName>
        <active>true</active>
        <description>Feedback from CAN</description>
        <label>CAN Analysis Report</label>
    </recordTypes>
    <recordTypes>
        <fullName>FDA_EMDR_Response</fullName>
        <active>true</active>
        <description>Response to EMDR submission</description>
        <label>FDA EMDR Response</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>hmsc_registration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SAFBIO-652</description>
        <label>HMSC Registration</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/complaint__c.object
<CustomObject>
    <description>Medical Device Complaint used for reporting issues with patients that have a Biotronik device implanted.</description>
    <fields>
        <fullName>asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>linkage from complaint to asset</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Complaint_Relationships__c.object
<CustomObject>
    <fields>
        <fullName>complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>complaint__c</referenceTo>
        <relationshipLabel>Complaint Relationships</relationshipLabel>
        <relationshipName>Complaint_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please choose a Physician or Other Contact.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician, Other Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Complaint Relationships</relationshipLabel>
        <relationshipName>Complaint_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>type_of_contact__c</fullName>
        <label>Type of contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Biotronik Contact Person</fullName>
                </value>
                <value>
                    <fullName>Dr Letter Recipient</fullName>
                </value>
                <value>
                    <fullName>Event Physician</fullName>
                </value>
                <value>
                    <fullName>Explanting Physician</fullName>
                </value>
                <value>
                    <fullName>Following Physician</fullName>
                </value>
                <value>
                    <fullName>Implanting Physician</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Returned Product Sender</fullName>
                </value>
                <value>
                    <fullName>Revising Physician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint Relationships</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Complaint Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>hmsc_registration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator whether a patient has an active registration with the Home Monitoring Service Center.</description>
        <label>HMSC Registration</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DoctorLetterControllerExtTest.cls
/**
 * Test class for DoctorLetterController
 *
 * @author         emma
 * @created        2018-04-23
 * @modified       2018-08-14
 * @systemLayer    Test
 *
 **/
@isTest
public class DoctorLetterControllerExtTest {
    static DoctorLetterControllerExt ext;
    static Asset objAsset;
    static Account objAccount;
    static Case  cases;
    static complaint__c complaints;
    static list<asset> assetList = new list<asset>();

    private static void init(){
        cases = TestDataFactory.createCase();
        insert cases;

        objAccount = TestDataFactory.createAccount();
        insert objAccount;

        objAsset = TestDataFactory.createAsset(objAccount.id);
        assetList.add(objAsset);
        insert objAsset;

        complaints  = TestDataFactory.createComplaint(cases.id);
        complaints.recordtypeid = Utility.getRecordTypeId ('complaint__c', ComplaintHandler.OOS_COMPLAINT);
        complaints.asset__c = objAsset.id;
    }
    static testMethod void validateDoctorLettr(){
        init();

        PageReference pref = Page.DoctorLetter;
        pref.getParameters().put('id',complaints.id);
        Test.setCurrentPage(pref);
        ApexPages.StandardController con = new ApexPages.StandardController(complaints);

        Test.startTest();
        ext = new DoctorLetterControllerExt(con);
        Test.stopTest();

        System.debug('**'+ext.complaints.Id );
        System.assertEquals(ext.complaints.Id, complaints.Id);
    }
    static testMethod void validatePhysicianDetails(){
        init ();
        Contact physician = new Contact(FirstName = 'Doctor_01',
                                        LastName = 'First',
                                        Salutation = 'Dr.',
                                        RecordTypeId = Utility.getRecordTypeId(Contact.SObjectType, Constants.RECORD_TYPE_NAME_CONTACT_US_PHYSICIAN),
                                        MailingStreet ='Street flower',
                                        MailingPostalCode ='01069',
                                        MailingCity ='Dresden',
                                        MailingState = 'Florida',
                                        MailingCountry = 'United States',
                                        hmsc_registration__c = false,
                                        AccountId = objAccount.Id
                                       );
        insert physician;
        Complaint_Relationships__c compRelation = new Complaint_Relationships__c (complaint__c	= complaints.id,
                                                                                  type_of_contact__c = DoctorLetterControllerExt.DOCTOR_RECIPIENT,
                                                                                  contact__c = physician.Id);
        insert compRelation;

        PageReference pref = Page.DoctorLetter;
        pref.getParameters().put('id',complaints.id);
        Test.setCurrentPage(pref);
        ApexPages.StandardController con = new ApexPages.StandardController(complaints);

        Test.startTest();
        ext = new DoctorLetterControllerExt(con);
        Test.stopTest();
        system.debug('asd'+ext);

        list<Contact> contactDetails = [SELECT Id,
                                        	   Salutation,
                                        	   Name,
                                        	   MailingStreet, MailingPostalCode, MailingCity, MailingState,
                                        	   MailingCountry
                                  		From Contact
                                        where Id =:physician.Id];

        system.assertEquals(ext.physicianDetails, contactDetails);

    }

    static testMethod void validateAnalysisResult(){
        init ();
        
        List<string> result = new list<string>();

        case objCase = TestDataFactory.createCase();
        insert objCase;

        complaint__c cmp = TestDataFactory.createComplaint(objCase.id);
        cmp.recordtypeid =
            Utility.getRecordTypeId ('complaint__c', ComplaintHandler.OOS_COMPLAINT);
        cmp.asset__c = objAsset.id;
        insert cmp;

        Analysis_Report__c analysis = new Analysis_Report__c(complaint__c = cmp.id,
                                                             analysis_results__c = 'This is the text of the analysis report .... and ....',
                                                             RecordTypeId = Utility.getRecordTypeId('Analysis_Report__c', 'CAN_Analysis_Report'),
                                                             conclusion_code__c = '110');
        Analysis_Report__c analysis2 = new Analysis_Report__c(complaint__c = cmp.id,
                                                              analysis_results__c = 'This is the text of the analysis report2 .... and ....',
                                                              RecordTypeId = Utility.getRecordTypeId('Analysis_Report__c', 'FDA_EMDR_Response'),
                                                              conclusion_code__c = '110');
		
        List<Analysis_Report__c> lstAnalysis =  new List<Analysis_Report__c>{analysis, analysis2};
        
        insert lstAnalysis;
		
        PageReference pref = Page.DoctorLetter;
        pref.getParameters().put('id',cmp.id);
        Test.setCurrentPage(pref);
        ApexPages.StandardController con = new ApexPages.StandardController(cmp);

        Test.startTest();
        ext = new DoctorLetterControllerExt(con);
        Test.stopTest();

        system.debug('asd'+ext);

        for(Analysis_Report__c ans :lstAnalysis){
            if (ans.RecordTypeId == Utility.getRecordTypeId('Analysis_Report__c', 'CAN_Analysis_Report')){

            	result.add(ans.analysis_results__c);
            }
        }
        System.assertEquals(ext.analysis, result);
    }
    static testMethod void validateAttachement(){
        init();
        case objCase = TestDataFactory.createCase();
        insert objCase;

        complaint__c cmp = TestDataFactory.createComplaint(objCase.id);
        cmp.recordtypeid =
            Utility.getRecordTypeId ('complaint__c', ComplaintHandler.OOS_COMPLAINT);
        cmp.asset__c = objAsset.id;
        insert cmp;

        Attachment attach=new Attachment();
        attach.parentId=cmp.Id;
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.ContentType = 'application/msword#DoctorLetter.doc';
        attach.IsPrivate = false;
        attach.Description = 'Test';
        insert attach;
        System.debug('Inserted: '+ attach.Id);

        PageReference pref = Page.DoctorLetter;
        pref.getParameters().put('id',cmp.id);
        system.debug('');
        Test.setCurrentPage(pref);
        ApexPages.StandardController con = new ApexPages.StandardController(cmp);

        Test.startTest();
        ext = new DoctorLetterControllerExt(con);
        Test.stopTest();

        List<Attachment> attachments=[select id, name, ContentType from Attachment where parent.id=:cmp.Id];
        System.assertEquals(1, attachments.size());

        String conType=[select id, name, ContentType from Attachment where parent.id=:cmp.Id].ContentType;
        System.assertEquals('application/msword#DoctorLetter.doc', conType);
    }
    static testMethod void validateGetError(){
     	init();
        case objCase = TestDataFactory.createCase();
        insert objCase;

        complaint__c cmp = TestDataFactory.createComplaint(objCase.id);
        cmp.recordtypeid =
            Utility.getRecordTypeId ('complaint__c', ComplaintHandler.OOS_COMPLAINT);
        cmp.asset__c = objAsset.id;
        insert cmp;
         Contact physician = new Contact(FirstName = 'Doctor_01',
                                        LastName = 'First',
                                        RecordTypeId = Utility.getRecordTypeId(Contact.SObjectType, Constants.RECORD_TYPE_NAME_CONTACT_US_PHYSICIAN),
                                        MailingStreet ='Street flower',
                                        MailingPostalCode ='01069',
                                        MailingCity ='Dresden',
                                        MailingState = 'Florida',
                                        MailingCountry = 'United States',
                                        hmsc_registration__c = false,
                                        AccountId = objAccount.Id
                                       );
        insert physician;
        Complaint_Relationships__c compRelation = new Complaint_Relationships__c (complaint__c	= cmp.id,
                                                                                  type_of_contact__c = DoctorLetterControllerExt.DOCTOR_RECIPIENT,
                                                                                  contact__c = physician.Id);
        insert compRelation;
        String msgReturn;
        Test.startTest();
        	msgReturn = DoctorLetterControllerExt.getErrorMsg(cmp.id);
        Test.stopTest();
        system.assertEquals(System.Label.DOCTOR_LETTER_CREATED, msgReturn);

    }


}