objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Days_from_Implant_to_Explant__c</fullName>
        <formula>Explant_Date__c - InstallDate</formula>
        <label>Days from Implant to Explant</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Explant_Date__c</fullName>
        <description>Date the Asset was explanted. In case the Asset goes through a change out process, the field is auto-updated with the implant date value of the replacing Asset.</description>
        <label>Explant Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>date_asset_status_changed__c</fullName>
        <description>Used in OOS validation rules.  Updated via process builder when Asset &apos;Status&apos;  is changed.</description>
        <label>Date Asset Status Changed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>event_reason__c</fullName>
        <label>Event Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>event_reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>explant_date_unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Explant Date Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>explanting_facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the explant</description>
        <label>Explanting Facility</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>x5500_us_account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Other_Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>explanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Explanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Explanted_Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>has_attached_oos_complaints__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A trigger checks, if the asset has already an attached OOS complaint.</description>
        <label>Has attached OOS complaints</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>imported_as_oos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imported as OOS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>oos_additional_information__c</fullName>
        <description>Reason device or lead was taken out of service (comment)</description>
        <label>OOS - Event  Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>oos_date__c</fullName>
        <description>Gives the date of the explanation. date can only be inserted if asset has the status &quot;explanted&quot;.
Date device was taken out of service (explanted, capped, or discarded)</description>
        <label>OOS Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implant Procedures</relationshipLabel>
        <relationshipName>Implants_Procedures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/event_reason.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Both</fullName>
    </customValue>
    <customValue>
        <fullName>Dislodgement</fullName>
    </customValue>
    <customValue>
        <fullName>ERI</fullName>
    </customValue>
    <customValue>
        <fullName>Erosion</fullName>
    </customValue>
    <customValue>
        <fullName>Error Message</fullName>
    </customValue>
    <customValue>
        <fullName>High shock impedance/High impedance</fullName>
    </customValue>
    <customValue>
        <fullName>High threshold</fullName>
    </customValue>
    <customValue>
        <fullName>Infection</fullName>
    </customValue>
    <customValue>
        <fullName>Landline Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Reposition</fullName>
    </customValue>
    <customValue>
        <fullName>Loss of Capture</fullName>
    </customValue>
    <customValue>
        <fullName>Low impedance</fullName>
    </customValue>
    <customValue>
        <fullName>Noise</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Oversensing</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Anatomy</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Death</fullName>
    </customValue>
    <customValue>
        <fullName>Pocket Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Power Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Safe mode/Back up Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Freeze</fullName>
    </customValue>
    <customValue>
        <fullName>Start Up</fullName>
    </customValue>
    <customValue>
        <fullName>Storm Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Telephone Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Transmit</fullName>
    </customValue>
    <customValue>
        <fullName>Undersensing</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Exposed to bodily fluids</fullName>
        <isActive>false</isActive>
        <label>Exposed to bodily fluids</label>
    </customValue>
    <customValue>
        <fullName>Diaphragmatic Stimulation</fullName>
        <isActive>false</isActive>
        <label>Diaphragmatic Stimulation</label>
    </customValue>
    <masterLabel>Event Reason</masterLabel>
</GlobalValueSet>

classes/OrderItemOosValidationCtrl.cls
/**
 *
 * This controller functions as a server side controller for the OrderItemOosValidation lightning component
 * 
 * It provides the selector part and functions for the needed updates on the order and order items
 * 
 * @author         ilu_pkas 
 * @modifiedBy     snpa
 * @created        2018-MM-DD
 * @modified       2018-08-29
 * @systemLayer    Controller
 *  
*/
public with sharing class OrderItemOosValidationCtrl {

    @AuraEnabled
    public static List<Asset> getMissingComplaintAssets(Id idOrder) {
    	Order objOrder = [SELECT Id, patient__c, 
                          			(SELECT createddate FROM Implants_Procedures__r) 
                          FROM Order 
                          	WHERE Id = :idOrder LIMIT 1];
        
        if(objOrder.Implants_Procedures__r != null && objOrder.Implants_Procedures__r.size() > 0) {
            Date createdDateIP = Date.valueOf(objOrder.Implants_Procedures__r[0].CreatedDate.date());
            if(Test.isRunningTest())
            	createdDateIP =  System.today().addDays(-4);
            List<Asset> assList = [SELECT Id, Name, Status, oos_date__c, oos_additional_information__c,			
                                     explant_date__c , explant_date_unknown__c , explanting_facility__c,
                                     explanting_physician__c , event_reason__c, has_attached_oos_complaints__c,
                                     days_from_implant_to_explant__c, InstallDate
                                FROM Asset WHERE Status IN : Constants.OOS_STATUS
                                    AND patient__c = :objOrder.patient__c
                                    AND imported_as_oos__c = FALSE
                                    AND RecordType.DeveloperName = : Constants.RECORD_TYPE_NAME_ASSET_US_BIOTRONIK
                                    AND (date_asset_status_changed__c = null 
                                         OR
                                            (date_asset_status_changed__c <= :System.today() 
                                                AND 
                                            date_asset_status_changed__c >= :createdDateIP))
                                  ];
            
            List<Asset> oosList = new List<Asset>();
            for (Asset assetObj : assList) {
                if( (assetObj.oos_date__c == null
                     || assetObj.oos_additional_information__c	== null			
                     || (assetObj.status == Constants.IMPLANT_STATUS_EXPLANTED && assetObj.explant_date__c == null && assetObj.explant_date_unknown__c == false)
                     || assetObj.event_reason__c == null
                     || (assetObj.has_attached_oos_complaints__c == false 
                         &&
                         ((assetObj.event_reason__c == Constants.PICKLIST_VALUE_OOS_REASON_ERI && assetObj.days_from_implant_to_explant__c < 1825 )
                          || (assetObj.event_reason__c == Constants.PICKLIST_VALUE_OOS_REASON_PATIENT_DEATH && assetObj.installDate != null && assetObj.days_from_implant_to_explant__c == 0)
                          || (assetObj.event_reason__c != Constants.PICKLIST_VALUE_OOS_REASON_UPGRADE )
                         )))) {
                    oosList.add(assetObj);
                } 
            }
            return oosList;
        } 
        return null;         
    } 
}