objects/Asset.object
<CustomObject>
    <fields>
        <fullName>hmsc_registration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SAFBIO-652</description>
        <label>HMSC Registration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linkage to the  Order record</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Patient)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>hmsc_registration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator whether a patient has an active registration with the Home Monitoring Service Center.</description>
        <label>HMSC Registration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hmsc_registration_stringval__c</fullName>
        <description>This field is created purely for technical purpose and should not be added on any layout. Since, HMSC TWD is sending &apos;yes&apos; OR &apos;No&apos; value from CSV file, we can&apos;t insert these values directly, that&apos;s why this field is required.</description>
        <label>HMSC_Registration_StringVal</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>date_cm_submitted__c</fullName>
        <description>Used for setting time stamp when the CM was submitted.</description>
        <label>Date CM Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/HmscRegistrationCheckBatchTest.cls
/**
 *
 * Test class for the HmscRegistrationCheckBatch
 * 
 * @author         ilu_pkas 
 * @modifiedBy     ilu_pkas
 * @created        2018-MM-DD
 * @modified       2018-08-30
 * @systemLayer    Test 
 *  
*/
@isTest
public class HmscRegistrationCheckBatchTest {
	static Account objAccount;  
    static Order objOrder;
    static Contact objPatient;
    static User testUser;    
    
    private static void init(){
        objAccount = TestDataFactory.createAccount();
        insert objAccount;
        
        objPatient = TestDataFactory.createPatient(false);
        objPatient.AccountId = objAccount.Id;
        insert objPatient;
        
        Id orderRtId =  Utility.getRecordTypeId(Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
        objOrder = TestDataFactory.createOrder(objAccount.Id);
        objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_PENDING_HMSC;
        objOrder.RecordTypeId = orderRtId;
        objOrder.PoNumber = '123456789test';
        objOrder.patient__c = objPatient.Id;
        objOrder.rep_at_implant__c = UserInfo.getUserId();
        objOrder.date_cm_submitted__c = Date.today().addDays(-10);
       
        insert objOrder;      
        
        System.debug('### '+[SELECT Status FROM Order WHERE ID = :objOrder.Id]);
    }
    
    /**
     * This test case generates coverage for the call of the salesforce internal schedule feature
     */
    @isTest
    private static void testScheduel(){
        Test.startTest();
            HmscRegistrationCheckBatch myClass = new HmscRegistrationCheckBatch();   
            String chron = '0 0 23 * * ?';        
            System.schedule('Test Sched', chron, myClass);
        Test.stopTest();
    }
    
    @isTest
    private static void testBatch(){
        init();
        
        Product2 prod = new Product2(Name = 'ICD');
        prod.product_type__c = 'ICD';
        insert prod;
        
        Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
        objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        objAsset.order__c = objOrder.id;
        objAsset.status = Constants.IMPLANT_STATUS_IMPLANTED;
        objAsset.Product2Id = prod.Id;
        insert objAsset;
         
        objPatient.hmsc_registration__c = true;
        objPatient.HMSC_Registration_StringVal__c = 'yes';
        update objPatient;
        
        Test.startTest();
        	HmscRegistrationCheckBatch batch = new HmscRegistrationCheckBatch();
        	Database.executeBatch(batch);
        Test.stopTest();
        
        objOrder = [SELECT Id, Status FROM Order WHERE Id = :objOrder.Id];
        System.assertEquals(Constants.PICKLIST_VALUE_ORDER_STATUS_PENDING_SAP, objOrder.Status);

    }
    /*
    @isTest
    private static void testBatchCancelation(){
        init();
        
        Product2 prod = new Product2(Name = 'ICD');
        prod.product_type__c = 'ICD';
        insert prod;
        
        Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
        objAsset.product_type__c = OrderHandler.ICD;
        objAsset.order__c = objOrder.id;
        objAsset.status = AssetHandler.IMPLANTED;
        objAsset.Product2Id = prod.Id;
        insert objAsset;

        Integer intDays = Integer.valueOf(Utility.getSettingValue(HmscRegistrationCheckBatch.IDENTIFIER_HMSC_BATCH_CONFIG));
        objOrder.date_cm_submitted__c = Date.today().addDays(-intDays - 10);
        update objOrder;
        
        Test.startTest();
        	HmscRegistrationCheckBatch batch = new HmscRegistrationCheckBatch();
        	Database.executeBatch(batch);
        Test.stopTest();
        
        objOrder = [SELECT Id, Status FROM Order WHERE Id = :objOrder.Id];
        System.assertEquals(HmscRegistrationCheckBatch.CANCELED, objOrder.Status);
    }*/
}