objects/Asset.object
<CustomObject>
    <fields>
        <fullName>expiration_date_ubd__c</fullName>
        <description>use by date. If the MDRF user selects (by scanning or manual entry) Asset that is past its Use by Date (UBD), the system will send a warning to the screen which the user must acknowledge.  It does not prevent the MDRF entry process from continuing with UBD asset (the product may already have been implanted at the time the MDRF is being completed).</description>
        <label>Expiration date (UBD)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>order_product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>submit_to_sap__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checkbox which triggers the status change to &apos;Submitted&apos; and Submission process to SAP</description>
        <label>Submit to SAP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>expiration_date_ubd__c</fullName>
        <description>Date after which product expires and must not be used</description>
        <label>Expiration date (UBD)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductConsumed.object
<CustomObject>
    <fields>
        <fullName>asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Products Consumed</relationshipLabel>
        <relationshipName>Products_Consumed</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>expiration_date_ubd__c</fullName>
        <description>Date after which product expires and must not be used</description>
        <formula>ProductItem.expiration_date_ubd__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date after which product expires and must not be used</inlineHelpText>
        <label>Expiration date (UBD)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>Product type defined by the picklist located in the related Product Item record.</description>
        <formula>TEXT(ProductItem.product_type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <inlineHelpText>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</inlineHelpText>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrderItemRemoveCtrl_Test.cls
/**
 *
 * Testclass for the OrderItemRemoveCtrl
 * 
 * @author         ilu_pkas 
 * @modifiedBy     ilu_pkas
 * @created        2018-MM-DD
 * @modified       2018-08-30
 * @systemLayer    Test 
 *  
*/
@isTest
public class OrderItemRemoveCtrl_Test {

   	static Account objAccount;  
    static Order objOrder;
    static User testUser;
    
   	private static void init(){
        objAccount = TestDataFactory.createAccount();
        insert objAccount;

        objOrder = TestDataFactory.createOrder(objAccount.Id);
        objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_NOT_SUBMITTED;
        objOrder.RecordTypeId = Utility.getRecordTypeId(Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
        objOrder.submit_to_sap__c = true;
        objOrder.PoNumber = 'aplhanumeric1234';        
        objOrder.rep_at_implant__c = UserInfo.getUserId();
        insert objOrder;
    }
    
    @isTest
    private static void simpleOrderItemNoSystem(){
        init();
        
        OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
        objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        objOrderItem.part_of_system_price__c = false;
        objOrderItem.UnitPrice = 0;
        objOrderItem.expiration_date_ubd__c = Date.today();
        insert objOrderItem;
        
        Integer intItemCountBefore = [SELECT Id FROM OrderItem].size();
        System.debug('### '+intItemCountBefore);
        
        Test.startTest();
        	ApexPages.currentPage().getParameters().put('id', String.valueOf(objOrderItem.Id));
        	ApexPages.StandardController stdOrderItem = new ApexPages.StandardController(objOrderItem);
        	OrderItemRemoveCtrl ctrl = new OrderItemRemoveCtrl(stdOrderItem);
        	ctrl.checkForDeletion();        
        Test.stopTest();
        
        Integer intItemCountAfter = [SELECT Id FROM OrderItem].size();
       	System.debug('### '+intItemCountAfter);
        
        System.assertEquals(0, intItemCountAfter);
    }
    
    
    @isTest
    private static void complexOrderItemNoSystem(){
        init();
        
        OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
        objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        objOrderItem.part_of_system_price__c = false;
        objOrderItem.UnitPrice = 0;
        objOrderItem.expiration_date_ubd__c = Date.today();
        insert objOrderItem;
        
        Asset objAsset = TestDataFactory.createAsset(objAccount.Id);
        objAsset.order_product__c = objOrderItem.Id;
        insert objAsset;
        
        Product2 prod = new Product2(Name = 'ICD');
        insert prod;
		Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        WorkOrder objWorkOrder = new WorkOrder();
        objWorkOrder.StartDate = Date.today();
        objWorkOrder.EndDate = Date.today();
        objWorkOrder.Pricebook2Id = pricebookId;
        objWorkORder.rep_at_implant__c = UserInfo.getUserId();
        insert objWorkOrder;
        
        ProductConsumed item = new ProductConsumed();
        item.WorkOrderId = objWorkOrder.Id;
        item.PricebookEntryId = standardPrice.Id;
        item.QuantityConsumed = 2;
        item.asset__c = objAsset.Id;
        insert item;
        
        Integer intItemCountBefore = [SELECT Id FROM OrderItem].size();
        Integer intAssetCountBefore = [SELECT Id FROM Asset].size();
        Integer intProdConCountBefore = [SELECT Id FROM ProductConsumed].size();
        System.debug('### Items '+intItemCountBefore);
        System.debug('### Asset '+intAssetCountBefore);
        System.debug('### ProdCon '+intProdConCountBefore);
        
        Test.startTest();
        	ApexPages.currentPage().getParameters().put('id', String.valueOf(objOrderItem.Id));
        	ApexPages.StandardController stdOrderItem = new ApexPages.StandardController(objOrderItem);
        	OrderItemRemoveCtrl ctrl = new OrderItemRemoveCtrl(stdOrderItem);
        	ctrl.checkForDeletion();        
        Test.stopTest();
        
        Integer intItemCountAfter = [SELECT Id FROM OrderItem].size();
        Integer intAssetCountAfter = [SELECT Id FROM Asset].size();
        Integer intProdConCountAfter = [SELECT Id FROM ProductConsumed].size();
       	System.debug('### Item '+intItemCountAfter);
        System.debug('### Asset '+intAssetCountAfter);
        System.debug('### ProdCon '+intProdConCountAfter);
        
        System.assertEquals(0, intItemCountAfter);
        System.assertEquals(0, intAssetCountAfter);
        System.assertEquals(0, intProdConCountAfter);
    }
    
    @isTest
    private static void deleteRec(){
        init();
        
        OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
        objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
        objOrderItem.part_of_system_price__c = false;
        objOrderItem.UnitPrice = 0;
        objOrderItem.expiration_date_ubd__c = Date.today();
        insert objOrderItem;
        
        Integer intItemCountBefore = [SELECT Id FROM OrderItem].size();
        System.debug('### '+intItemCountBefore);
        
        Test.startTest();
        	ApexPages.currentPage().getParameters().put('id', String.valueOf(objOrderItem.Id));
        	ApexPages.StandardController stdOrderItem = new ApexPages.StandardController(objOrderItem);
        	OrderItemRemoveCtrl ctrl = new OrderItemRemoveCtrl(stdOrderItem);
        Test.stopTest();
        
        Integer intItemCountAfter = [SELECT Id FROM OrderItem].size();
       	System.debug('### '+intItemCountAfter);
        
        System.assertEquals(intItemCountBefore, intItemCountAfter);
    }
}