objects/Asset.object
<CustomObject>
    <fields>
        <fullName>date_asset_status_changed__c</fullName>
        <description>Used in OOS validation rules.  Updated via process builder when Asset &apos;Status&apos;  is changed.</description>
        <label>Date Asset Status Changed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>event_reason__c</fullName>
        <label>Event Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>event_reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>has_attached_oos_complaints__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A trigger checks, if the asset has already an attached OOS complaint.</description>
        <label>Has attached OOS complaints</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>imported_as_oos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imported as OOS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>oos_additional_information__c</fullName>
        <description>Reason device or lead was taken out of service (comment)</description>
        <label>OOS - Event  Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>oos_date__c</fullName>
        <description>Gives the date of the explanation. date can only be inserted if asset has the status &quot;explanted&quot;.
Date device was taken out of service (explanted, capped, or discarded)</description>
        <label>OOS Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linkage to the  Order record</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>submit_to_sap__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checkbox which triggers the status change to &apos;Submitted&apos; and Submission process to SAP</description>
        <label>Submit to SAP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implant Procedures</relationshipLabel>
        <relationshipName>Implants_Procedures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/event_reason.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Both</fullName>
    </customValue>
    <customValue>
        <fullName>Dislodgement</fullName>
    </customValue>
    <customValue>
        <fullName>ERI</fullName>
    </customValue>
    <customValue>
        <fullName>Erosion</fullName>
    </customValue>
    <customValue>
        <fullName>Error Message</fullName>
    </customValue>
    <customValue>
        <fullName>High shock impedance/High impedance</fullName>
    </customValue>
    <customValue>
        <fullName>High threshold</fullName>
    </customValue>
    <customValue>
        <fullName>Infection</fullName>
    </customValue>
    <customValue>
        <fullName>Landline Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Reposition</fullName>
    </customValue>
    <customValue>
        <fullName>Loss of Capture</fullName>
    </customValue>
    <customValue>
        <fullName>Low impedance</fullName>
    </customValue>
    <customValue>
        <fullName>Noise</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Oversensing</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Anatomy</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Death</fullName>
    </customValue>
    <customValue>
        <fullName>Pocket Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Power Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Safe mode/Back up Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Freeze</fullName>
    </customValue>
    <customValue>
        <fullName>Start Up</fullName>
    </customValue>
    <customValue>
        <fullName>Storm Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Telephone Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Transmit</fullName>
    </customValue>
    <customValue>
        <fullName>Undersensing</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Exposed to bodily fluids</fullName>
        <isActive>false</isActive>
        <label>Exposed to bodily fluids</label>
    </customValue>
    <customValue>
        <fullName>Diaphragmatic Stimulation</fullName>
        <isActive>false</isActive>
        <label>Diaphragmatic Stimulation</label>
    </customValue>
    <masterLabel>Event Reason</masterLabel>
</GlobalValueSet>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrderItemOosValidationCtrlTest.cls
@isTest
public class OrderItemOosValidationCtrlTest {
    static Account objAccount;
    static Order objOrder;
    static Asset objAsset;
    static User testUser;

    public static void setup(){
        testUser = TestDataFactory.createUser(UserInfo.getProfileId());
        testUser.UserRoleId = [SELECT Id FROM UserRole WHERE DeveloperName = : Constants.USER_ROLE_NAME_SO LIMIT 1].Id;

        System.runAs(testUser){
            objAccount = TestDataFactory.createAccount();
            insert objAccount;

            Id orderRtId =  Utility.getRecordTypeId ('Order', Constants.RECORD_TYPE_NAME_ORDER_MDRF);
            objOrder = TestDataFactory.createOrder(objAccount.Id);
            objOrder.RecordTypeId = orderRtId;
            objOrder.submit_to_sap__c = true;
            objOrder.PoNumber = '1234';
            insert objOrder;
			
            WorkOrder wo = TestDataFactory.createWorkOrder();
            wo.order__c = objOrder.Id;
            insert wo;
            
            Product2 prod = new Product2(Name = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD);
            prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            insert prod;

            objAsset = TestDataFactory.createAsset(objAccount.Id);
            System.debug('patient '+objOrder.patient__c);
            objAsset.recordTypeId = Utility.getRecordTypeId ('Asset', Constants.RECORD_TYPE_NAME_ASSET_US_BIOTRONIK);
            objAsset.patient__c = objOrder.patient__c;
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objAsset.product2Id = prod.Id;
            objAsset.status = Constants.IMPLANT_STATUS_CAPPED;
            objAsset.oos_date__c = null;
            objAsset.date_asset_status_changed__c = system.today().addDays(-1);
            objAsset.imported_as_oos__c = false;
            insert objAsset;
        }
    }
    
    @isTest
    public static void getOosAssets(){
        setup();
        List<Asset> lstOosAssets = new List<Asset>();
        
        Test.startTest();
        	lstOosAssets = OrderItemOosValidationCtrl.getMissingComplaintAssets(objOrder.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstOosAssets.size());
    }
    
    @isTest
    public static void getOosAssetsWithNotRelevantOosAsset(){
        setup();
        List<Asset> lstOosAssets = new List<Asset>();
        System.runAs(testUser){
            
            objAsset.oos_date__c = Date.today();
            objAsset.oos_additional_information__c = 'Test';
            objAsset.event_reason__c = Constants.PICKLIST_VALUE_OOS_REASON_UPGRADE;
            objAsset.has_attached_oos_complaints__c = false;
            update objAsset;
            
            Test.startTest();
                lstOosAssets = OrderItemOosValidationCtrl.getMissingComplaintAssets(objOrder.Id);
            Test.stopTest();
        }
        System.assertEquals(0, lstOosAssets.size());
    }
    
    @isTest
    public static void submitForProcessing(){
        setup();
        
        System.runAs(testUser){
			List<OrderItem> lstItems = new List<OrderItem>();
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderItem.part_of_system_price__c = false;
            objOrderItem.UnitPrice = 0;
            lstItems.add(objOrderItem);

            OrderItem objLead = TestDataFactory.createOrderItem(objOrder.Id);
            objLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead.UnitPrice = 1;
            lstItems.add(objLead);

            OrderItem objLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead2.UnitPrice = 1;
            lstItems.add(objLead2);

            insert lstItems;
            
            Test.startTest();
                objOrder.status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            	update objOrder;	
            Test.stopTest();
        }
        objOrder = [SELECT Id, Status FROM Order WHERE Id = :objOrder.Id];
        System.assertNotEquals(Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING, objOrder.Status);
    }
    
    
}