objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Explant_Date__c</fullName>
        <description>Date the Asset was explanted. In case the Asset goes through a change out process, the field is auto-updated with the implant date value of the replacing Asset.</description>
        <label>Explant Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>event_reason__c</fullName>
        <label>Event Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>event_reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>has_attached_oos_complaints__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A trigger checks, if the asset has already an attached OOS complaint.</description>
        <label>Has attached OOS complaints</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>oos_additional_information__c</fullName>
        <description>Reason device or lead was taken out of service (comment)</description>
        <label>OOS - Event  Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>oos_date__c</fullName>
        <description>Gives the date of the explanation. date can only be inserted if asset has the status &quot;explanted&quot;.
Date device was taken out of service (explanted, capped, or discarded)</description>
        <label>OOS Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linkage to the  Order record</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>stock_type__c</fullName>
        <description>Stock Location of the asset.</description>
        <label>Stock Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B</fullName>
                    <label>Bulk</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Consignment Stock</label>
                </value>
                <value>
                    <fullName>L</fullName>
                    <label>Loaned Stock</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Trunk Stock</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>submit_to_sap__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checkbox which triggers the status change to &apos;Submitted&apos; and Submission process to SAP</description>
        <label>Submit to SAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>validation_reason__c</fullName>
        <description>Auto-filled comment field to create task description lines for CAS</description>
        <label>Validation Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Price Discrepancy Reason = Bulk swap</fullName>
                </value>
                <value>
                    <fullName>Implanting facility in Puerto Rico**</fullName>
                </value>
                <value>
                    <fullName>Alphanumeric PO Number**</fullName>
                </value>
                <value>
                    <fullName>Donation**</fullName>
                </value>
                <value>
                    <fullName>Bulk Product with Price &gt; $0</fullName>
                </value>
                <value>
                    <fullName>Part of System &amp; Price &gt; $0</fullName>
                </value>
                <value>
                    <fullName>$0 Product outside System</fullName>
                </value>
                <value>
                    <fullName>Unverified physician</fullName>
                </value>
                <value>
                    <fullName>Device with no leads</fullName>
                </value>
                <value>
                    <fullName>Patient Shipping Address is P.O. Box</fullName>
                </value>
                <value>
                    <fullName>Unverified Patient Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Lead with no Device</fullName>
                </value>
                <value>
                    <fullName>Device with only one Lead</fullName>
                </value>
                <value>
                    <fullName>More than 1 Device on MDRF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>price_discrepancy_reason__c</fullName>
        <description>When the Order Product price is manually adjusted, the reason is required</description>
        <label>Price Discrepancy Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One-time exception</fullName>
                </value>
                <value>
                    <fullName>No price loaded for product</fullName>
                </value>
                <value>
                    <fullName>Loaded price is incorrect</fullName>
                </value>
                <value>
                    <fullName>Proposed price</fullName>
                </value>
                <value>
                    <fullName>Bulk swap</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>stock_type__c</fullName>
        <description>Stock Location of the asset.</description>
        <label>Stock Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B</fullName>
                    <label>Bulk</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Consignment Stock</label>
                </value>
                <value>
                    <fullName>L</fullName>
                    <label>Loaned Stock</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Trunk Stock</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sub_group_4__c</fullName>
        <label>Sub-group (4)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/event_reason.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Both</fullName>
    </customValue>
    <customValue>
        <fullName>Dislodgement</fullName>
    </customValue>
    <customValue>
        <fullName>ERI</fullName>
    </customValue>
    <customValue>
        <fullName>Erosion</fullName>
    </customValue>
    <customValue>
        <fullName>Error Message</fullName>
    </customValue>
    <customValue>
        <fullName>High shock impedance/High impedance</fullName>
    </customValue>
    <customValue>
        <fullName>High threshold</fullName>
    </customValue>
    <customValue>
        <fullName>Infection</fullName>
    </customValue>
    <customValue>
        <fullName>Landline Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Reposition</fullName>
    </customValue>
    <customValue>
        <fullName>Loss of Capture</fullName>
    </customValue>
    <customValue>
        <fullName>Low impedance</fullName>
    </customValue>
    <customValue>
        <fullName>Noise</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Oversensing</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Anatomy</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Death</fullName>
    </customValue>
    <customValue>
        <fullName>Pocket Revision</fullName>
    </customValue>
    <customValue>
        <fullName>Power Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Safe mode/Back up Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Freeze</fullName>
    </customValue>
    <customValue>
        <fullName>Start Up</fullName>
    </customValue>
    <customValue>
        <fullName>Storm Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Telephone Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Transmit</fullName>
    </customValue>
    <customValue>
        <fullName>Undersensing</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Exposed to bodily fluids</fullName>
        <isActive>false</isActive>
        <label>Exposed to bodily fluids</label>
    </customValue>
    <customValue>
        <fullName>Diaphragmatic Stimulation</fullName>
        <isActive>false</isActive>
        <label>Diaphragmatic Stimulation</label>
    </customValue>
    <masterLabel>Event Reason</masterLabel>
</GlobalValueSet>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrderValidationTest.cls
/**
* @author:			arwe
*					T-Systems Multimedia Solutions GmbH
*					Riesaer Strasse 5,
*					01129 Dresden
*					www.t-systems-mms.com
*
* @description      
*                  
*
* @date             12.10.2018
* 
*/

@IsTest
private class OrderValidationTest {

    static Account objAccount;
    static Order objOrder;
    static User testUser;


    @isTest
    static void testValidOrder(){
        init();

        System.runAs(testUser){
            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objAsset.Product2Id = prod.Id;
            objAsset.patient__c = objOrder.patient__c;
            insert objAsset;

            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_PACEMAKER;
            objOrderDevice.stock_type__c = 'L';
            objOrderDevice.part_of_system_price__c = true;
            objOrderDevice.UnitPrice = 0;
            lstOrderItems.add(objOrderDevice);
            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            OrderItem objOrderLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead2.part_of_system_price__c = true;
            objOrderLead2.UnitPrice = 0;
            lstOrderItems.add(objOrderLead2);
            insert lstOrderItems;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        assertValidation(Constants.PICKLIST_VALIDATION_REASON_NONE);
    }

    /**
    * Method checks OrderItem is a Lead and "Price" = $0, AND not part of the System
    * and MDRF status is changed to processing then send the order to review
    */
    @isTest
    static void testZeroDollarLeadOutsideSystem() {
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_PACEMAKER;
            objOrderDevice.stock_type__c = 'L';
            objOrderDevice.part_of_system_price__c = false;
            objOrderDevice.UnitPrice = 0;
            lstOrderItems.add(objOrderDevice);

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            OrderItem objOrderLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead2.part_of_system_price__c = true;
            objOrderLead2.UnitPrice = 0;
            lstOrderItems.add(objOrderLead2);
            insert lstOrderItems;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        assertValidation(Constants.PICKLIST_VALIDATION_REASON_ZERO_DOLLAR_PRODUCT_OUTSIDE_SYSTEM);
    }

    @isTest
    static void testZeroDollarLoopRecorderOutsideSystem() {
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LOOP_RECORDER;
            objOrderDevice.stock_type__c = 'L';
            objOrderDevice.part_of_system_price__c = false;
            objOrderDevice.UnitPrice = 0;
            lstOrderItems.add(objOrderDevice);

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            OrderItem objOrderLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead2.part_of_system_price__c = true;
            objOrderLead2.UnitPrice = 0;
            lstOrderItems.add(objOrderLead2);
            insert lstOrderItems;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        assertValidation(Constants.PICKLIST_VALIDATION_REASON_ZERO_DOLLAR_PRODUCT_OUTSIDE_SYSTEM);
    }

    /**
    * Method checks OrderItem has Location as "Bulk Stock", OrderItem Adjusted Price > 0
    * and MDRF status is changed to processing from Not submitted
    * then send the order to review
    */
    @isTest
    static void testBulkProductPriceGreaterZero() {
        init();

        System.runAs(testUser){
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.stock_type__c = Constants.PICKLIST_VALUE_ORDER_ITEM_STOCK_TYPE_BULK;
            objOrderItem.UnitPrice = 19;
            insert objOrderItem;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }
        assertValidation(Constants.PICKLIST_VALIDATION_REASON_BULK_PRODUCT_WITH_PRICE_GREATER_ZERO);
    }

    /**
    * Method checks Implanting facility is in  Puerto Rico
    * then send the order to review
    */
    @isTest
    static void testLocationPuertoRico() {
        init();

        System.runAs(testUser){
            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objAsset.Product2Id = prod.Id;
            objAsset.patient__c = objOrder.patient__c;
            insert objAsset;

            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_PACEMAKER;
            objOrderDevice.stock_type__c = 'L';
            objOrderDevice.part_of_system_price__c = true;
            objOrderDevice.UnitPrice = 0;
            lstOrderItems.add(objOrderDevice);
            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            OrderItem objOrderLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead2.part_of_system_price__c = true;
            objOrderLead2.UnitPrice = 0;
            lstOrderItems.add(objOrderLead2);
            insert lstOrderItems;

            objAccount.ShippingCountryCode = 'US';
            objAccount.ShippingStateCode = 'PR';
            update objAccount;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }
        assertValidation(Constants.PICKLIST_VALIDATION_REASON_IMPLANTING_FACILITY_IN_PUERTO_RICO);
    }

    /**
    * Method checks if asset is part of system and has price more than 0
    * then send the order to review
    */
    @isTest
    static void testPartOfSysOrderItemPrice() {
        init();

        System.runAs(testUser){
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.part_of_system_price__c = true;
            objOrderItem.UnitPrice = 19;
            insert objOrderItem;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        assertValidation(Constants.PICKLIST_VALIDATION_REASON_PART_OF_SYSTEM_AND_PRICE_GREATER_ZERO);
    }

    /**
    * Method checks if asset is device out of system and has price more than 0
    * then send the order to review to customer solution queue
    */
    @isTest
    static void testDeviceWithNoLeads(){
        init();

        System.runAs(testUser){
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderItem.part_of_system_price__c = false;
            objOrderItem.UnitPrice = 2;
            insert objOrderItem;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }
        assertValidation(Constants.PICKLIST_VALIDATION_REASON_DEVICE_WITH_NO_LEADS);
    }

    /**
    * Method checks if asset is device out of system and has price more than 0
    * then send the order to review to customer solution queue
    */
    @isTest
    static void testDeviceWithOneNotImplantedLead(){
        init();

        System.runAs(testUser){
            Product2 prod = new Product2(Name = 'Lead');
            prod.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.patient__c = objOrder.patient__c;
            objAsset.Status = Constants.IMPLANT_STATUS_EXPLANTED;
            objAsset.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objAsset.Product2Id = prod.Id;

            objAsset.oos_date__c = Date.today();
            objAsset.oos_additional_information__c = 'test';
            objAsset.explant_Date__c = Date.today();
            objAsset.event_reason__c = Constants.PICKLIST_VALUE_OOS_REASON_UPGRADE;
            objAsset.has_attached_oos_complaints__c = false;
            insert objAsset;

            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderItem.part_of_system_price__c = false;
            objOrderItem.UnitPrice = 2;
            insert objOrderItem;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }
        assertValidation(Constants.PICKLIST_VALIDATION_REASON_DEVICE_WITH_NO_LEADS);
    }

    /**
    * Method checks if reason for price discepancy is bulk swap then send to review
    * also when the order is reviewed in 2nd step submit it to SAP and chnge queue
    */
    @isTest
    static void testSecondStep(){
        init();

        System.runAs(testUser){
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;

            objOrderItem.price_discrepancy_reason__c = Constants.PICKLIST_VALUE_ORDER_ITEM_DISCREPANY_REASON_BULKSWAP;
            objOrderItem.UnitPrice = 1;
            insert objOrderItem;

            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;

            objOrder = [SELECT Id, OwnerId, submit_to_sap__c, validation_reason__c FROM Order WHERE Id = :objOrder.Id];

            assertValidation(Constants.PICKLIST_VALIDATION_REASON_PRICE_DISCREPANCY_REASON_BULK_SWAP);

            Test.startTest();
            objOrderItem.price_discrepancy_reason__c = '';
            update objOrderItem;

            objOrder.validation_reason__c = 'None';
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_PENDING_SAP;
            update objOrder;
            Test.stopTest();
        }

        assertValidation(Constants.PICKLIST_VALIDATION_REASON_NONE);
    }

    /**
   * Method checks validation for more than one realated device
   */
    @isTest
    static void test2DeviceWith2Leads(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstItems = new List<OrderItem>();
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_PACEMAKER;
            objOrderItem.part_of_system_price__c = false;
            objOrderItem.UnitPrice = 0;
            lstItems.add(objOrderItem);

            OrderItem objOrderItem2 = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_PACEMAKER;
            objOrderItem2.part_of_system_price__c = false;
            objOrderItem2.UnitPrice = 0;
            lstItems.add(objOrderItem2);

            OrderItem objLead = TestDataFactory.createOrderItem(objOrder.Id);
            objLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead.price_discrepancy_reason__c = Constants.PICKLIST_VALUE_ORDER_ITEM_DISCREPANY_REASON_BULKSWAP;
            objLead.UnitPrice = 1;
            lstItems.add(objLead);

            OrderItem objLead2 = TestDataFactory.createOrderItem(objOrder.Id);
            objLead2.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objLead2.price_discrepancy_reason__c = Constants.PICKLIST_VALUE_ORDER_ITEM_DISCREPANY_REASON_BULKSWAP;
            objLead2.UnitPrice = 1;
            lstItems.add(objLead2);

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.patient__c = objOrder.patient__c;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.patient__c = objOrder.patient__c;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            insert lstItems;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        Order objOrder = [SELECT Id, validation_reason__c FROM Order WHERE Id = :objOrder.Id];
        System.assertEquals('Price Discrepancy Reason = Bulk swap;More than 1 Device on MDRF', objOrder.validation_reason__c);
    }

    // Test If only Order Items (Product Type = 'Lead') was attached to the submitted Order Record
    // AND NO Asset with Product Type 'Device' OR 'ICD' OR 'Pacemaker' and Status 'Implanted'
    @isTest
    static void testLeadWithNoDevice(){
        init();

        System.runAs(testUser){
            OrderItem objOrderItem = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderItem.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderItem.part_of_system_price__c = true;
            objOrderItem.UnitPrice = 0;
            insert objOrderItem;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }
        assertValidation(Constants.PICKLIST_VALIDATION_REASON_LEAD_WITH_NO_DEVICE);
    }

    @isTest
    static void testDeviceWithOnlyOneLead(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderDevice.part_of_system_price__c = false;
            objOrderDevice.UnitPrice = 2;
            lstOrderItems.add(objOrderDevice);

            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            insert lstOrderItems;

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.patient__c = objOrder.patient__c;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }
        assertValidation(Constants.PICKLIST_VALIDATION_REASON_DEVICE_WITH_ONLY_ONE_LEAD);
    }

    @isTest
    static void testLeadItemAndOneLeadAssetNoDevice(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            insert lstOrderItems;

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            insert prod;

            List<Asset> lstAssetsToInsert = new List<Asset>();
            Asset objAssetLead = TestDataFactory.createAsset(objOrder.AccountId);
            objAssetLead.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAssetLead.Product2Id = prod.Id;
            objAssetLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objAssetLead.patient__c = objOrder.patient__c;
            lstAssetsToInsert.add(objAssetLead);
            insert lstAssetsToInsert;

            objOrderLead.asset__c = objAssetLead.Id;
            update objOrderLead;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }
        // check if DEVICE_WITH_NO_LEADS did not exist in Validation Reason
        assertNotValidationReasons(Constants.PICKLIST_VALIDATION_REASON_DEVICE_WITH_NO_LEADS);
        assertValidation(Constants.PICKLIST_VALIDATION_REASON_LEAD_WITH_NO_DEVICE);
    }

    @isTest
    static void testDeviceWithOneLeadItemAndOneLeadAsset(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_PACEMAKER;
            objOrderDevice.part_of_system_price__c = false;
            objOrderDevice.UnitPrice = 2;
            lstOrderItems.add(objOrderDevice);

            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            insert lstOrderItems;

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            insert prod;

            List<Asset> lstAssetsToInsert = new List<Asset>();
            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.patient__c = objOrder.patient__c;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.Product2Id = prod.Id;
            lstAssetsToInsert.add(objAsset);

            Asset objAssetLead = TestDataFactory.createAsset(objOrder.AccountId);
            objAssetLead.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAssetLead.Product2Id = prod.Id;
            objAssetLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objAssetLead.patient__c = objOrder.patient__c;
            lstAssetsToInsert.add(objAssetLead);
            insert lstAssetsToInsert;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        assertValidation(Constants.PICKLIST_VALIDATION_REASON_NONE);
    }

    @isTest
    static void testSingleLeadDeviceWithOnlyOneLead(){
        init();

        System.runAs(testUser){
            List<OrderItem> lstOrderItems = new List<OrderItem>();
            OrderItem objOrderDevice = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderDevice.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_ICD;
            objOrderDevice.part_of_system_price__c = false;
            objOrderDevice.UnitPrice = 2;
            lstOrderItems.add(objOrderDevice);

            OrderItem objOrderLead = TestDataFactory.createOrderItem(objOrder.Id);
            objOrderLead.product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_LEAD;
            objOrderLead.part_of_system_price__c = true;
            objOrderLead.UnitPrice = 0;
            lstOrderItems.add(objOrderLead);
            insert lstOrderItems;

            objOrderDevice = [SELECT Id, Product2Id FROM OrderItem WHERE Id = :objOrderDevice.Id LIMIT 1];
            Product2 prodOderItem = new Product2();
            prodOderItem.Id = objOrderDevice.Product2Id;
            prodOderItem.sub_group_4__c = 'Single Chamber Pacemakers';
            update prodOderItem;

            Product2 prod = new Product2(Name = 'ICD');
            prod.product_type__c = 'ICD';
            prod.sub_group_4__c = 'Single Chamber Pacemakers';
            insert prod;

            Asset objAsset = TestDataFactory.createAsset(objOrder.AccountId);
            objAsset.order__c = objOrder.Id;
            objAsset.patient__c = objOrder.patient__c;
            objAsset.Status = Constants.IMPLANT_STATUS_IMPLANTED;
            objAsset.Product2Id = prod.Id;
            insert objAsset;

            Test.startTest();
            objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
            update objOrder;
            Test.stopTest();
        }

        assertValidation(Constants.PICKLIST_VALIDATION_REASON_NONE);
    }

    /**
    * Method checks if an Order with out any OrderItems get catched by
    * the validation
    */
    @isTest
    static void testOrderWithoutOrderItem() {
        init();

        try{
            System.runAs(testUser){
                Test.startTest();
                objOrder.Status = Constants.PICKLIST_VALUE_ORDER_STATUS_SUBMITTED_PROCESSING;
                update objOrder;

                System.assert(true, 'This part should not be reached.');

                Test.stopTest();
            }
        }catch(Exception ex){
            System.assert(ex.getMessage().contains(Label.ERR_ORDER_HAS_NO_ORDER_ITEMS), 'Wrong error. Msg: '+ex.getMessage());
        }

        objOrder = [SELECT Id, Status FROM Order WHERE Id = :objOrder.Id LIMIT 1];
        System.assertEquals(Constants.PICKLIST_VALUE_STATUS_NOT_SUBMITTED, objOrder.Status);
    }



    private static void init() {
        testUser = TestDataFactory.createUser(UserInfo.getProfileId());
        testUser.UserRoleId = [SELECT Id FROM UserRole WHERE DeveloperName = : Constants.USER_ROLE_NAME_SO LIMIT 1].Id;
        System.runAs(testUser){
            objAccount = TestDataFactory.createAccount();
            insert objAccount;

            Id orderRtId =  Utility.getRecordTypeId (Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
            objOrder = TestDataFactory.createOrder(objAccount.Id);
            objOrder.Status = Constants.PICKLIST_VALUE_STATUS_NOT_SUBMITTED;
            objOrder.RecordTypeId = orderRtId;
            objOrder.PoNumber = '1234';
            objOrder.validation_reason__c = Constants.PICKLIST_VALIDATION_REASON_NONE;
            insert objOrder;
        }
    }

    private static void assertValidation(String validationReason){
        objOrder = [SELECT Id, OwnerId, validation_reason__c, Status FROM Order WHERE Id = :objOrder.Id LIMIT 1];

        String shouldStatus = OrderValidation.CAS_VALIDATION_VALUES.contains(validationReason) ? Constants.PICKLIST_VALUE_ORDER_STATUS_PENDING_REVIEW : Constants.PICKLIST_VALUE_ORDER_STATUS_PENDING_SAP;

        System.debug('ValidationReason '+objOrder.validation_reason__c + ' / Status '+objOrder.Status);
        System.assert(objOrder.validation_reason__c.contains(validationReason), 'Order validation reasons: '+objOrder.validation_reason__c);
        System.assertEquals(shouldStatus , objOrder.Status);
    }

    private static void assertNotValidationReasons(String validationReason){
        objOrder = [SELECT Id, OwnerId, validation_reason__c, Status FROM Order WHERE Id = :objOrder.Id LIMIT 1];

        String shouldStatus = OrderValidation.CAS_VALIDATION_VALUES.contains(validationReason) ? Constants.PICKLIST_VALUE_ORDER_STATUS_PENDING_REVIEW : Constants.PICKLIST_VALUE_ORDER_STATUS_PENDING_SAP;

        System.debug('ValidationReason '+objOrder.validation_reason__c + ' / Status '+objOrder.Status);
        System.assert(!objOrder.validation_reason__c.contains(validationReason), 'Validation Reason "'+ validationReason +'" should not exist; Order validation reasons: '+objOrder.validation_reason__c);
        System.assertEquals(shouldStatus , objOrder.Status);
    }
}