objects/Asset.object
<CustomObject>
    <fields>
        <fullName>model_no__c</fullName>
        <description>Unique numeric identifier of the product</description>
        <inlineHelpText>Unique numeric identifier of the product</inlineHelpText>
        <label>Model No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>stock_type__c</fullName>
        <description>Stock Location of the asset.</description>
        <label>Stock Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B</fullName>
                    <label>Bulk</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Consignment Stock</label>
                </value>
                <value>
                    <fullName>L</fullName>
                    <label>Loaned Stock</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Trunk Stock</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>num_cm_products__c</fullName>
        <label>Number of Cardio Messenger Products</label>
        <summaryFilterItems>
            <field>OrderItem.product_type__c</field>
            <operation>equals</operation>
            <value>Cardio Messenger</value>
        </summaryFilterItems>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>num_hm_products__c</fullName>
        <label>Number of Home Monitoring Products</label>
        <summaryFilterItems>
            <field>OrderItem.model_no__c</field>
            <operation>equals</operation>
            <value>358364</value>
        </summaryFilterItems>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>model_no__c</fullName>
        <label>Model No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>stock_type__c</fullName>
        <description>Stock Location of the asset.</description>
        <label>Stock Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B</fullName>
                    <label>Bulk</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Consignment Stock</label>
                </value>
                <value>
                    <fullName>L</fullName>
                    <label>Loaned Stock</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Trunk Stock</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>model_no__c</fullName>
        <description>Formula-field referencing the product</description>
        <formula>Product2.sap_model_no__c</formula>
        <label>Model No</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>sap_model_no__c</fullName>
        <externalId>true</externalId>
        <label>SAP Model No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrderItemHandler.cls
/* 2018-07-24 Florian Heer <f.heer@conciscon.de>
 * Handles Trigger events for OrderItems.
 *
 * Currently this only adds a Home Monitoring Service if a Cardio Messenger is added.
 */
public class OrderItemHandler {

    public static List<Product2> getHomeMonitoringServiceProducts() {
        return [SELECT Id, sap_model_no__c FROM Product2 WHERE ExternalId = :Constants.HOME_MONITORING_SERVICE_SAP_EXTERNAL_ID];
    }
    
    /* Updates all Orders to include a Home Monitoring Service if there is not already one present.
     */
    public static void afterInsert(List<OrderItem> newItems) {
        List<OrderItem> toBeConsidered = new List<OrderItem>();
        for(OrderItem oi : newItems) {
            if(Utility.getValidationCategory(oi.product_type__c) == Constants.VALI_CAT_CARDIO_MESSENGER 
               && (oi.asset__c == null || oi.asset__r.stock_type__c != 'B')) {
                toBeConsidered.add(oi);
            }
        }
        
        Set<Id> orderIDsToProcess = getOrderIDsForProductType(toBeConsidered, Constants.PICKLIST_VALUE_PRODUCT_TYPE_CARDIO_MESSENGER);
        
        if(orderIDsToProcess.size() > 0) {

            List<Product2> hmProducts = getHomeMonitoringServiceProducts();
            if(hmProducts.size() > 0) {
                List<Order> ordersToProcess = [SELECT Id, num_hm_products__c, CurrencyIsoCode, Pricebook2Id
                                               FROM Order WHERE Id IN :orderIDsToProcess AND num_hm_products__c = 0
                                               ];
                List<OrderItem> orderItemsToAdd = new List<OrderItem>();
                
                Map<Id, PricebookEntry> pb2pbe = new Map<Id, PricebookEntry>();
                List<Id> pricebookIds = new List<Id>();
                List<String> currencies = new List<String>();
                
                for(Order o : ordersToProcess) {
                    pricebookIds.add(o.Pricebook2Id);
                    currencies.add(o.CurrencyIsoCode);
                }
                List<PricebookEntry> pbes = [SELECT Id, UnitPrice, CurrencyIsoCode, Pricebook2Id 
                                             FROM PricebookEntry WHERE Product2Id = :hmProducts[0].Id
                                             AND CurrencyIsoCode IN :currencies
                                             AND IsActive = true
                                             AND Pricebook2Id IN :pricebookIds];
                
                
                
                
                for(Order o:ordersToProcess) {
                    PricebookEntry usablePBE = null;
                    for(PricebookEntry pbe : pbes) {
                        if(pbe.CurrencyIsoCode == o.CurrencyIsoCode && pbe.Pricebook2Id == o.Pricebook2Id) {
                            usablePBE = pbe;
                        }
                    }
                    if(usablePBE != null) {
                        orderItemsToAdd.add (new OrderItem (OrderId = o.Id,
                                                            PricebookEntryId = usablePBE.Id
                                                            , Quantity = 1
                                                            , UnitPrice = usablePBE.UnitPrice
                                                            , model_no__c = hmProducts[0].sap_model_no__c
                                                            , product_type__c = Constants.PICKLIST_VALUE_PRODUCT_TYPE_HOME_MONITORING_SERVICE
                                                           ));
                    }
                    else {
                        // TBD: what happens if there is no home monitoring in this Pricebook?
                        System.debug('Add Home Monitoring Service: Cannot find Home Monitoring Service in the current Pricebook.');
                        
                    }
                }
                if(orderItemsToAdd.size() > 0) {
                    insert orderItemsToAdd;
                }
            }
            else {
                // TBD: what happens if there is no home monitoring in the products?
                System.debug('Add Home Monitoring Service: Cannot find Home Monitoring Service in the products');
            }
        }
    }

    public static Set<Id> getOrderIDsForProductType(List<OrderItem> ourItems, String productType) {
        Set<Id> retval = new Set<Id>();
        for(OrderItem oi : ourItems) {
            if(Utility.getValidationCategory(oi.product_type__c) == Constants.VALI_CAT_CARDIO_MESSENGER) {
                retval.add(oi.OrderId);
            }
        }
        return retval;

    }
    
    /* Updates all Orders to remove a Home Monitoring Service if there is no Cardio Messenger left.
     */
    public static void afterDelete(List<OrderItem> oldItems) {
        Set<Id> orderIDsToProcess = getOrderIDsForProductType(oldItems, Constants.PICKLIST_VALUE_PRODUCT_TYPE_CARDIO_MESSENGER);
        
        if(orderIDsToProcess.size() > 0) {

            List<Product2> hmProducts = getHomeMonitoringServiceProducts();
            if(hmProducts.size() > 0) {
                List<Order> ordersToProcess = [SELECT Id, num_hm_products__c, num_cm_products__c, CurrencyIsoCode, Pricebook2Id
                                               FROM Order WHERE Id IN :orderIDsToProcess AND num_hm_products__c > 0
                                              ];
                List<OrderItem> orderItemsToDelete = new List<OrderItem>();
                List<Id> orderIDs = new List<Id>();
                for(Order o:ordersToProcess) {
                    if(o.num_hm_products__c > 0 && o.num_cm_products__c == 1) {
                        orderIDs.add(o.Id);
                    }
                }
                
                if(orderIDs.size() > 0) {
                    orderItemsToDelete.addAll([SELECT Id FROM OrderItem WHERE OrderId IN :orderIDs 
                                               AND model_no__c = :Constants.HOME_MONITORING_SERVICE_SAP_MODEL]);
                }
                
                if(orderItemsToDelete.size() > 0) {
                    delete orderItemsToDelete;
                }
            }
            else {
                // TBD: what happens if there is no home monitoring in the products?
                System.debug('Add Home Monitoring Service: Cannot find Home Monitoring Service in the products');
            }
        }
        
    }

}