objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Lead_Tip_Location__c</fullName>
        <label>Lead Tip Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RV_APEX</fullName>
                    <label>RV, Apex</label>
                </value>
                <value>
                    <fullName>RV_SEPTUM</fullName>
                    <label>RV, Septum</label>
                </value>
                <value>
                    <fullName>RV_HIS</fullName>
                    <label>RV, HISbundle</label>
                </value>
                <value>
                    <fullName>RV_OT</fullName>
                    <label>RV, OutflowTract</label>
                </value>
                <value>
                    <fullName>RV_ANT</fullName>
                    <label>RV, Anterior</label>
                </value>
                <value>
                    <fullName>RV_LAT</fullName>
                    <label>RV, Lateral</label>
                </value>
                <value>
                    <fullName>RV_EPICARD</fullName>
                    <label>RV, Epicardial</label>
                </value>
                <value>
                    <fullName>RV_ANY</fullName>
                    <label>RV / No details</label>
                </value>
                <value>
                    <fullName>RA_ANT</fullName>
                    <label>RA, Anterior</label>
                </value>
                <value>
                    <fullName>RA_FWALL</fullName>
                    <label>RA, FreeWall</label>
                </value>
                <value>
                    <fullName>RA_SEPTUM</fullName>
                    <label>RA, Septum</label>
                </value>
                <value>
                    <fullName>RA_ANY</fullName>
                    <label>RA / No details</label>
                </value>
                <value>
                    <fullName>RA_HIS</fullName>
                    <label>RA, HISbundle</label>
                </value>
                <value>
                    <fullName>LV_APEX</fullName>
                    <label>LV, Apex</label>
                </value>
                <value>
                    <fullName>LV_LAT</fullName>
                    <label>LV, Lateral</label>
                </value>
                <value>
                    <fullName>LV_POST</fullName>
                    <label>LV, Posterior</label>
                </value>
                <value>
                    <fullName>LV_SEPTUM</fullName>
                    <label>LV, Septum</label>
                </value>
                <value>
                    <fullName>LV_EPICARD</fullName>
                    <label>LV, Epicardial</label>
                </value>
                <value>
                    <fullName>LV_ANY</fullName>
                    <label>LV / No details</label>
                </value>
                <value>
                    <fullName>CS_POST</fullName>
                    <label>Coronary Sinus, Posterior</label>
                </value>
                <value>
                    <fullName>CS_POST_LAT</fullName>
                    <label>Coronary Sinus, Posterior, Lateral</label>
                </value>
                <value>
                    <fullName>CS_LAT</fullName>
                    <label>Coronary Sinus, Lateral</label>
                </value>
                <value>
                    <fullName>CS_ANT</fullName>
                    <label>Coronary Sinus, Anterior</label>
                </value>
                <value>
                    <fullName>CS_ANT_LAT</fullName>
                    <label>Coronary Sinus, Anterior, Lateral</label>
                </value>
                <value>
                    <fullName>CS_ANY</fullName>
                    <label>Coronary Sinus / No details</label>
                </value>
                <value>
                    <fullName>CV_GREAT</fullName>
                    <label>Cardiac Vein, Great</label>
                </value>
                <value>
                    <fullName>CV_MID</fullName>
                    <label>Cardiac Vein, Middle</label>
                </value>
                <value>
                    <fullName>CV_POST</fullName>
                    <label>Cardiac Vein, Posterior</label>
                </value>
                <value>
                    <fullName>CV_POST_LAT</fullName>
                    <label>Cardiac Vein, Posterior, Lateral</label>
                </value>
                <value>
                    <fullName>CV_LAT</fullName>
                    <label>Cardiac Vein, Lateral</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UDI__c</fullName>
        <description>Unique Device Identification made up of serial/batch number, UBD, and EAN. Required by FDA</description>
        <label>UDI</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>batch_no__c</fullName>
        <description>Unique alphanumeric identifier of a lot of products</description>
        <label>Batch No.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>explanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Explanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Explanted_Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets (Implanting Physician)</relationshipLabel>
        <relationshipName>Assets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>model_no__c</fullName>
        <description>Unique numeric identifier of the product</description>
        <inlineHelpText>Unique numeric identifier of the product</inlineHelpText>
        <label>Model No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linkage to the  Order record</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>following_physican__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Following Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Following Physican)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>batch_no__c</fullName>
        <description>Unique alphanumeric identifier of a lot of products</description>
        <label>Batch No.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>model_no__c</fullName>
        <label>Model No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>part_of_system_price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Asset was part of an reduced system pricing.</description>
        <label>Part of System Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <description>When the user adds a competitor product to a patient they must select the Product type from this picklist.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>product_type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>udi__c</fullName>
        <description>Unique Device Identification made up of serial/batch number, UBD, and EAN. Required by FDA</description>
        <label>UDI</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/product_type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accessory</fullName>
    </customValue>
    <customValue>
        <fullName>Adapter</fullName>
    </customValue>
    <customValue>
        <fullName>Cardio Messenger</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-D</fullName>
    </customValue>
    <customValue>
        <fullName>CRT-P</fullName>
    </customValue>
    <customValue>
        <fullName>Home Monitoring Service</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Loop Recorder</fullName>
    </customValue>
    <customValue>
        <fullName>Pacemaker</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
        <isActive>false</isActive>
        <label>Raw Material</label>
    </customValue>
    <customValue>
        <fullName>Guide Wire</fullName>
        <isActive>false</isActive>
        <label>Guide Wire</label>
    </customValue>
    <customValue>
        <fullName>Device</fullName>
        <isActive>false</isActive>
        <label>Device</label>
    </customValue>
    <customValue>
        <fullName>Demo/Documents</fullName>
        <isActive>false</isActive>
        <label>Demo/Documents</label>
    </customValue>
    <customValue>
        <fullName>Competitor Product</fullName>
        <isActive>false</isActive>
        <label>Competitor Product</label>
    </customValue>
    <customValue>
        <fullName>Catheter</fullName>
        <isActive>false</isActive>
        <label>Catheter</label>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

classes/OrdersReview.cls
/**
* @author:			arwe
*					T-Systems Multimedia Solutions GmbH
*					Riesaer Strasse 5,
*					01129 Dresden
*					www.t-systems-mms.com
*
* @description      
*                  
*
* @date             15.10.2018
* 
*/

public with sharing class OrdersReview {

    private static final Id idRecordTypeMdrfOrder = Utility.getRecordTypeId(Order.SObjectType, Constants.RECORD_TYPE_NAME_ORDER_MDRF);
    public Map<Id, Account> accountMap;
    public Map<Id, Contact> contactMap;

    private Map<Id, List<OrderItem>> orderOrderItemMap = new Map<Id, List<OrderItem>>();
    private Map<Id, List<Asset>> orderAssetMap = new Map<Id, List<Asset>>();

    public Map<Id, List<OrderItem>> getOrderOrderItemMap(){
        return this.orderOrderItemMap;
    }

    public Map<Id, List<Asset>> getOrderAssetMap(){
        return this.orderAssetMap;
    }

    public OrdersReview(List<Order> newOrderLis) {
        accountMap = new Map<Id, Account>();
        contactMap = new Map<Id, Contact>();
        setData(newOrderLis);
    }

    private void setData(List<Order> newOrderList) {

        Set<Id> processedOrdersId = new Set<Id>();
        Set<Id> setIdPatients = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();

        for (Order objOrder : newOrderList) {
            if (idRecordTypeMdrfOrder == objOrder.RecordTypeId) {
                if (!Trigger.isInsert) {
                    processedOrdersId.add(objOrder.Id);
                }
                setIdPatients.add(objOrder.patient__c);
                accountIds.add(objOrder.AccountId);
                contactIds.addAll(new Set<Id>{
                        objOrder.implanting_physician__c, objOrder.patient__c, objOrder.following_physican__c
                });
            }
        }
        accountMap = getAccounts(accountIds);
        contactMap = OrderHelper.getContactMap(contactIds);
        if (!processedOrdersId.isEmpty()) {
            orderOrderItemMap = OrderHelper.getOrderItemsFromOrder(processedOrdersId);
            orderAssetMap = getAssetsFromPatient(setIdPatients);
        }

    }

    /**
     *  Selects the account id and the ShippingState for the given account ids
     *
     * @param	setAccountIds, Ids from the accounts, which should be selected
     * @return	Map<Id, Account>, the selected accounts mapped by their Id
     */
    private static Map<Id, Account> getAccounts(Set<Id> setAccountIds) {
        return new Map<Id, Account>([
                SELECT Id, ShippingState
                        FROM Account
                        WHERE Id IN :setAccountIds
        ]);
    }

    /**
    * Select all the Asset information related to the given patient
    *
    * @param	setPatientIds, Ids from the patients, for which the assets should be selected#
    * @return	Map<Id, List<Asset>>, a Map with a list of all assets, mapped by their patient id
    */
    private static Map<Id, List<Asset>> getAssetsFromPatient(Set<Id> setPatientIds) {
        Map<Id, List<Asset>> mapAssetsByPatient = new Map<Id, List<Asset>>();
        for(Asset objAsset :  [SELECT Id,
                patient__c,
                part_of_system_price__c,
                Price,
                order__c,
                LocationId,
                Location.Name,
                product_type__c,
                Status,
                Lead_Tip_Location__c,
                UDI__c,
                SerialNumber,
                batch_no__c,
                model_no__c,
                explanting_physician__c,
                explanting_physician__r.Name,
                explanting_physician__r.Phone,
                explanting_physician__r.MailingAddress
                FROM Asset
                WHERE patient__c IN :setPatientIds]) {

            if(mapAssetsByPatient.isEmpty() || !mapAssetsByPatient.containsKey(objAsset.patient__c)) {
                mapAssetsByPatient.put(objAsset.patient__c, new List<Asset>{objAsset});
            } else {
                mapAssetsByPatient.get(objAsset.patient__c).add(objAsset);
            }
        }
        return mapAssetsByPatient;
    }

}