objects/Auto_Running_Numbers__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store the latest running RP, CI and MDR number</description>
    <fields>
        <fullName>CI_Number__c</fullName>
        <description>Stores recent number that is to be assigned to CI Number</description>
        <inlineHelpText>Store recent number that is to be assigned to CI number</inlineHelpText>
        <label>CI Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDR_Number__c</fullName>
        <description>Stores recent number that is to be assigned to MDR number</description>
        <inlineHelpText>Store recent number that is to be assigned to RP number</inlineHelpText>
        <label>MDR Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RP_Number__c</fullName>
        <description>Stores recent number that is to be assigned to RP number</description>
        <inlineHelpText>Store recent number that is to be assigned to RP number</inlineHelpText>
        <label>RP Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Running_Number_Year__c</fullName>
        <description>Store the year to which the current running numbers in the custom settings belong</description>
        <inlineHelpText>Store the year to which the current running numbers in the custom settings belong</inlineHelpText>
        <label>Running Number Year</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Auto Running Numbers</label>
</CustomObject>

objects/complaint__c.object
<CustomObject>
    <description>Medical Device Complaint used for reporting issues with patients that have a Biotronik device implanted.</description>
    <fields>
        <fullName>RP_Number__c</fullName>
        <description>Returned Product Number RP-YEAR-XXXXX
Annually the running number sequence starts from 00001. SFDC automatically generates next number in sequence.</description>
        <label>RP Number</label>
        <length>14</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ci_number__c</fullName>
        <description>Complaint Investigation Number CI-YEAR-XXXXX
Annually the running number sequence starts from 00001.  SFDC automatically generates next number in sequence.</description>
        <label>CI Number</label>
        <length>14</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>date_product_received_by_mdr_team__c</fullName>
        <label>Date Product Received by MDR Team</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>initial_approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The initial approver for review.</inlineHelpText>
        <label>Initial Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Complaints_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_decision__c</fullName>
        <description>The outcome of the decision tree of the MDR Determination Guide will be auto populated here.</description>
        <label>MDR Decision</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mdr_number__c</fullName>
        <description>Medical Device Reporting Number
1028232-YEAR-xxxxx
Annually the running number sequence starts from 00001. SFDC automatically generates next number in sequence.</description>
        <label>MDR Number</label>
        <length>23</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GenerateAutoNumbersControllerTest.cls
/**
 * Test Class for GenerateAutoNumbersController
 * 
 * @author            SNPA
 * @created           2018-04-26
 * @systemLayer       Test Class 
 *  
 */
@isTest
private class GenerateAutoNumbersControllerTest {
    
     /** 
     * Method checks if correct RP Number is assigned to complaint 
     * @author     SNPA 
     */
	static testMethod void testRPNumberAssignment() {
    	
        case objCase = TestDataFactory.createCase();
        insert objCase;
        
        complaint__c objComplaint = TestDataFactory.createComplaint(objCase.id);
        objComplaint.initial_approver__c = UserInfo.getUserId();
        objComplaint.date_product_received_by_mdr_team__c = system.today();
        insert objComplaint;
        
        Test.startTest();
        	GenerateAutoNumbersController.assignRpNumber(objComplaint.id);        
        Test.stopTest();
        
        objComplaint = [SELECT id, rp_number__c FROM complaint__c WHERE id = :objComplaint.id];
        system.assertEquals(GenerateAutoNumbersController.RP_PREFIX + System.Today().year() + '-00001' , objComplaint.rp_number__c);
    }
    
    /** 
     * Method checks if correct CI Number is assigned to complaint
     * @author     SNPA 
     */
    static testMethod void testCINumberAssignment() {
    	
        case objCase = TestDataFactory.createCase();
        insert objCase;
        
        complaint__c objComplaint = TestDataFactory.createComplaint(objCase.id);
        objComplaint.initial_approver__c = UserInfo.getUserId();
        objComplaint.date_product_received_by_mdr_team__c = system.today();
        insert objComplaint;        
         
        complaint__c objComplaint2 = TestDataFactory.createComplaint(objCase.id);
        objComplaint.initial_approver__c = UserInfo.getUserId();
        objComplaint.date_product_received_by_mdr_team__c = system.today();
        insert objComplaint2;
        
        Test.startTest();
        	GenerateAutoNumbersController.assignCiNumber(objComplaint.id);        	
        Test.stopTest();
                
        objComplaint = [SELECT id, ci_number__c FROM complaint__c WHERE id = :objComplaint.id];
        system.assertEquals(GenerateAutoNumbersController.CI_PREFIX + System.Today().year() + '-00001' , objComplaint.ci_number__c);        
    }

    /** 
     * Method checks if correct MDR Number is assigned to complaint
     * @author     SNPA 
     */
    static testMethod void testMDRNumberAssignment() {
    	
        case objCase = TestDataFactory.createCase();
        insert objCase;
        
        complaint__c objComplaint = TestDataFactory.createComplaint(objCase.id);
        objComplaint.initial_approver__c = UserInfo.getUserId();
        objComplaint.mdr_decision__c = 'Test MDR decision';
        insert objComplaint;

        GenerateAutoNumbersController.assignCiNumber(objComplaint.id);
        GenerateAutoNumbersController.assignMdrNumber(objComplaint.id);
        
        objComplaint = [SELECT id, mdr_number__c FROM complaint__c WHERE id = :objComplaint.id];
        system.assertEquals(GenerateAutoNumbersController.MDR_PREFIX + System.Today().year() + '-00001' , objComplaint.mdr_number__c);
    }
    
    /** 
     * Method checks if correct new Numbers are assigned when Year is changed
     * @author     SNPA 
     */
    static testMethod void testYearChange() {
    	
        case objCase = TestDataFactory.createCase();
        insert objCase;
        
        auto_running_numbers__c objNumber = TestDataFactory.createAutoNumberSetting(2017);
        insert objNumber;
        
        complaint__c objComplaint = TestDataFactory.createComplaint(objCase.id);
        objComplaint.mdr_decision__c = 'Test MDR decision';
        objComplaint.initial_approver__c = UserInfo.getUserId();
        objComplaint.date_product_received_by_mdr_team__c = system.today();
        insert objComplaint;

        GenerateAutoNumbersController.assignCiNumber(objComplaint.id);
        GenerateAutoNumbersController.assignMdrNumber(objComplaint.id);
        
        objComplaint = [SELECT id, ci_number__c, mdr_number__c FROM complaint__c WHERE id = :objComplaint.id];
        system.assertEquals(GenerateAutoNumbersController.MDR_PREFIX + System.Today().year() + '-00001' , objComplaint.mdr_number__c);
        system.assertEquals(GenerateAutoNumbersController.CI_PREFIX + System.Today().year() + '-00001' , objComplaint.ci_number__c);
        
        GenerateAutoNumbersController.assignRpNumber(objComplaint.id);        
        
        objComplaint = [SELECT id, rp_number__c FROM complaint__c WHERE id = :objComplaint.id];
        system.assertEquals(GenerateAutoNumbersController.RP_PREFIX  + System.Today().year() + '-00001' , objComplaint.rp_number__c);
        
        objNumber =  [SELECT ci_number__c, 
                      		 mdr_number__c, 
                      		 rp_number__c, 
                      		 running_number_year__c  
                      	FROM auto_running_numbers__c WHERE id = :objNumber.id];
        system.assert(objNumber.ci_number__c == 2 && 
                     objNumber.mdr_number__c == 2 &&
                     objNumber.rp_number__c == 2 &&
                     objNumber.running_number_year__c == 2018 );        
        
    }
}