objects/complaint__c.object
<CustomObject>
    <description>Medical Device Complaint used for reporting issues with patients that have a Biotronik device implanted.</description>
    <fields>
        <fullName>approval_status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending Peer Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>SubmitToEMDRPending</fullName>
                    <label>Submitted to EMDR: Pending</label>
                </value>
                <value>
                    <fullName>SubmitToEMDROK</fullName>
                    <label>Submitted to EMDR: Transmit OK</label>
                </value>
                <value>
                    <fullName>SubmitToEMDRFail</fullName>
                    <label>Submitted to EMDR: Transmit Failed</label>
                </value>
                <value>
                    <fullName>FDAResponsePass</fullName>
                    <label>FDA Response: Pass</label>
                </value>
                <value>
                    <fullName>FDAResponseFail</fullName>
                    <label>FDA Response: Fail</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/X5500_EMDRConfig__mdt.object
<CustomObject>
    <description>Holds run time configs for complaints related applications.</description>
    <fields>
        <fullName>status_submit_to_emdr_ready__c</fullName>
        <description>Status set in complaint__c.approval_process__c for records that are ready to submit to emdr system.</description>
        <label>Complaint Status: Ready to Submit</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>EMDR Runtime Configuration</label>
    <pluralLabel>EMDR Runtime Configurations</pluralLabel>
</CustomObject>

classes/X5500_EMDR_Submit_Callout_Mock.cls
/**
Simulate return from remote web service for code coverage
@author	Mike Tribble
@revised 06/20/18 created
*/
@isTest
global class X5500_EMDR_Submit_Callout_Mock implements WebServiceMock {
   global void doInvoke(
		Object stub,
		Object request,
		Map<String, Object> response,
		String endpoint,
		String soapAction,
		String requestName,
		String responseNS,
		String responseName,
		String responseType) {

		X5500_EMDRConfig__mdt config = [SELECT x.Id,
			x.status_submit_to_emdr_ready__c
			From X5500_EMDRConfig__mdt x
			WHERE x.DeveloperName =: 'EMDR_Config'];

		List<complaint__c> comList = [SELECT Id
			FROM complaint__c
			WHERE approval_status__c =: config.status_submit_to_emdr_ready__c];

        // mock response to return when testing
		X5500_EMDR_Submit_Callout.Resp_Message response_x = new X5500_EMDR_Submit_Callout.Resp_Message();
		response_x.rows = new List<X5500_EMDR_Submit_Callout.resp_element>();
		//set up pretend responses to correspond to the test records inserted
		Integer i = 0;
		for (complaint__c com : comList) {
			i++;
			X5500_EMDR_Submit_Callout.resp_element re = new X5500_EMDR_Submit_Callout.resp_element();
			re.emdr_recordid=com.Id;
			//fail every other message
			re.message = (math.mod(i,2)==1 ? 'success:recordid='+i : 'fail:because why not');
			response_x.rows.add(re);
		}
		response.put('response_x', response_x);
	}
}