objects/Contact.object
<CustomObject>
    <fields>
        <fullName>following_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the physician contact</description>
        <label>Following Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Patients Following</relationshipLabel>
        <relationshipName>ContactFollowingPhysician</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Referring Physician)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>following_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>following physician CONTACT record assigned by SFDC</description>
        <label>Following Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Following Physician)</relationshipLabel>
        <relationshipName>Implants_Procedures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>implanting physician CONTACT record assigned by SFDC
removed Implanting Physician: Account: Account ID = Work Order: Account ID filter criteria</description>
        <inlineHelpText>implanting physician CONTACT record assigned by SFDC</inlineHelpText>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <inlineHelpText>Physician who referred the patient</inlineHelpText>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Referring Physician)</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SendEmailController.cls
/* 
 *  Description  - Class to get Contact and User Information
 *  Created Date - 4/2/2018
 *  Created by   - susi
 */
public with sharing class SendEmailController {
    /* 
     *  Description  - Method that returns contact and User Info. 
     *  @param    recId    Id of contact record
     *  @return   wrapper  Contact and User Info wrapped together 
     */
    @AuraEnabled
    public static wrapper getRecords(String recId) {
        wrapper wrp;
        try {
            User usr = [SELECT Id, Email 
                        FROM User 
                        WHERE id =: UserInfo.getUserId()];
            Contact con = [SELECT Id, Email 
                            FROM Contact 
                            WHERE id =: recId];
            wrp = new wrapper(usr, con);
            
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return wrp;
    }
    
    /*
     * Wrapper class to bind User and contact information together
     */
    public class wrapper {
        @testVisible @AuraEnabled User u {get;set;}
        @testVisible @AuraEnabled Contact c {get;set;}
        public wrapper(User usr, Contact con) {
            u = usr;
            c= con;
        }
    }
    
    /* 
     *  Description  - Method that returns lookupfields from Workorder AND Order. 
     *  @param    recId    Id of Workorder/Order record
     *  @return   List<sObject>    List of workorder/order records
     */
    @AuraEnabled
    public static List<KeyValueWrapper> getlookupFieldValues(String recId) {
        sObject sObj;
        Map<String, String> fieldsMap;
        Id recordId = (Id)recId;
        List<KeyValueWrapper> wrapperList = new List<KeyValueWrapper>();  
        String objName = recordId.getSObjectType().getDescribe().getName();
        Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap();
        if(objName.equalsIgnoreCase('Workorder')) {
            fieldsMap = new Map<String, String>{'id' => 'id', 
                								'ContactId' => 'Contact.name', 
                								'following_physician__c' => 'following_physician__r.name',
                								'implanting_physician__c' => 'implanting_physician__r.name', 
                								'patient__c' => 'patient__r.Name',
                								'referring_physician__c' => 'referring_physician__r.name'
                                               };
        } else {
            fieldsMap = new Map<String, String>{'id' => 'id',  
                								'BillToContactId' => 'BillToContact.name', 
                                                'CustomerAuthorizedById' => 'CustomerAuthorizedBy.name',
                        						'patient__c' => 'patient__r.name',
                								'referring_physician__c' => 'referring_physician__r.name',
                        						'ShipToContactId' => 'ShipToContact.name'
        									   };
        }
        Set<String> fields = new Set<String>();
        fields.addAll(fieldsMap.keySet());
        fields.addAll(fieldsMap.values());
        List<String> strList = new List<String>(fields);
        String queryString = 'SELECT ' +  String.join(strList, ', ') + ' FROM ' + objName + ' WHERE Id =: recId';
        sObj = database.query(queryString);
        for(String key : fieldsMap.keySet()) {
            if (fieldsMap.get(key) != null && sObj.get(key) != null && !key.equalsIgnoreCase('Id')) {
                List<String> tempList = String.valueOf(fieldsMap.get(key)).split('\\.');
                if(tempList.size() > 1)
                	wrapperList.add(new KeyValueWrapper(key, (String)sObj.get(key), (String)sObj.getsObject(tempList[0]).get(tempList[1]), objectFields.get(key).getDescribe().getlabel()));
            }  
        }
        return wrapperList;        
    } 
    
    /*
     * Wrapper class to bind User and contact information together
     */
    public class KeyValueWrapper {
        @testVisible @AuraEnabled String key {get;set;}
        @testVisible @AuraEnabled String Id {get;set;}
        @testVisible @AuraEnabled String val {get;set;}
        @testVisible @AuraEnabled String label {get;set;}
        public KeyValueWrapper(String keyItem, String recId, String nameValue, String lbl) {
            key = keyItem;
            Id = recId;
            val = nameValue;
            label = lbl;
        }
    }   
}