objects/Contact.object
<CustomObject>
    <fields>
        <fullName>declined_to_provide_phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>declined_to_provide_ssn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Declined to Provide SSN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>following_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the physician contact</description>
        <label>Following Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Patients Following</relationshipLabel>
        <relationshipName>ContactFollowingPhysician</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>trig_dob__c</fullName>
        <description>This field will be used during the matching rule, as we can not create a matching rule based on the date of birth, this filed will be filled with a trigger and used it as Date of birth then.</description>
        <label>Trig_DOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestPatient.cls
@isTest

public class TestPatient {
    @isTest static void TestInsertNewPatient(){
        RecordType rt = [SELECT id, name FROM RecordType where name = 'Physician'];
        Contact contph = new Contact(FirstName='Phy', LastName='Ba', Birthdate = Date.today()-2, sap_company_code__c = '5500',
                                   recordTypeId=rt.id, MailingCity = 'Dresden', MailingStreet = 'Res', MailingPostalCode = '11090',
                                   MailingCountryCode ='US',MailingStateCode='LA'
                 
                                  );
        insert contph;
        
        RecordType rtt = [SELECT id, name FROM RecordType where name = 'Patient'];
        Contact cont = new Contact(FirstName='Emna', LastName='Masmoudi', Birthdate = Date.today()-2, sap_company_code__c = '5500',
                                   recordTypeId=rtt.id, MailingCity = 'Dresden', MailingStreet = 'Res', MailingPostalCode = '11090',
                                   MailingCountryCode ='US',MailingStateCode='LA',
                                   declined_to_provide_phone__c = True,
                                   declined_to_provide_ssn__c = True,
                                   following_physician__c = contph.Id
                                  );
        insert cont;
        
        Test.startTest();
        String dateOfBirth = [SELECT Id,trig_dob__c From Contact where Id =:cont.Id ].trig_dob__c;
        System.assertEquals(dateOfBirth, string.ValueOf(Date.today()-2));
        Test.stopTest();
        

    }
}