objects/Order.object
<CustomObject>
    <fields>
        <fullName>brady_tachy_syndrome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Brady/Tachy Syndrome</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>chf__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>donation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Donation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>mi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>one_hb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1° HB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Patient)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Referring Physician)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_for_credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep for Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>brady_tachy_syndrome__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Brady/Tachy Syndrome</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>chf__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>mi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>one_hb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1° HB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Patient record</description>
        <inlineHelpText>Link to Patient record</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>notEqual</operation>
                <value>Deceased</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Patient)</relationshipLabel>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>referring_physician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physician who referred the patient</description>
        <inlineHelpText>Physician who referred the patient</inlineHelpText>
        <label>Referring Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Referring Physician)</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <inlineHelpText>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</inlineHelpText>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_for_credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for sales rep who will receive credit for the sale.</description>
        <inlineHelpText>Identifier for sales rep who will receive credit for the sale.</inlineHelpText>
        <label>Rep for Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sap_company_code__c</fullName>
        <description>All org units in SAP are uniquely identified with a company name and a company code with 4 digits, see API-Names.</description>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company_Code</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WorkOrderToOrderConverter.cls
public class WorkOrderToOrderConverter {
    private static final String DEFAULT_ORDER_STATUS = 'Not Submitted';
    
    public static Order convertToOrder(WorkOrder objWorkOrder){
        Order orderNew = new Order();
        
        orderNew.AccountId                  = objWorkOrder.AccountId;
        orderNew.BillingCity                = objWorkOrder.City;
        orderNew.BillingCountry             = objWorkOrder.Country;
        orderNew.BillingPostalCode          = objWorkOrder.PostalCode;
        orderNew.BillingState               = objWorkOrder.State;
        orderNew.BillingStreet              = objWorkOrder.Street;
        orderNew.brady_tachy_syndrome__c    = objWorkOrder.brady_tachy_syndrome__c;
        
        orderNew.chf__c             = objWorkOrder.chf__c;
        //SAFBIO-1890 orderNew.donation__c        = objWorkOrder.donation__c;
        
        Datetime dtEndDate = objWorkOrder.EndDate;
        orderNew.EndDate            = date.newinstance(dtEndDate.year(), dtEndDate.month(), dtEndDate.day()); 
        orderNew.Status             = DEFAULT_ORDER_STATUS;
        orderNew.mi__c              = objWorkOrder.mi__c;
        orderNew.one_hb__c          = objWorkOrder.one_hb__c;
        
        orderNew.referring_physician__c = objWorkOrder.referring_physician__c;
        orderNew.rep_at_implant__c  = objWorkOrder.rep_at_implant__c;
        orderNew.rep_for_credit__c  = objWorkOrder.rep_for_credit__c;
        //orderNew.sap_company_code__c = objWorkOrder.sap_company_code__c;
        
        orderNew.patient__c         = objWorkOrder.patient__c;
        orderNew.Pricebook2Id       = objWorkOrder.Pricebook2Id;    
        
        return orderNew;
    }
    
    public static List<Order> convertToOrder(List<WorkOrder> lstWorkOrder){
        List<Order> lstNewOrder = new List<Order>();
        
        for(WorkOrder wo :lstWorkOrder){
            lstNewOrder.add(convertToOrder(wo));
        }
        
        return lstNewOrder;
    }
}