objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that no BIOTRONIK representative was present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>rep_at_implant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</description>
        <inlineHelpText>Identifier for the BIOTRONIK representative (Sales Rep, FCS) CONTACT record in attendance at the implant</inlineHelpText>
        <label>Rep at implant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rep_for_credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifier for sales rep who will receive credit for the sale.</description>
        <inlineHelpText>Identifier for sales rep who will receive credit for the sale.</inlineHelpText>
        <label>Rep for Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders_MDRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WorkOrderUpdator.cls
/*
 * This class contains the methods used to update workorder record.
 * @Revision History: 
 *
 */
public class WorkOrderUpdator {  
   
   /*
    * This method updates the workorder record
    * @param    wo    Instance of workorder object
    * @param    woRecId    Workorder record Id    
    */
    @AuraEnabled 
    public static void updateWorkOrderredords(WorkOrder wo, String woRecId) {
        WorkOrder workodr = [SELECT id, rep_for_credit__c, rep_at_implant__c, no_rep_present_at_implant__c FROM WorkOrder WHERE Id =: woRecId];
        workodr.rep_for_credit__c = wo.rep_for_credit__c;
        workodr.rep_at_implant__c= wo.rep_at_implant__c;
        workodr.no_rep_present_at_implant__c = wo.no_rep_present_at_implant__c;
        try {
            update workodr;
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}