objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>implanting physician CONTACT record assigned by SFDC
removed Implanting Physician: Account: Account ID = Work Order: Account ID filter criteria</description>
        <inlineHelpText>implanting physician CONTACT record assigned by SFDC</inlineHelpText>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that no BIOTRONIK representative was present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SendEmailControllerTest.cls
/*
 * Test class for SendEmailController
 *  Created Date - 4/2/2018
 *  Created by   - susi
 */
@isTest
private class SendEmailControllerTest {
    
    public static testMethod void testGetRecords() {
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        Contact con = TestDataFactory.createPhysician(false);
        con.accountId = acc.id;
        insert con;
        
        Test.startTest();
            //Calling the method
            SendEmailController.wrapper  wp = SendEmailController.getRecords(con.Id);
            System.AssertEquals(wp.c.Email,con.Email);
        Test.stopTest();
        
    }
    
    public static testMethod void testGetlookupFieldValues() {
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        Contact con = TestDataFactory.createPhysician(false);
        con.accountId = acc.id;
        insert con;
        
        workorder wo = new workorder();
        wo.implanting_physician__c = con.id;
        wo.no_rep_present_at_implant__c = true;
        wo.AccountId = acc.id;
        insert wo;
        
        Test.startTest();
            //Calling the method
            List<SendEmailController.KeyValueWrapper>  wp = SendEmailController.getlookupFieldValues(wo.Id);
        Test.stopTest();
        
    }
}