objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>implanting physician CONTACT record assigned by SFDC
removed Implanting Physician: Account: Account ID = Work Order: Account ID filter criteria</description>
        <inlineHelpText>implanting physician CONTACT record assigned by SFDC</inlineHelpText>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that no BIOTRONIK representative was present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PermanentIdcardGeneratorTest.cls
/*
 * Test class for PermanentIdcardGenerator
 *  Created Date - April 9, 2018
 *  Created by   - susi
 */
@isTest
private class PermanentIdcardGeneratorTest {
	   
    public static testMethod void testUpdatePrintDate() {
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        Contact contph = TestDataFactory.createPhysician(false);
        contph.accountId = acc.id;
        insert contph;
        
        Contact cont = TestDataFactory.createPatient(false);
        cont.accountId = acc.id;
        insert cont;
        
        workorder wo = new workorder();
        wo.implanting_physician__c = contph.id;
        wo.no_rep_present_at_implant__c = true;
        wo.AccountId = acc.id;
        insert wo;
        
        Test.startTest();
        	List<Contact> cList = new List<Contact>{cont};
       		ApexPages.StandardSetController controller = new ApexPages.StandardSetController(cList);
        	controller.setSelected(cList);
            PermanentIdcardGenerator idGen = new PermanentIdcardGenerator(controller);  
        	PermanentIdcardGenerator.isAllPatients(cont.id);
            idGen.updatePrintDate();
        Test.stopTest();    
    }
}