objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>implanting_physician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>implanting physician CONTACT record assigned by SFDC
removed Implanting Physician: Account: Account ID = Work Order: Account ID filter criteria</description>
        <inlineHelpText>implanting physician CONTACT record assigned by SFDC</inlineHelpText>
        <label>Implanting Physician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Physician</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implant Procedures (Implanting Physician)</relationshipLabel>
        <relationshipName>Orders_MDRFs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>no_rep_present_at_implant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system must allow the user entering the MDRF to indicate that no BIOTRONIK representative was present at the implant.</description>
        <label>No Rep present at implant</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CustomLookUpControllerTest.cls
/*
 *  Test class for CustomLookUpController  
 *  Created Date - March 6, 2018
 *  Created by   - Sumit
 * 
 * Revision History - 
 * Date             | Developer Name                | Version               | Changes/Ticket Number 
 * ================================================================================================      
 *  
 */
@isTest 
private class CustomLookUpControllerTest {
    static testMethod void fetchLookUpValuesTest() {
        workorder wodr = createWorkorder();  
        Test.startTest();
        	System.assertEquals(0, customLookUpController.fetchLookUpValues(wodr.Id, 'User', 'User', 'RepforCredit').size());
        Test.stopTest();
    }
    
    private static workorder createWorkorder() {
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        Contact con = TestDataFactory.createPhysician(false);
        con.accountid = acc.id;
        insert con;
                
        /*Territory2 t2 = new Territory2();
        t2.developerName = 'Testing';
        insert t2;
        
        ObjectTerritory2Association ota = new ObjectTerritory2Association();
        ota.ObjectId = acc.id;
        ota.Territory2Id = t2.id;
        insert ota;
        
        UserTerritory2Association uta = new UserTerritory2Association();
        uta.Territory2Id = t2.id;
        uta.UserId = u.id;
        insert uta; */
        
        workorder wo = new workorder();
        wo.implanting_physician__c = con.id;
        wo.no_rep_present_at_implant__c = true;
        wo.AccountId = acc.id;
        insert wo;
        return wo;
    }
}